import type { FoodProduct } from "@/lib/food-products-types";

/**
 * Lokalna baza produktów GymBrat (makro na porcję).
 * Skan kodu najpierw szuka tutaj, potem w Open Food Facts.
 */
export const FOOD_PRODUCTS_LOCAL: FoodProduct[] = [
  {
    id: "local-jogurt-grecki-0",
    barcode: "5900643032016",
    name: "Jogurt grecki 0%",
    brand: "Bakoma",
    servingLabel: "150 g",
    calories: 82,
    proteinG: 15,
    fatG: 0.3,
    carbsG: 5,
    source: "local",
  },
  {
    id: "local-twarog-chudy",
    barcode: "5900820001234",
    name: "Twaróg chudy",
    brand: "Piątnica",
    servingLabel: "200 g",
    calories: 176,
    proteinG: 36,
    fatG: 1,
    carbsG: 6,
    source: "local",
  },
  {
    id: "local-jajko-l",
    barcode: "5900001000001",
    name: "Jajko kurze L",
    servingLabel: "1 szt. (58 g)",
    calories: 80,
    proteinG: 7,
    fatG: 5.5,
    carbsG: 0.4,
    source: "local",
  },
  {
    id: "local-piers-kurczaka",
    barcode: "5901234123457",
    name: "Pierś z kurczaka bez skóry",
    servingLabel: "100 g",
    calories: 110,
    proteinG: 23,
    fatG: 1.5,
    carbsG: 0,
    source: "local",
  },
  {
    id: "local-losos-filet",
    barcode: "5901234123464",
    name: "Filet z łososia",
    servingLabel: "100 g",
    calories: 208,
    proteinG: 20,
    fatG: 13,
    carbsG: 0,
    source: "local",
  },
  {
    id: "local-tunczyk-woda",
    barcode: "5900397012345",
    name: "Tuńczyk w wodzie",
    brand: "Graal",
    servingLabel: "1 puszka odsączona (130 g)",
    calories: 116,
    proteinG: 26,
    fatG: 1,
    carbsG: 0,
    source: "local",
  },
  {
    id: "local-ryz-bialy",
    barcode: "5900783001112",
    name: "Ryż biały ugotowany",
    servingLabel: "100 g",
    calories: 130,
    proteinG: 2.7,
    fatG: 0.3,
    carbsG: 28,
    source: "local",
  },
  {
    id: "local-platki-owsiane",
    barcode: "5900012002223",
    name: "Płatki owsiane",
    brand: "Kupiec",
    servingLabel: "40 g (suchych)",
    calories: 148,
    proteinG: 5.4,
    fatG: 2.8,
    carbsG: 24,
    source: "local",
  },
  {
    id: "local-banan",
    barcode: "5900002000002",
    name: "Banan",
    servingLabel: "1 szt. średni (120 g)",
    calories: 107,
    proteinG: 1.3,
    fatG: 0.4,
    carbsG: 27,
    source: "local",
  },
  {
    id: "local-jablko",
    barcode: "5900002000003",
    name: "Jabłko",
    servingLabel: "1 szt. (150 g)",
    calories: 78,
    proteinG: 0.4,
    fatG: 0.3,
    carbsG: 19,
    source: "local",
  },
  {
    id: "local-chleb-zytni",
    barcode: "5900821003334",
    name: "Chleb żytni razowy",
    servingLabel: "1 kromka (40 g)",
    calories: 90,
    proteinG: 3,
    fatG: 0.8,
    carbsG: 17,
    source: "local",
  },
  {
    id: "local-maslo-orzechowe",
    barcode: "5900643011111",
    name: "Masło orzechowe 100%",
    brand: "Skippy / lokalne",
    servingLabel: "20 g",
    calories: 120,
    proteinG: 5,
    fatG: 10,
    carbsG: 3.5,
    source: "local",
  },
  {
    id: "local-mleko-15",
    barcode: "5900820005555",
    name: "Mleko 1,5%",
    brand: "Łaciate",
    servingLabel: "250 ml",
    calories: 118,
    proteinG: 8.3,
    fatG: 3.8,
    carbsG: 12,
    source: "local",
  },
  {
    id: "local-ser-light",
    barcode: "5900643022222",
    name: "Ser żółty light",
    brand: "Hochland",
    servingLabel: "2 plasterki (40 g)",
    calories: 100,
    proteinG: 12,
    fatG: 5,
    carbsG: 1,
    source: "local",
  },
  {
    id: "local-szynka-drobiowa",
    barcode: "5902194001111",
    name: "Szynka drobiowa",
    brand: "Morliny",
    servingLabel: "3 plastry (45 g)",
    calories: 48,
    proteinG: 8,
    fatG: 1.2,
    carbsG: 1,
    source: "local",
  },
  {
    id: "local-hummus",
    barcode: "5900014111222",
    name: "Hummus klasyczny",
    brand: "Sabra / lokalne",
    servingLabel: "50 g",
    calories: 110,
    proteinG: 4,
    fatG: 8,
    carbsG: 6,
    source: "local",
  },
  {
    id: "local-ciecierzyca",
    barcode: "5900783012345",
    name: "Ciecierzyca z puszki",
    servingLabel: "100 g odsączonych",
    calories: 120,
    proteinG: 7,
    fatG: 2,
    carbsG: 17,
    source: "local",
  },
  {
    id: "local-makaron-pelnoziarnisty",
    barcode: "5900783099999",
    name: "Makaron pełnoziarnisty ugotowany",
    brand: "Barilla",
    servingLabel: "100 g",
    calories: 124,
    proteinG: 5,
    fatG: 1,
    carbsG: 23,
    source: "local",
  },
  {
    id: "local-ziemniak",
    barcode: "5900003000004",
    name: "Ziemniak ugotowany",
    servingLabel: "150 g",
    calories: 110,
    proteinG: 2.5,
    fatG: 0.2,
    carbsG: 25,
    source: "local",
  },
  {
    id: "local-brokul",
    barcode: "5900003000005",
    name: "Brokuł gotowany",
    servingLabel: "150 g",
    calories: 52,
    proteinG: 4.5,
    fatG: 0.5,
    carbsG: 8,
    source: "local",
  },
  {
    id: "local-oliwa",
    barcode: "5900015123456",
    name: "Oliwa z oliwek",
    servingLabel: "1 łyżka (10 g)",
    calories: 88,
    proteinG: 0,
    fatG: 10,
    carbsG: 0,
    source: "local",
  },
  {
    id: "local-awokado",
    barcode: "5900002000006",
    name: "Awokado",
    servingLabel: "1/2 szt. (70 g)",
    calories: 112,
    proteinG: 1.4,
    fatG: 10,
    carbsG: 4,
    source: "local",
  },
  {
    id: "local-bialko-wpc",
    barcode: "5907654321098",
    name: "Odżywka białkowa WPC wanilia",
    brand: "GymBrat",
    servingLabel: "1 miarka (30 g)",
    calories: 112,
    proteinG: 24,
    fatG: 1.5,
    carbsG: 2,
    source: "local",
  },
  {
    id: "local-skyr",
    barcode: "5900643044444",
    name: "Skyr naturalny",
    brand: "Piątnica",
    servingLabel: "150 g",
    calories: 90,
    proteinG: 16,
    fatG: 0.3,
    carbsG: 5.5,
    source: "local",
  },
  {
    id: "local-cottage",
    barcode: "5900820007777",
    name: "Serek wiejski light",
    brand: "Piątnica",
    servingLabel: "200 g",
    calories: 140,
    proteinG: 22,
    fatG: 4,
    carbsG: 4,
    source: "local",
  },
  {
    id: "local-indyk-piers",
    barcode: "5901234123471",
    name: "Pierś z indyka",
    servingLabel: "100 g",
    calories: 104,
    proteinG: 24,
    fatG: 1,
    carbsG: 0,
    source: "local",
  },
  {
    id: "local-wolowina-chuda",
    barcode: "5901234123488",
    name: "Wołowina chuda (pieczona)",
    servingLabel: "100 g",
    calories: 170,
    proteinG: 26,
    fatG: 7,
    carbsG: 0,
    source: "local",
  },
  {
    id: "local-kasza-gryczana",
    barcode: "5900783008888",
    name: "Kasza gryczana ugotowana",
    servingLabel: "100 g",
    calories: 92,
    proteinG: 3.4,
    fatG: 0.6,
    carbsG: 20,
    source: "local",
  },
  {
    id: "local-tortilla",
    barcode: "5902194012345",
    name: "Tortilla pełnoziarnista",
    brand: "Mission",
    servingLabel: "1 szt. (50 g)",
    calories: 140,
    proteinG: 5,
    fatG: 3.5,
    carbsG: 22,
    source: "local",
  },
  {
    id: "local-mocca",
    barcode: "5900016001111",
    name: "Czekolada gorzka 70%",
    brand: "Lindt / lokalne",
    servingLabel: "20 g",
    calories: 110,
    proteinG: 1.8,
    fatG: 8,
    carbsG: 7,
    source: "local",
  },
  {
    id: "local-orzechy-wloskie",
    barcode: "5900017002222",
    name: "Orzechy włoskie",
    servingLabel: "20 g",
    calories: 130,
    proteinG: 3,
    fatG: 13,
    carbsG: 2.5,
    source: "local",
  },
  {
    id: "local-migdaly",
    barcode: "5900017003333",
    name: "Migdały",
    servingLabel: "20 g",
    calories: 116,
    proteinG: 4.2,
    fatG: 10,
    carbsG: 4,
    source: "local",
  },
  {
    id: "local-pomidor",
    barcode: "5900003000007",
    name: "Pomidor",
    servingLabel: "1 szt. (120 g)",
    calories: 22,
    proteinG: 1,
    fatG: 0.2,
    carbsG: 4.5,
    source: "local",
  },
  {
    id: "local-ogorek",
    barcode: "5900003000008",
    name: "Ogórek",
    servingLabel: "100 g",
    calories: 15,
    proteinG: 0.7,
    fatG: 0.1,
    carbsG: 3,
    source: "local",
  },
  {
    id: "local-kefir",
    barcode: "5900820008888",
    name: "Kefir 1,5%",
    brand: "Bakoma",
    servingLabel: "250 ml",
    calories: 100,
    proteinG: 8,
    fatG: 3.8,
    carbsG: 9,
    source: "local",
  },
  {
    id: "local-kanapka-szynka",
    barcode: null,
    name: "Kanapka z szynką i warzywami",
    servingLabel: "1 szt.",
    calories: 320,
    proteinG: 22,
    fatG: 8,
    carbsG: 38,
    source: "local",
  },
  {
    id: "local-salatka-kurczak",
    barcode: null,
    name: "Sałatka z kurczakiem i ryżem",
    servingLabel: "1 porcja",
    calories: 420,
    proteinG: 35,
    fatG: 10,
    carbsG: 45,
    source: "local",
  },
  {
    id: "local-owsianka-bialko",
    barcode: null,
    name: "Owsianka proteinowa",
    servingLabel: "1 miska",
    calories: 390,
    proteinG: 28,
    fatG: 8,
    carbsG: 50,
    source: "local",
  },
  {
    id: "local-omlet-3",
    barcode: null,
    name: "Omlet z 3 jajek",
    servingLabel: "1 porcja",
    calories: 240,
    proteinG: 20,
    fatG: 16,
    carbsG: 2,
    source: "local",
  },
  {
    id: "local-wrap-kurczak",
    barcode: null,
    name: "Wrap z kurczakiem",
    servingLabel: "1 szt.",
    calories: 380,
    proteinG: 32,
    fatG: 10,
    carbsG: 36,
    source: "local",
  },
];
