import type { FoodProduct } from "@/lib/food-products-types";

/**
 * Rozszerzona baza produktów (makro na 100 g / 100 ml) — wartości jak w typowych
 * tabelach PL (IŻŻ / Fitatu dla produktów generycznych).
 */
function per100(
  id: string,
  name: string,
  macros: { calories: number; proteinG: number; fatG: number; carbsG: number },
  extra?: Partial<FoodProduct>,
): FoodProduct {
  return {
    id,
    barcode: null,
    name,
    servingLabel: extra?.basisUnit === "ml" ? "100 ml" : "100 g",
    ...macros,
    source: "local",
    basisAmount: 100,
    basisUnit: extra?.basisUnit ?? "g",
    ...extra,
  };
}

export const FOOD_PRODUCTS_STAPLES_PL: FoodProduct[] = [
  // Owoce
  per100("local-malina", "Malina", { calories: 53, proteinG: 1.2, fatG: 0.7, carbsG: 12 }),
  per100("local-jagoda", "Jagoda", { calories: 57, proteinG: 0.7, fatG: 0.3, carbsG: 14.5 }),
  per100("local-jezyna", "Jeżyna", { calories: 43, proteinG: 1.4, fatG: 0.5, carbsG: 10 }),
  per100("local-czeresnia", "Czereśnia", { calories: 63, proteinG: 1, fatG: 0.2, carbsG: 14 }),
  per100("local-wisnia", "Wiśnia", { calories: 48, proteinG: 0.9, fatG: 0.3, carbsG: 12 }),
  per100("local-brzoskwinia", "Brzoskwinia", {
    calories: 39,
    proteinG: 0.9,
    fatG: 0.1,
    carbsG: 10,
  }, { gramsPerPiece: 150 }),
  per100("local-nektarynka", "Nektarynka", {
    calories: 44,
    proteinG: 1.1,
    fatG: 0.3,
    carbsG: 11,
  }, { gramsPerPiece: 140 }),
  per100("local-morela", "Morela", {
    calories: 48,
    proteinG: 1.4,
    fatG: 0.4,
    carbsG: 11,
  }, { gramsPerPiece: 55 }),
  per100("local-sliwka", "Śliwka", {
    calories: 46,
    proteinG: 0.7,
    fatG: 0.3,
    carbsG: 11,
  }, { gramsPerPiece: 40 }),
  per100("local-arbuz", "Arbuz", { calories: 30, proteinG: 0.6, fatG: 0.2, carbsG: 8 }),
  per100("local-melon", "Melon", { calories: 34, proteinG: 0.8, fatG: 0.2, carbsG: 8 }),
  per100("local-ananas", "Ananas", { calories: 50, proteinG: 0.5, fatG: 0.1, carbsG: 13 }),
  per100("local-mango", "Mango", { calories: 60, proteinG: 0.8, fatG: 0.4, carbsG: 15 }),
per100("local-limonka", "Limonka", { calories: 30, proteinG: 0.7, fatG: 0.2, carbsG: 11 }),
  per100("local-cytryna", "Cytryna", {
    calories: 29,
    proteinG: 1.1,
    fatG: 0.3,
    carbsG: 9,
  }, { gramsPerPiece: 85 }),
  per100("local-grejpfrut", "Grejpfrut", { calories: 42, proteinG: 0.8, fatG: 0.1, carbsG: 11 }),
  per100("local-rodzynki", "Rodzynki", { calories: 299, proteinG: 3.1, fatG: 0.5, carbsG: 79 }),
  per100("local-daktyle", "Daktyle suszone", {
    calories: 282,
    proteinG: 2.5,
    fatG: 0.4,
    carbsG: 75,
  }),
  per100("local-figi-suszone", "Figi suszone", {
    calories: 249,
    proteinG: 3.3,
    fatG: 0.9,
    carbsG: 64,
  }),

  // Warzywa
  per100("local-papryka-czerwona", "Papryka czerwona", {
    calories: 31,
    proteinG: 1,
    fatG: 0.3,
    carbsG: 6,
  }),
  per100("local-papryka-zielona", "Papryka zielona", {
    calories: 20,
    proteinG: 0.9,
    fatG: 0.2,
    carbsG: 4.6,
  }),
per100("local-kalafior", "Kalafior", { calories: 25, proteinG: 1.9, fatG: 0.3, carbsG: 5 }),
  per100("local-szpinak", "Szpinak", { calories: 23, proteinG: 2.9, fatG: 0.4, carbsG: 3.6 }),
  per100("local-salata", "Sałata", { calories: 14, proteinG: 1.4, fatG: 0.2, carbsG: 2.9 }),
  per100("local-rukola", "Rukola", { calories: 25, proteinG: 2.6, fatG: 0.7, carbsG: 3.7 }),
  per100("local-cukinia", "Cukinia", { calories: 17, proteinG: 1.2, fatG: 0.3, carbsG: 3.1 }),
  per100("local-baklazan", "Bakłażan", { calories: 25, proteinG: 1, fatG: 0.2, carbsG: 6 }),
per100("local-ziemniak-pieczony", "Ziemniak pieczony", {
    calories: 93,
    proteinG: 2.5,
    fatG: 0.1,
    carbsG: 21,
  }),
  per100("local-batat", "Batat ugotowany", {
    calories: 90,
    proteinG: 2,
    fatG: 0.2,
    carbsG: 21,
  }),
  per100("local-burak", "Burak ugotowany", {
    calories: 44,
    proteinG: 1.7,
    fatG: 0.2,
    carbsG: 10,
  }),
  per100("local-pietruszka-korzen", "Pietruszka korzeń", {
    calories: 36,
    proteinG: 2.6,
    fatG: 0.5,
    carbsG: 6.3,
  }),
  per100("local-seler-naciowy", "Seler naciowy", {
    calories: 14,
    proteinG: 0.7,
    fatG: 0.2,
    carbsG: 3,
  }),
  per100("local-cebula", "Cebula", { calories: 40, proteinG: 1.1, fatG: 0.1, carbsG: 9 }),
  per100("local-czosnek", "Czosnek", { calories: 149, proteinG: 6.4, fatG: 0.5, carbsG: 33 }),
  per100("local-kukurydza", "Kukurydza konserwowa", {
    calories: 86,
    proteinG: 3.3,
    fatG: 1.2,
    carbsG: 19,
  }),
  per100("local-groszek", "Groszek zielony", {
    calories: 81,
    proteinG: 5.4,
    fatG: 0.4,
    carbsG: 14,
  }),
  per100("local-fasolka-szparagowa", "Fasolka szparagowa", {
    calories: 31,
    proteinG: 1.8,
    fatG: 0.1,
    carbsG: 7,
  }),
  per100("local-kapusta-biala", "Kapusta biała", {
    calories: 25,
    proteinG: 1.3,
    fatG: 0.1,
    carbsG: 6,
  }),
  per100("local-kapusta-pekińska", "Kapusta pekińska", {
    calories: 13,
    proteinG: 1.2,
    fatG: 0.2,
    carbsG: 2.2,
  }),
  per100("local-kiszonka-ogorek", "Ogórek kiszony", {
    calories: 11,
    proteinG: 0.3,
    fatG: 0.1,
    carbsG: 2.3,
  }),
  per100("local-kiszonka-kapusta", "Kapusta kiszona", {
    calories: 19,
    proteinG: 1.1,
    fatG: 0.1,
    carbsG: 4.3,
  }),

  // Mięso / ryby / nabiał
  per100("local-udko-kurczaka", "Udko z kurczaka bez skóry", {
    calories: 155,
    proteinG: 21,
    fatG: 8,
    carbsG: 0,
  }),
  per100("local-udo-kurczaka-skora", "Udko z kurczaka ze skórą", {
    calories: 210,
    proteinG: 18,
    fatG: 15,
    carbsG: 0,
  }),
  per100("local-schab", "Schab wieprzowy", {
    calories: 157,
    proteinG: 21,
    fatG: 8,
    carbsG: 0,
  }),
  per100("local-mielone-wolowo-wieprzowe", "Mięso mielone wołowo-wieprzowe", {
    calories: 210,
    proteinG: 17,
    fatG: 16,
    carbsG: 0,
  }),
  per100("local-szynka-gotowana", "Szynka gotowana", {
    calories: 120,
    proteinG: 19,
    fatG: 5,
    carbsG: 1,
  }),
  per100("local-kurczak-wędliny", "Filet z kurczaka wędzony", {
    calories: 105,
    proteinG: 21,
    fatG: 2,
    carbsG: 1,
  }),
  per100("local-dorsz", "Dorsz", { calories: 82, proteinG: 18, fatG: 0.7, carbsG: 0 }),
  per100("local-mintaj", "Mintaj", { calories: 73, proteinG: 16.5, fatG: 0.8, carbsG: 0 }),
  per100("local-krewetki", "Krewetki gotowane", {
    calories: 99,
    proteinG: 24,
    fatG: 0.3,
    carbsG: 0.2,
  }),
per100("local-jogurt-naturalny", "Jogurt naturalny 2%", {
    calories: 60,
    proteinG: 4.3,
    fatG: 2,
    carbsG: 5.5,
  }),
per100("local-maslanka", "Maślanka", {
    calories: 37,
    proteinG: 3.3,
    fatG: 0.5,
    carbsG: 4.7,
  }),
  per100("local-serek-wiejski", "Serek wiejski chudy", {
    calories: 80,
    proteinG: 12,
    fatG: 2,
    carbsG: 3,
  }),
  per100("local-serek-wiejski-tlusty", "Serek wiejski tłusty", {
    calories: 120,
    proteinG: 11,
    fatG: 7,
    carbsG: 3,
  }),
  per100("local-mozarella-light", "Mozzarella light", {
    calories: 169,
    proteinG: 19,
    fatG: 10,
    carbsG: 1,
  }),
  per100("local-feta", "Ser feta", { calories: 264, proteinG: 14, fatG: 21, carbsG: 4 }),
  per100("local-cheddar", "Ser cheddar", {
    calories: 403,
    proteinG: 25,
    fatG: 33,
    carbsG: 1.3,
  }),
  per100("local-parmezan", "Parmezan", {
    calories: 392,
    proteinG: 36,
    fatG: 26,
    carbsG: 3.2,
  }),
  per100("local-ser-zolty", "Ser żółty gouda", {
    calories: 356,
    proteinG: 25,
    fatG: 27,
    carbsG: 2,
  }),
  per100("local-smietana-18", "Śmietana 18%", {
    calories: 181,
    proteinG: 2.5,
    fatG: 18,
    carbsG: 3.5,
  }),
  per100("local-smietana-12", "Śmietana 12%", {
    calories: 133,
    proteinG: 2.8,
    fatG: 12,
    carbsG: 3.8,
  }),
  per100("local-maslo", "Masło ekstra", {
    calories: 735,
    proteinG: 0.7,
    fatG: 82,
    carbsG: 0.7,
  }),
  per100("local-jajko-calosc-100", "Jajko (masa jadalna)", {
    calories: 155,
    proteinG: 13,
    fatG: 11,
    carbsG: 1.1,
  }),
  per100("local-bialko-jajka", "Białko jajka", {
    calories: 52,
    proteinG: 11,
    fatG: 0.2,
    carbsG: 0.7,
  }),
  per100("local-zolto-jajka", "Żółtko jajka", {
    calories: 322,
    proteinG: 16,
    fatG: 27,
    carbsG: 3.6,
  }),

  // Węglowodany / zboża
  per100("local-ryz-brazowy", "Ryż brązowy ugotowany", {
    calories: 112,
    proteinG: 2.3,
    fatG: 0.8,
    carbsG: 24,
  }),
per100("local-kasza-jaglana", "Kasza jaglana ugotowana", {
    calories: 98,
    proteinG: 3.1,
    fatG: 1,
    carbsG: 19,
  }),
  per100("local-kasza-jeczmienna", "Kasza jęczmienna ugotowana", {
    calories: 108,
    proteinG: 2.3,
    fatG: 0.4,
    carbsG: 24,
  }),
  per100("local-komosa", "Komosa ryżowa ugotowana", {
    calories: 120,
    proteinG: 4.4,
    fatG: 1.9,
    carbsG: 21,
  }),
  per100("local-makaron-ugotowany", "Makaron pszenny ugotowany", {
    calories: 131,
    proteinG: 5,
    fatG: 1.1,
    carbsG: 25,
  }),
  per100("local-makaron-razowy", "Makaron razowy ugotowany", {
    calories: 124,
    proteinG: 5.3,
    fatG: 1.5,
    carbsG: 23,
  }),
  per100("local-chleb-bialy", "Chleb pszenny", {
    calories: 265,
    proteinG: 9,
    fatG: 3.2,
    carbsG: 49,
  }),
  per100("local-chleb-tostowy", "Chleb tostowy", {
    calories: 270,
    proteinG: 8,
    fatG: 4,
    carbsG: 50,
  }),
  per100("local-bulka-kajzerka", "Bułka kajzerka", {
    calories: 280,
    proteinG: 9,
    fatG: 3.5,
    carbsG: 54,
  }),
per100("local-platki-kukurydziane", "Płatki kukurydziane", {
    calories: 360,
    proteinG: 7,
    fatG: 1,
    carbsG: 84,
  }),
  per100("local-musli", "Musli klasyczne", {
    calories: 370,
    proteinG: 9,
    fatG: 7,
    carbsG: 67,
  }),
  per100("local-granola", "Granola", { calories: 450, proteinG: 10, fatG: 15, carbsG: 65 }),
  per100("local-maka-pszenna", "Mąka pszenna", {
    calories: 364,
    proteinG: 10,
    fatG: 1,
    carbsG: 76,
  }),

  // Roślinne / tłuszcze / inne
per100("local-soczewica", "Soczewica ugotowana", {
    calories: 116,
    proteinG: 9,
    fatG: 0.4,
    carbsG: 20,
  }),
  per100("local-fasola-czerwona", "Fasola czerwona ugotowana", {
    calories: 127,
    proteinG: 8.7,
    fatG: 0.5,
    carbsG: 23,
  }),
  per100("local-tofu", "Tofu naturalne", {
    calories: 76,
    proteinG: 8,
    fatG: 4.8,
    carbsG: 1.9,
  }),
  per100("local-orzechy-laskowe", "Orzechy laskowe", {
    calories: 628,
    proteinG: 15,
    fatG: 61,
    carbsG: 17,
  }),
per100("local-nerkowce", "Nerkowce", {
    calories: 553,
    proteinG: 18,
    fatG: 44,
    carbsG: 30,
  }),
  per100("local-pestki-dyni", "Pestki dyni", {
    calories: 559,
    proteinG: 30,
    fatG: 49,
    carbsG: 11,
  }),
  per100("local-siemie-lniane", "Siemię lniane", {
    calories: 534,
    proteinG: 18,
    fatG: 42,
    carbsG: 29,
  }),
  per100("local-chia", "Nasiona chia", {
    calories: 486,
    proteinG: 17,
    fatG: 31,
    carbsG: 42,
  }),
per100("local-olej-rzepakowy", "Olej rzepakowy", {
    calories: 884,
    proteinG: 0,
    fatG: 100,
    carbsG: 0,
  }, { basisUnit: "ml" }),
  per100("local-olej-kokosowy", "Olej kokosowy", {
    calories: 862,
    proteinG: 0,
    fatG: 100,
    carbsG: 0,
  }, { basisUnit: "ml" }),
  per100("local-majonez", "Majonez", { calories: 680, proteinG: 1, fatG: 75, carbsG: 2 }),
  per100("local-ketchup", "Ketchup", { calories: 112, proteinG: 1.8, fatG: 0.3, carbsG: 26 }),
  per100("local-musztarda", "Musztarda", {
    calories: 66,
    proteinG: 4,
    fatG: 3,
    carbsG: 6,
  }),
  per100("local-miod", "Miód", { calories: 304, proteinG: 0.3, fatG: 0, carbsG: 82 }),
  per100("local-cukier", "Cukier biały", {
    calories: 400,
    proteinG: 0,
    fatG: 0,
    carbsG: 100,
  }),
  per100("local-czekolada-gorzka", "Czekolada gorzka 70%", {
    calories: 550,
    proteinG: 8,
    fatG: 40,
    carbsG: 45,
  }),
  per100("local-czekolada-mleczna", "Czekolada mleczna", {
    calories: 535,
    proteinG: 7,
    fatG: 30,
    carbsG: 59,
  }),
  per100("local-kakao", "Kakao 16%", { calories: 350, proteinG: 20, fatG: 12, carbsG: 35 }),
  per100("local-whey", "Odżywka białkowa WPC", {
    calories: 380,
    proteinG: 75,
    fatG: 5,
    carbsG: 8,
  }),
  per100("local-tofu-wedzone", "Tofu wędzone", {
    calories: 140,
    proteinG: 14,
    fatG: 8,
    carbsG: 3,
  }),
  per100("local-seitan", "Seitan", { calories: 141, proteinG: 25, fatG: 2, carbsG: 5 }),
  per100("local-napoj-migdalowy", "Napój migdałowy niesłodzony", {
    calories: 15,
    proteinG: 0.5,
    fatG: 1.1,
    carbsG: 0.3,
  }, { basisUnit: "ml" }),
  per100("local-napoj-owsiany", "Napój owsiany", {
    calories: 43,
    proteinG: 0.8,
    fatG: 1.5,
    carbsG: 6.7,
  }, { basisUnit: "ml" }),
  per100("local-cola", "Cola", {
    calories: 42,
    proteinG: 0,
    fatG: 0,
    carbsG: 10.6,
  }, { basisUnit: "ml" }),
  per100("local-sok-pomaranczowy", "Sok pomarańczowy", {
    calories: 45,
    proteinG: 0.7,
    fatG: 0.2,
    carbsG: 10,
  }, { basisUnit: "ml" }),
];
