import type { FoodProduct } from "@/lib/food-products-types";

/**
 * Popularne produkty z sieci PL / QSR — makro typowe / etykietowe (ok.).
 * Uzupełniają wyszukiwanie Jadłospisu, gdy Open Food Facts nie ma wpisu.
 */
export const FOOD_PRODUCTS_RETAIL_PL: FoodProduct[] = [
  {
    id: "retail-kfc-longer",
    barcode: null,
    name: "Longer",
    brand: "KFC",
    servingLabel: "1 szt.",
    calories: 470,
    proteinG: 28,
    fatG: 22,
    carbsG: 42,
    source: "local",
    basisAmount: 1,
    basisUnit: "pcs",
    gramsPerPiece: 195,
  },
  {
    id: "retail-kfc-twister",
    barcode: null,
    name: "Twister",
    brand: "KFC",
    servingLabel: "1 szt.",
    calories: 520,
    proteinG: 27,
    fatG: 24,
    carbsG: 48,
    source: "local",
    basisAmount: 1,
    basisUnit: "pcs",
    gramsPerPiece: 220,
  },
  {
    id: "retail-kfc-strips-3",
    barcode: null,
    name: "Strips (3 szt.)",
    brand: "KFC",
    servingLabel: "3 szt.",
    calories: 390,
    proteinG: 32,
    fatG: 20,
    carbsG: 22,
    source: "local",
    basisAmount: 3,
    basisUnit: "pcs",
    gramsPerPiece: 40,
  },
  {
    id: "retail-kfc-grander",
    barcode: null,
    name: "Grander",
    brand: "KFC",
    servingLabel: "1 szt.",
    calories: 610,
    proteinG: 34,
    fatG: 30,
    carbsG: 52,
    source: "local",
    basisAmount: 1,
    basisUnit: "pcs",
    gramsPerPiece: 260,
  },
  {
    id: "retail-lidl-chleb-gorski",
    barcode: null,
    name: "Chleb górski",
    brand: "Lidl",
    servingLabel: "100 g",
    calories: 250,
    proteinG: 8.5,
    fatG: 3.2,
    carbsG: 46,
    source: "local",
    basisAmount: 100,
    basisUnit: "g",
  },
  {
    id: "retail-lidl-chleb-sloneczny",
    barcode: null,
    name: "Chleb słoneczny",
    brand: "Lidl",
    servingLabel: "100 g",
    calories: 265,
    proteinG: 9,
    fatG: 4.5,
    carbsG: 47,
    source: "local",
    basisAmount: 100,
    basisUnit: "g",
  },
  {
    id: "retail-lidl-bulka-graham",
    barcode: null,
    name: "Bułka graham",
    brand: "Lidl",
    servingLabel: "1 szt. (70 g)",
    calories: 180,
    proteinG: 7,
    fatG: 2.5,
    carbsG: 32,
    source: "local",
    basisAmount: 1,
    basisUnit: "pcs",
    gramsPerPiece: 70,
  },
  {
    id: "retail-lidl-tortilla",
    barcode: null,
    name: "Tortilla pszenna",
    brand: "Lidl",
    servingLabel: "1 szt. (62 g)",
    calories: 190,
    proteinG: 5.5,
    fatG: 4,
    carbsG: 32,
    source: "local",
    basisAmount: 1,
    basisUnit: "pcs",
    gramsPerPiece: 62,
  },
  {
    id: "retail-lidl-skyr",
    barcode: null,
    name: "Skyr naturalny",
    brand: "Lidl",
    servingLabel: "150 g",
    calories: 90,
    proteinG: 16,
    fatG: 0.3,
    carbsG: 5.5,
    source: "local",
    basisAmount: 150,
    basisUnit: "g",
  },
  {
    id: "retail-biedronka-bulka-maslana",
    barcode: null,
    name: "Bułka maślana",
    brand: "Biedronka",
    servingLabel: "1 szt. (55 g)",
    calories: 175,
    proteinG: 5,
    fatG: 4.5,
    carbsG: 28,
    source: "local",
    basisAmount: 1,
    basisUnit: "pcs",
    gramsPerPiece: 55,
  },
  {
    id: "retail-biedronka-kajzerka",
    barcode: null,
    name: "Kajzerka",
    brand: "Biedronka",
    servingLabel: "1 szt. (50 g)",
    calories: 140,
    proteinG: 4.5,
    fatG: 1.5,
    carbsG: 27,
    source: "local",
    basisAmount: 1,
    basisUnit: "pcs",
    gramsPerPiece: 50,
  },
  {
    id: "retail-biedronka-chleb-tostowy",
    barcode: null,
    name: "Chleb tostowy jasny",
    brand: "Biedronka",
    servingLabel: "100 g",
    calories: 265,
    proteinG: 8,
    fatG: 3.5,
    carbsG: 50,
    source: "local",
    basisAmount: 100,
    basisUnit: "g",
  },
  {
    id: "retail-biedronka-bulka-hamburgerowa",
    barcode: null,
    name: "Bułka hamburgerowa",
    brand: "Biedronka",
    servingLabel: "1 szt. (75 g)",
    calories: 210,
    proteinG: 7,
    fatG: 3.5,
    carbsG: 38,
    source: "local",
    basisAmount: 1,
    basisUnit: "pcs",
    gramsPerPiece: 75,
  },
  {
    id: "retail-biedronka-gosto-skyr",
    barcode: null,
    name: "Skyr naturalny",
    brand: "Gosto / Biedronka",
    servingLabel: "150 g",
    calories: 88,
    proteinG: 15.5,
    fatG: 0.2,
    carbsG: 5.2,
    source: "local",
    basisAmount: 150,
    basisUnit: "g",
  },
  {
    id: "retail-zabka-kanapka-kurczak",
    barcode: null,
    name: "Kanapka z kurczakiem",
    brand: "Żabka",
    servingLabel: "1 szt.",
    calories: 380,
    proteinG: 22,
    fatG: 12,
    carbsG: 42,
    source: "local",
    basisAmount: 1,
    basisUnit: "pcs",
    gramsPerPiece: 180,
  },
  {
    id: "retail-mcdonalds-hamburger",
    barcode: null,
    name: "Hamburger",
    brand: "McDonald's",
    servingLabel: "1 szt.",
    calories: 250,
    proteinG: 13,
    fatG: 9,
    carbsG: 30,
    source: "local",
    basisAmount: 1,
    basisUnit: "pcs",
    gramsPerPiece: 100,
  },
  {
    id: "retail-mcdonalds-cheeseburger",
    barcode: null,
    name: "Cheeseburger",
    brand: "McDonald's",
    servingLabel: "1 szt.",
    calories: 300,
    proteinG: 15,
    fatG: 12,
    carbsG: 31,
    source: "local",
    basisAmount: 1,
    basisUnit: "pcs",
    gramsPerPiece: 115,
  },
  {
    id: "retail-subway-kurczak",
    barcode: null,
    name: "Kanapka kurczak teriyaki (15 cm)",
    brand: "Subway",
    servingLabel: "1 szt.",
    calories: 370,
    proteinG: 25,
    fatG: 5,
    carbsG: 55,
    source: "local",
    basisAmount: 1,
    basisUnit: "pcs",
    gramsPerPiece: 230,
  },
  {
    id: "retail-auchan-chleb-razowy",
    barcode: null,
    name: "Chleb razowy",
    brand: "Auchan",
    servingLabel: "100 g",
    calories: 230,
    proteinG: 8,
    fatG: 2.5,
    carbsG: 42,
    source: "local",
    basisAmount: 100,
    basisUnit: "g",
  },
  {
    id: "retail-carrefour-bulka-wiejska",
    barcode: null,
    name: "Bułka wiejska",
    brand: "Carrefour",
    servingLabel: "1 szt. (80 g)",
    calories: 210,
    proteinG: 7,
    fatG: 2,
    carbsG: 40,
    source: "local",
    basisAmount: 1,
    basisUnit: "pcs",
    gramsPerPiece: 80,
  },
  {
    id: "retail-pasibus-burger",
    barcode: null,
    name: "Burger klasyczny",
    brand: "Pasibus",
    servingLabel: "1 szt.",
    calories: 650,
    proteinG: 35,
    fatG: 35,
    carbsG: 48,
    source: "local",
    basisAmount: 1,
    basisUnit: "pcs",
    gramsPerPiece: 280,
  },
  {
    id: "retail-north-fish-box",
    barcode: null,
    name: "Fish & chips (porcja)",
    brand: "North Fish",
    servingLabel: "1 porcja",
    calories: 720,
    proteinG: 32,
    fatG: 38,
    carbsG: 65,
    source: "local",
    basisAmount: 1,
    basisUnit: "pcs",
    gramsPerPiece: 400,
  },
  {
    id: "retail-starbucks-latte",
    barcode: null,
    name: "Caffè Latte (grande, mleko 2%)",
    brand: "Starbucks",
    servingLabel: "1 szt. (470 ml)",
    calories: 190,
    proteinG: 12,
    fatG: 7,
    carbsG: 18,
    source: "local",
    basisAmount: 470,
    basisUnit: "ml",
  },
  {
    id: "retail-zywiec-zdroj",
    barcode: null,
    name: "Woda niegazowana",
    brand: "Żywiec Zdrój",
    servingLabel: "100 ml",
    calories: 0,
    proteinG: 0,
    fatG: 0,
    carbsG: 0,
    source: "local",
    basisAmount: 100,
    basisUnit: "ml",
  },
  {
    id: "retail-tymbark-jablko",
    barcode: null,
    name: "Sok jabłkowy",
    brand: "Tymbark",
    servingLabel: "100 ml",
    calories: 45,
    proteinG: 0.1,
    fatG: 0.1,
    carbsG: 11,
    source: "local",
    basisAmount: 100,
    basisUnit: "ml",
  },
];
