/** Autogenerowane przez scripts/generate-meal-catalog.mjs — unikalne dania, bez kombinatorów. */
import type { CatalogMeal } from "@/lib/meal-catalog-types";

export const MEAL_CATALOG_GENERATED: CatalogMeal[] = [
  {
    id: "sniadanie-0001-owsianka-proteinowa-z-jablkiem-i-cynamonem",
    slot: "sniadanie",
    title: "Owsianka proteinowa z jabłkiem i cynamonem",
    tagline: "Ciepłe śniadanie z błonnikiem",
    ingredients: ["60 g płatków owsianych","200 ml mleka 1,5%","20 g odżywki białkowej waniliowej","1 jabłko","1 łyżeczka cynamonu"],
    steps: ["Ugotuj płatki na mleku.","Zdejmij z ognia, wmieszaj białko.","Dodaj pokrojone jabłko i cynamon."],
    approximateMacros: { calories: 392, proteinG: 28, fatG: 8, carbsG: 52 },
    imagePromptEn: "protein oatmeal apple cinnamon bowl",
    prepMinutes: 12,
  },
  {
    id: "sniadanie-0002-tosty-francuskie-pelnoziarniste-z-twarogiem",
    slot: "sniadanie",
    title: "Tosty francuskie pełnoziarniste z twarogiem",
    tagline: "Słodko-słone śniadanie",
    ingredients: ["2 kromki chleba pełnoziarnistego","1 jajko","80 g twarogu chudego","50 ml mleka","1 łyżeczka miodu"],
    steps: ["Roztrzep jajko z mlekiem.","Obtocz chleb i podsmaż na patelni.","Podawaj z twarogiem i miodem."],
    approximateMacros: { calories: 380, proteinG: 26, fatG: 12, carbsG: 42 },
    imagePromptEn: "whole grain french toast cottage cheese",
    prepMinutes: 15,
  },
  {
    id: "sniadanie-0003-shakshuka-z-ciecierzyca",
    slot: "sniadanie",
    title: "Shakshuka z ciecierzycą",
    tagline: "Bliskowschodnie śniadanie na ciepło",
    ingredients: ["2 jajka","150 g pomidorów krojonych","80 g ciecierzycy z puszki","1/2 cebuli","przyprawy: kumin, papryka, czosnek"],
    steps: ["Zeszklij cebulę, dodaj pomidory i przyprawy.","Dodaj ciecierzycę, wbij jajka.","Duś pod przykryciem do ścięcia białka."],
    approximateMacros: { calories: 326, proteinG: 22, fatG: 14, carbsG: 28 },
    imagePromptEn: "shakshuka chickpeas skillet breakfast",
    prepMinutes: 20,
  },
  {
    id: "sniadanie-0004-kanapka-club-z-indykiem-i-jajkiem",
    slot: "sniadanie",
    title: "Kanapka club z indykiem i jajkiem",
    tagline: "Sycące śniadanie do pracy",
    ingredients: ["3 kromki tosta graham","80 g pieczonej piersi indyka","1 jajko na twardo","liście sałaty","1 łyżeczka musztardy"],
    steps: ["Opiecz tosty.","Ułóż warstwy: indyk, jajko, sałata, musztarda.","Przekrój na pół."],
    approximateMacros: { calories: 362, proteinG: 32, fatG: 10, carbsG: 36 },
    imagePromptEn: "turkey egg club sandwich",
    prepMinutes: 12,
  },
  {
    id: "sniadanie-0005-pancakes-bananowe-z-jogurtem-greckim",
    slot: "sniadanie",
    title: "Pancakes bananowe z jogurtem greckim",
    tagline: "Bez mąki — tylko banan i jajka",
    ingredients: ["1 banan","2 jajka","150 g jogurtu greckiego 0%","szczypta proszku do pieczenia","kilka malin"],
    steps: ["Zblenduj banana z jajkami.","Smaż małe placki na nieprzywierającej patelni.","Podawaj z jogurtem i malinami."],
    approximateMacros: { calories: 338, proteinG: 24, fatG: 10, carbsG: 38 },
    imagePromptEn: "banana egg pancakes greek yogurt berries",
    prepMinutes: 15,
  },
  {
    id: "sniadanie-0006-kasza-jaglana-na-mleku-z-gruszka",
    slot: "sniadanie",
    title: "Kasza jaglana na mleku z gruszką",
    tagline: "Bezglutenowe śniadanie",
    ingredients: ["50 g kaszy jaglanej","250 ml mleka 1,5%","1 gruszka","10 g orzechów laskowych","szczypta wanilii"],
    steps: ["Ugotuj jagłę na mleku.","Dodaj pokrojoną gruszkę.","Posyp orzechami."],
    approximateMacros: { calories: 384, proteinG: 14, fatG: 12, carbsG: 55 },
    imagePromptEn: "millet porridge pear hazelnuts",
    prepMinutes: 20,
  },
  {
    id: "sniadanie-0007-frittata-ze-szpinakiem-i-feta",
    slot: "sniadanie",
    title: "Frittata ze szpinakiem i fetą",
    tagline: "Pieczony omlet na kilka porcji",
    ingredients: ["3 jajka","80 g szpinaku","40 g fety","1 pomidor","1 łyżeczka oliwy"],
    steps: ["Podduś szpinak.","Wymieszaj z jajkami i fetą, przelej do formy.","Piecz 15 min w 180°C."],
    approximateMacros: { calories: 334, proteinG: 26, fatG: 22, carbsG: 8 },
    imagePromptEn: "spinach feta frittata slice",
    prepMinutes: 25,
  },
  {
    id: "sniadanie-0008-bowl-chia-z-mango-i-kokosem",
    slot: "sniadanie",
    title: "Bowl chia z mango i kokosem",
    tagline: "Przygotuj wieczorem",
    ingredients: ["30 g nasion chia","200 ml napoju sojowego","1/2 mango","10 g wiórków kokosowych","1 łyżeczka miodu"],
    steps: ["Wymieszaj chia z napojem, odstaw na noc.","Rano dodaj mango i kokos.","Posłodź miodem."],
    approximateMacros: { calories: 318, proteinG: 12, fatG: 14, carbsG: 36 },
    imagePromptEn: "chia pudding mango coconut bowl",
    prepMinutes: 5,
  },
  {
    id: "sniadanie-0009-quesadilla-sniadaniowa-z-jajkiem-i-fasola",
    slot: "sniadanie",
    title: "Quesadilla śniadaniowa z jajkiem i fasolą",
    tagline: "Meksykański start dnia",
    ingredients: ["1 tortilla pełnoziarnista","1 jajko","80 g czarnej fasoli","30 g sera light","salsa lub pomidor"],
    steps: ["Usmaż jajko na placku.","Dodaj fasolę i ser, złóż tortillę.","Zrumień z obu stron."],
    approximateMacros: { calories: 382, proteinG: 24, fatG: 14, carbsG: 40 },
    imagePromptEn: "breakfast quesadilla egg black beans",
    prepMinutes: 12,
  },
  {
    id: "sniadanie-0010-smothie-bowl-z-jagodami-i-granola",
    slot: "sniadanie",
    title: "Smothie bowl z jagodami i granolą",
    tagline: "Zimne śniadanie w misce",
    ingredients: ["150 g mrożonych jagód","120 g skyru","1/2 banana","25 g granoli","5 g masła orzechowego"],
    steps: ["Zblenduj jagody, skyr i banana.","Przelej do miski.","Posyp granolą i masłem orzechowym."],
    approximateMacros: { calories: 346, proteinG: 22, fatG: 10, carbsG: 42 },
    imagePromptEn: "berry smoothie bowl granola",
    prepMinutes: 8,
  },
  {
    id: "sniadanie-0011-jajka-w-koszulkach-na-toscie-z-awokado",
    slot: "sniadanie",
    title: "Jajka w koszulkach na toście z awokado",
    tagline: "Klasyka po nowemu",
    ingredients: ["2 jajka","1 tost graham","1/2 awokado","szczypta chili","sok z cytryny"],
    steps: ["Ugotuj jajka w koszulkach.","Rozgnieć awokado z cytryną na toście.","Ułóż jajka, posyp chili."],
    approximateMacros: { calories: 340, proteinG: 18, fatG: 20, carbsG: 22 },
    imagePromptEn: "poached eggs avocado toast",
    prepMinutes: 15,
  },
  {
    id: "sniadanie-0012-ryz-jasminowy-na-mleku-kokosowym-z-kardamonem",
    slot: "sniadanie",
    title: "Ryż jaśminowy na mleku kokosowym z kardamonem",
    tagline: "Azjatyckie śniadanie",
    ingredients: ["50 g ryżu jaśminowego","150 ml mleka kokosowego light","100 ml wody","szczypta kardamonu","kilka orzechów nerkowca"],
    steps: ["Ugotuj ryż na mieszance mleka i wody.","Dopraw kardamonem.","Posyp nerkowcami."],
    approximateMacros: { calories: 368, proteinG: 8, fatG: 16, carbsG: 48 },
    imagePromptEn: "jasmine rice coconut milk cardamom breakfast",
    prepMinutes: 25,
  },
  {
    id: "sniadanie-0013-wrap-sniadaniowy-z-lososiem-wedzonym",
    slot: "sniadanie",
    title: "Wrap śniadaniowy z łososiem wędzonym",
    tagline: "Omega-3 na start",
    ingredients: ["1 tortilla","60 g łososia wędzonego","80 g serka wiejskiego light","ogórek","koperek"],
    steps: ["Posmaruj tortillę serkiem.","Ułóż łososia, ogórek i koper.","Zwiń ciasno."],
    approximateMacros: { calories: 332, proteinG: 26, fatG: 12, carbsG: 30 },
    imagePromptEn: "smoked salmon breakfast wrap",
    prepMinutes: 8,
  },
  {
    id: "sniadanie-0014-polenta-z-jajkiem-i-pieczarkami",
    slot: "sniadanie",
    title: "Polenta z jajkiem i pieczarkami",
    tagline: "Włoski poranek",
    ingredients: ["50 g polenty","1 jajko","100 g pieczarek","10 g parmezanu","szczypta tymianku"],
    steps: ["Ugotuj polentę.","Usmaż pieczarki z tymiankiem.","Podawaj z jajkiem sadzonym i parmezanem."],
    approximateMacros: { calories: 334, proteinG: 16, fatG: 14, carbsG: 36 },
    imagePromptEn: "polenta fried egg mushrooms",
    prepMinutes: 20,
  },
  {
    id: "sniadanie-0015-budyn-jaglany-z-kakao-i-bananem",
    slot: "sniadanie",
    title: "Budyń jaglany z kakao i bananem",
    tagline: "Na słodko bez cukru",
    ingredients: ["45 g kaszy jaglanej","250 ml mleka","1 łyżeczka kakao","1 banan","5 g gorzkiej czekolady"],
    steps: ["Ugotuj jagłę na mleku z kakao.","Zblenduj z połową banana.","Udekoruj bananem i czekoladą."],
    approximateMacros: { calories: 352, proteinG: 12, fatG: 8, carbsG: 58 },
    imagePromptEn: "millet cocoa banana pudding breakfast",
    prepMinutes: 20,
  },
  {
    id: "sniadanie-0016-omlet-japonski-tamagoyaki-z-ryzem",
    slot: "sniadanie",
    title: "Omlet japoński tamagoyaki z ryżem",
    tagline: "Słodkawy omlet rolka",
    ingredients: ["3 jajka","1 łyżeczka sosu sojowego","1 łyżeczka mirinu lub miodu","80 g ugotowanego ryżu","nori (opcjonalnie)"],
    steps: ["Roztrzep jajka z soją i mirinem.","Smaż warstwami i zwijaj.","Podawaj z ryżem."],
    approximateMacros: { calories: 342, proteinG: 20, fatG: 14, carbsG: 34 },
    imagePromptEn: "tamagoyaki japanese omelette rice",
    prepMinutes: 18,
  },
  {
    id: "sniadanie-0017-placki-z-cukinii-z-sosem-jogurtowym",
    slot: "sniadanie",
    title: "Placki z cukinii z sosem jogurtowym",
    tagline: "Warzywne śniadanie",
    ingredients: ["1 mała cukinia","1 jajko","30 g mąki owsianej","100 g jogurtu naturalnego","czosnek i koper"],
    steps: ["Zetrzyj cukinię, odsącz.","Wymieszaj z jajkiem i mąką, smaż placki.","Podawaj z jogurtem czosnkowym."],
    approximateMacros: { calories: 266, proteinG: 16, fatG: 10, carbsG: 28 },
    imagePromptEn: "zucchini fritters yogurt dip breakfast",
    prepMinutes: 20,
  },
  {
    id: "sniadanie-0018-kasza-manna-z-kakao-i-twarogiem",
    slot: "sniadanie",
    title: "Kasza manna z kakao i twarogiem",
    tagline: "Dzieciństwo w wersji fitness",
    ingredients: ["40 g kaszy manny","250 ml mleka 1,5%","100 g twarogu","1 łyżeczka kakao","1 łyżeczka miodu"],
    steps: ["Ugotuj manną na mleku z kakao.","Przełóż do miski z twarogiem.","Posłodź miodem."],
    approximateMacros: { calories: 344, proteinG: 24, fatG: 8, carbsG: 44 },
    imagePromptEn: "semolina cocoa cottage cheese bowl",
    prepMinutes: 12,
  },
  {
    id: "sniadanie-0019-bagel-z-humusem-jajkiem-i-pieczywem",
    slot: "sniadanie",
    title: "Bagel z humusem, jajkiem i pieczywem",
    tagline: "Śródziemnomorski talerz",
    ingredients: ["2 jajka na twardo","50 g humusu","2 kromki chleba żytniego","ogórek i pomidor","oliwa + za'atar"],
    steps: ["Ugotuj jajka.","Ułóż humus, warzywa i jajka.","Skrop oliwą, posyp za'atar, podawaj z chlebem."],
    approximateMacros: { calories: 410, proteinG: 22, fatG: 18, carbsG: 40 },
    imagePromptEn: "hummus eggs mediterranean breakfast plate",
    prepMinutes: 15,
  },
  {
    id: "sniadanie-0020-gofry-owsiane-z-serkiem-wiejskim",
    slot: "sniadanie",
    title: "Gofry owsiane z serkiem wiejskim",
    tagline: "Na gofrownicy lub patelni",
    ingredients: ["50 g płatków owsianych","1 jajko","80 ml mleka","150 g serka wiejskiego light","owoce sezonowe"],
    steps: ["Zblenduj płatki z jajkiem i mlekiem.","Piecz gofry.","Podawaj z serkiem i owocami."],
    approximateMacros: { calories: 362, proteinG: 28, fatG: 10, carbsG: 40 },
    imagePromptEn: "oat waffles cottage cheese fruit",
    prepMinutes: 20,
  },
  {
    id: "drugie_sniadanie-0021-kanapka-zytnia-z-pasta-z-tunczyka-i-ogorkiem",
    slot: "drugie_sniadanie",
    title: "Kanapka żytnia z pastą z tuńczyka i ogórkiem",
    tagline: "Wysokobiałkowa przekąska",
    ingredients: ["2 kromki chleba żytniego","80 g tuńczyka w wodzie","1 łyżeczka jogurtu","ogórek","szczypiorek"],
    steps: ["Odcedź tuńczyka, wymieszaj z jogurtem.","Posmaruj pieczywo.","Dodaj ogórek i szczypiorek."],
    approximateMacros: { calories: 268, proteinG: 28, fatG: 4, carbsG: 30 },
    imagePromptEn: "rye tuna cucumber sandwich",
    prepMinutes: 8,
  },
  {
    id: "drugie_sniadanie-0022-wrap-z-kurczakiem-teriyaki-i-kapusta",
    slot: "drugie_sniadanie",
    title: "Wrap z kurczakiem teriyaki i kapustą",
    tagline: "Azjatycki lunchbox",
    ingredients: ["1 tortilla","100 g kurczaka","1 łyżeczka sosu teriyaki","kapusta pekińska","marchewka starta"],
    steps: ["Usmaż kurczaka, polej teriyaki.","Ułóż z warzywami na tortilli.","Zwiń wrap."],
    approximateMacros: { calories: 328, proteinG: 30, fatG: 8, carbsG: 34 },
    imagePromptEn: "chicken teriyaki wrap cabbage",
    prepMinutes: 15,
  },
  {
    id: "drugie_sniadanie-0023-skyr-z-granola-i-malinami",
    slot: "drugie_sniadanie",
    title: "Skyr z granolą i malinami",
    tagline: "Szybkie białko",
    ingredients: ["200 g skyru naturalnego","30 g granoli","80 g malin"],
    steps: ["Przełóż skyr do miski.","Posyp granolą i malinami."],
    approximateMacros: { calories: 278, proteinG: 24, fatG: 6, carbsG: 32 },
    imagePromptEn: "skyr granola raspberries bowl",
    prepMinutes: 3,
  },
  {
    id: "drugie_sniadanie-0024-salatka-grecka-mini-z-feta-light",
    slot: "drugie_sniadanie",
    title: "Sałatka grecka mini z fetą light",
    tagline: "Warzywa w drodze",
    ingredients: ["100 g ogórka","100 g pomidora","40 g fety light","oliwki","1 łyżeczka oliwy","oregano"],
    steps: ["Pokrój warzywa.","Dodaj fetę i oliwki.","Skrop oliwą, posyp oregano."],
    approximateMacros: { calories: 222, proteinG: 12, fatG: 14, carbsG: 12 },
    imagePromptEn: "mini greek salad feta light",
    prepMinutes: 8,
  },
  {
    id: "drugie_sniadanie-0025-shake-czekoladowy-z-maslem-orzechowym",
    slot: "drugie_sniadanie",
    title: "Shake czekoladowy z masłem orzechowym",
    tagline: "Po treningu rano",
    ingredients: ["30 g białka czekoladowego","250 ml mleka 1,5%","10 g masła orzechowego","1/2 banana"],
    steps: ["Zblenduj wszystkie składniki.","Wypij schłodzony."],
    approximateMacros: { calories: 348, proteinG: 32, fatG: 12, carbsG: 28 },
    imagePromptEn: "chocolate peanut butter protein shake",
    prepMinutes: 4,
  },
  {
    id: "drugie_sniadanie-0026-tost-z-awokado-pomidorem-i-mozarella-light",
    slot: "drugie_sniadanie",
    title: "Tost z awokado, pomidorem i mozarellą light",
    tagline: "Włoska nuta",
    ingredients: ["1 duży tost","1/3 awokado","1 pomidor","40 g mozzarelli light","bazylia"],
    steps: ["Opiecz tost.","Rozgnieć awokado, dodaj pomidor i ser.","Posyp bazylią."],
    approximateMacros: { calories: 302, proteinG: 16, fatG: 14, carbsG: 28 },
    imagePromptEn: "avocado tomato mozzarella toast",
    prepMinutes: 7,
  },
  {
    id: "drugie_sniadanie-0027-rollsy-z-szynka-drobiowa-i-warzywami",
    slot: "drugie_sniadanie",
    title: "Rollsy z szynką drobiową i warzywami",
    tagline: "Bez pieczywa",
    ingredients: ["4 plastry szynki drobiowej","40 g serka śmietankowego light","papryka","ogórek","rukola"],
    steps: ["Posmaruj szynkę serkiem.","Ułóż warzywa i zwiń rolady."],
    approximateMacros: { calories: 192, proteinG: 22, fatG: 8, carbsG: 8 },
    imagePromptEn: "turkey ham veggie rolls",
    prepMinutes: 8,
  },
  {
    id: "drugie_sniadanie-0028-hummus-z-marchewka-i-pieczywem-chrupkim",
    slot: "drugie_sniadanie",
    title: "Hummus z marchewką i pieczywem chrupkim",
    tagline: "Roślinna przekąska",
    ingredients: ["80 g humusu","2 marchewki","2 pieczywa chrupkie","papryka"],
    steps: ["Pokrój warzywa w słupki.","Podawaj z humusem i pieczywem."],
    approximateMacros: { calories: 292, proteinG: 10, fatG: 12, carbsG: 36 },
    imagePromptEn: "hummus carrot crispbread snack",
    prepMinutes: 5,
  },
  {
    id: "drugie_sniadanie-0029-omlet-w-kubku-z-mikrofalowki",
    slot: "drugie_sniadanie",
    title: "Omlet w kubku z mikrofalówki",
    tagline: "Biurowe 3 minuty",
    ingredients: ["2 jajka","30 ml mleka","szpinak","20 g sera","sól, pieprz"],
    steps: ["Roztrzep jajka z mlekiem w kubku.","Dodaj szpinak i ser.","Mikrofaluj 60–90 s, mieszając w połowie."],
    approximateMacros: { calories: 214, proteinG: 18, fatG: 14, carbsG: 4 },
    imagePromptEn: "microwave mug omelette spinach",
    prepMinutes: 5,
  },
  {
    id: "drugie_sniadanie-0030-jogurt-grecki-z-miodem-i-orzechami-wloskimi",
    slot: "drugie_sniadanie",
    title: "Jogurt grecki z miodem i orzechami włoskimi",
    tagline: "Prosta klasyka",
    ingredients: ["200 g jogurtu greckiego 0%","1 łyżeczka miodu","15 g orzechów włoskich"],
    steps: ["Jogurt przełóż do miski.","Polej miodem, posyp orzechami."],
    approximateMacros: { calories: 242, proteinG: 20, fatG: 10, carbsG: 18 },
    imagePromptEn: "greek yogurt honey walnuts",
    prepMinutes: 2,
  },
  {
    id: "drugie_sniadanie-0031-kanapka-z-pasta-jajeczna-i-rukola",
    slot: "drugie_sniadanie",
    title: "Kanapka z pastą jajeczną i rukolą",
    tagline: "Klasyka lunchboxa",
    ingredients: ["2 kromki chleba","2 jajka","1 łyżeczka majonezu light","rukola","szczypiorek"],
    steps: ["Ugotuj jajka, zrób pastę.","Posmaruj pieczywo, dodaj rukolę."],
    approximateMacros: { calories: 292, proteinG: 18, fatG: 12, carbsG: 28 },
    imagePromptEn: "egg salad sandwich rocket",
    prepMinutes: 12,
  },
  {
    id: "drugie_sniadanie-0032-edamame-z-sola-morska-i-chili",
    slot: "drugie_sniadanie",
    title: "Edamame z solą morską i chili",
    tagline: "Azjatycka przekąska",
    ingredients: ["150 g edamame w strąkach","sól morska","szczypta chili","sok z limonki"],
    steps: ["Ugotuj lub podgrzej edamame.","Posól, dodaj chili i limonkę."],
    approximateMacros: { calories: 200, proteinG: 18, fatG: 8, carbsG: 14 },
    imagePromptEn: "edamame sea salt chili snack",
    prepMinutes: 8,
  },
  {
    id: "drugie_sniadanie-0033-twarozek-z-rzodkiewka-i-szczypiorkiem-na-pieczywie",
    slot: "drugie_sniadanie",
    title: "Twarożek z rzodkiewką i szczypiorkiem na pieczywie",
    tagline: "Polski klasyk",
    ingredients: ["150 g twarogu","rzodkiewka","szczypiorek","2 kromki chleba","szczypta soli"],
    steps: ["Rozduś twaróg z warzywami.","Posmaruj pieczywo."],
    approximateMacros: { calories: 270, proteinG: 24, fatG: 6, carbsG: 30 },
    imagePromptEn: "cottage cheese radish chives bread",
    prepMinutes: 7,
  },
  {
    id: "drugie_sniadanie-0034-sushi-bowl-mini-z-tunczykiem-i-ryzem",
    slot: "drugie_sniadanie",
    title: "Sushi bowl mini z tuńczykiem i ryżem",
    tagline: "Bez rolowania",
    ingredients: ["80 g ryżu sushi ugotowanego","70 g tuńczyka","ogórek","awokado 1/4","sos sojowy light"],
    steps: ["Ułóż ryż w misce.","Dodaj tuńczyka i warzywa.","Polej soją."],
    approximateMacros: { calories: 312, proteinG: 24, fatG: 8, carbsG: 36 },
    imagePromptEn: "mini tuna sushi bowl",
    prepMinutes: 10,
  },
  {
    id: "drugie_sniadanie-0035-nalesnik-owsiany-z-twarogiem-i-truskawkami",
    slot: "drugie_sniadanie",
    title: "Naleśnik owsiany z twarogiem i truskawkami",
    tagline: "Jeden duży naleśnik",
    ingredients: ["40 g płatków owsianych","1 jajko","100 g twarogu","80 g truskawek","odrobina mleka"],
    steps: ["Zblenduj płatki z jajkiem i mlekiem, usmaż naleśnik.","Nałóż twaróg i truskawki, zwiń."],
    approximateMacros: { calories: 338, proteinG: 26, fatG: 10, carbsG: 36 },
    imagePromptEn: "oat pancake cottage cheese strawberries",
    prepMinutes: 12,
  },
  {
    id: "obiad-0036-piers-z-kurczaka-sous-vide-styl-z-kasza-gryczana-i-burak",
    slot: "obiad",
    title: "Pierś z kurczaka sous-vide styl z kaszą gryczaną i burakiem",
    tagline: "Polski talerz siłowy",
    ingredients: ["150 g piersi kurczaka","70 g kaszy gryczanej","150 g buraka pieczonego","szczypta majeranku","1 łyżeczka oliwy"],
    steps: ["Usmaż lub upiecz kurczaka.","Ugotuj kaszę.","Podawaj z burakiem i majerankiem."],
    approximateMacros: { calories: 468, proteinG: 42, fatG: 12, carbsG: 48 },
    imagePromptEn: "chicken buckwheat roasted beet plate",
    prepMinutes: 30,
  },
  {
    id: "obiad-0037-losos-pieczony-z-batatem-i-brokulem",
    slot: "obiad",
    title: "Łosoś pieczony z batatem i brokułem",
    tagline: "Omega-3 + warzywa",
    ingredients: ["150 g łososia","200 g batata","150 g brokułu","cytryna","koperek"],
    steps: ["Piecz łososia 15 min w 190°C.","Ugotuj lub upiecz batata.","Blanszuj brokuł, skrop cytryną."],
    approximateMacros: { calories: 458, proteinG: 34, fatG: 18, carbsG: 40 },
    imagePromptEn: "baked salmon sweet potato broccoli",
    prepMinutes: 30,
  },
  {
    id: "obiad-0038-bowl-buddha-z-tofu-quinoa-i-warzywami",
    slot: "obiad",
    title: "Bowl buddha z tofu, quinoa i warzywami",
    tagline: "Wegański obiad",
    ingredients: ["120 g tofu","60 g quinoa","czerwona kapusta","marchewka","sos tahini 1 łyżeczka"],
    steps: ["Ugotuj quinoa.","Usmaż tofu na złoto.","Ułóż bowl, polej tahini."],
    approximateMacros: { calories: 408, proteinG: 24, fatG: 16, carbsG: 42 },
    imagePromptEn: "tofu quinoa buddha bowl tahini",
    prepMinutes: 25,
  },
  {
    id: "obiad-0039-chili-con-carne-z-indykiem-i-ryzem",
    slot: "obiad",
    title: "Chili con carne z indykiem i ryżem",
    tagline: "Lżejsza wersja klasyki",
    ingredients: ["150 g mięsa z indyka","100 g czerwonej fasoli","pomidory krojone","60 g ryżu","przyprawy chili"],
    steps: ["Zrumień indyka z przyprawami.","Dodaj pomidory i fasolę, duś 15 min.","Podawaj z ryżem."],
    approximateMacros: { calories: 450, proteinG: 40, fatG: 10, carbsG: 50 },
    imagePromptEn: "turkey chili con carne rice",
    prepMinutes: 35,
  },
  {
    id: "obiad-0040-dorsz-w-panierce-panko-z-puree-z-kalafiora",
    slot: "obiad",
    title: "Dorsz w panierce panko z puree z kalafiora",
    tagline: "Ryba w lekkiej panierce",
    ingredients: ["160 g dorsza","30 g panko","1 jajko","300 g kalafiora","szczypta gałki"],
    steps: ["Obtocz rybę w jajku i panko, upiecz.","Ugotuj kalafior, zblenduj na puree.","Dopraw gałką."],
    approximateMacros: { calories: 346, proteinG: 36, fatG: 10, carbsG: 28 },
    imagePromptEn: "panko cod cauliflower mash",
    prepMinutes: 30,
  },
  {
    id: "obiad-0041-pad-thai-z-krewetkami-wersja-light",
    slot: "obiad",
    title: "Pad thai z krewetkami (wersja light)",
    tagline: "Azjatycki wok",
    ingredients: ["120 g krewetek","80 g makaronu ryżowego","kiełki","1 jajko","sos rybny + limonka (odrobina)"],
    steps: ["Ugotuj makaron.","Smaż krewetki i jajko.","Wymieszaj z makaronem i kiełkami."],
    approximateMacros: { calories: 410, proteinG: 32, fatG: 10, carbsG: 48 },
    imagePromptEn: "light prawn pad thai",
    prepMinutes: 25,
  },
  {
    id: "obiad-0042-gulasz-wolowy-z-papryka-i-kasza-jeczmienna",
    slot: "obiad",
    title: "Gulasz wołowy z papryką i kaszą jęczmienną",
    tagline: "Sycący obiad",
    ingredients: ["140 g chudej wołowiny","papryka","cebula","60 g kaszy jęczmiennej","papryka słodka"],
    steps: ["Zrumień mięso.","Duś z warzywami i przyprawami.","Podawaj z kaszą."],
    approximateMacros: { calories: 454, proteinG: 38, fatG: 14, carbsG: 44 },
    imagePromptEn: "beef paprika stew barley",
    prepMinutes: 50,
  },
  {
    id: "obiad-0043-kurczak-tikka-z-ryzem-basmati-i-raita",
    slot: "obiad",
    title: "Kurczak tikka z ryżem basmati i raita",
    tagline: "Indyjskie aromaty",
    ingredients: ["150 g kurczaka","jogurt + przyprawy tikka","60 g ryżu basmati","ogórek + jogurt na raita"],
    steps: ["Marynuj kurczaka w jogurcie i przyprawach, upiecz.","Ugotuj ryż.","Zrób raita z ogórka."],
    approximateMacros: { calories: 442, proteinG: 40, fatG: 10, carbsG: 48 },
    imagePromptEn: "chicken tikka basmati raita",
    prepMinutes: 40,
  },
  {
    id: "obiad-0044-makaron-pelnoziarnisty-z-tunczykiem-i-cukinia",
    slot: "obiad",
    title: "Makaron pełnoziarnisty z tuńczykiem i cukinią",
    tagline: "Szybki obiad z puszki",
    ingredients: ["70 g makaronu pełnoziarnistego","80 g tuńczyka","1 cukinia","czosnek","pomidorki koktajlowe"],
    steps: ["Ugotuj makaron.","Smaż cukinię z czosnkiem.","Wymieszaj z tuńczykiem i makaronem."],
    approximateMacros: { calories: 416, proteinG: 34, fatG: 8, carbsG: 52 },
    imagePromptEn: "wholewheat pasta tuna zucchini",
    prepMinutes: 20,
  },
  {
    id: "obiad-0045-kaczka-confit-styl-light-z-puree-z-selera",
    slot: "obiad",
    title: "Kaczka confit styl light z puree z selera",
    tagline: "Odświętny obiad",
    ingredients: ["150 g udźca kaczki bez skóry","300 g selera","jabłko","tymianek"],
    steps: ["Upiecz kaczkę z tymiankiem.","Ugotuj seler z jabłkiem, zrób puree.","Podawaj razem."],
    approximateMacros: { calories: 384, proteinG: 32, fatG: 16, carbsG: 28 },
    imagePromptEn: "duck breast celery apple puree",
    prepMinutes: 45,
  },
  {
    id: "obiad-0046-falafel-pieczony-z-salatka-tabbouleh",
    slot: "obiad",
    title: "Falafel pieczony z sałatką tabbouleh",
    tagline: "Bliski Wschód bez smażenia",
    ingredients: ["4–5 falafel z ciecierzycy (pieczone)","bulgur 40 g","pietruszka","pomidor","sok z cytryny"],
    steps: ["Upiecz falafel.","Ugotuj bulgur, wymieszaj tabbouleh.","Podawaj razem."],
    approximateMacros: { calories: 372, proteinG: 18, fatG: 12, carbsG: 48 },
    imagePromptEn: "baked falafel tabbouleh plate",
    prepMinutes: 35,
  },
  {
    id: "obiad-0047-risotto-z-krewetkami-i-szparagami",
    slot: "obiad",
    title: "Risotto z krewetkami i szparagami",
    tagline: "Kremowe bez śmietany",
    ingredients: ["70 g ryżu arborio","100 g krewetek","szparagi","bulion warzywny","parmezan 10 g"],
    steps: ["Smaż ryż, dolewaj bulion.","Dodaj szparagi i krewetki pod koniec.","Dopraw parmezanem."],
    approximateMacros: { calories: 400, proteinG: 28, fatG: 8, carbsG: 54 },
    imagePromptEn: "prawn asparagus risotto",
    prepMinutes: 35,
  },
  {
    id: "obiad-0048-schab-pieczony-z-ziemniakami-i-surowka-z-kapusty",
    slot: "obiad",
    title: "Schab pieczony z ziemniakami i surówką z kapusty",
    tagline: "Domowy obiad",
    ingredients: ["140 g schabu","200 g ziemniaków","kapusta + marchewka","musztarda"],
    steps: ["Natrij schab musztardą, upiecz.","Upiecz ziemniaki.","Zrób surówkę."],
    approximateMacros: { calories: 420, proteinG: 36, fatG: 12, carbsG: 42 },
    imagePromptEn: "roast pork potatoes cabbage salad",
    prepMinutes: 45,
  },
  {
    id: "obiad-0049-moussaka-light-z-baklazanem-i-indykiem",
    slot: "obiad",
    title: "Moussaka light z bakłażanem i indykiem",
    tagline: "Grecka zapiekanka",
    ingredients: ["1 bakłażan","120 g indyka mielonego","sos pomidorowy","beszamel light z mleka i mąki"],
    steps: ["Podpiecz bakłażana.","Usmaż indyka z sosem.","Ułóż warstwy, zalej beszamelem, piecz."],
    approximateMacros: { calories: 374, proteinG: 32, fatG: 14, carbsG: 30 },
    imagePromptEn: "light turkey moussaka eggplant",
    prepMinutes: 50,
  },
  {
    id: "obiad-0050-krewetki-w-sosie-czosnkowym-z-kasza-jaglana",
    slot: "obiad",
    title: "Krewetki w sosie czosnkowym z kaszą jaglaną",
    tagline: "Szybki wok",
    ingredients: ["140 g krewetek","60 g kaszy jaglanej","czosnek","natka pietruszki","oliwa 1 łyżeczka"],
    steps: ["Ugotuj jagłę.","Smaż krewetki z czosnkiem.","Podawaj z pietruszką."],
    approximateMacros: { calories: 352, proteinG: 30, fatG: 8, carbsG: 40 },
    imagePromptEn: "garlic prawns millet",
    prepMinutes: 20,
  },
  {
    id: "obiad-0051-burger-z-indyka-z-pieczywem-pelnoziarnistym-i-salatka",
    slot: "obiad",
    title: "Burger z indyka z pieczywem pełnoziarnistym i sałatką",
    tagline: "Comfort food fitness",
    ingredients: ["140 g mielonego indyka","bułka pełnoziarnista","sałata, pomidor","sos jogurtowy"],
    steps: ["Uformuj i usmaż kotleta.","Złóż burgera.","Dodaj sałatkę z boku."],
    approximateMacros: { calories: 420, proteinG: 38, fatG: 12, carbsG: 40 },
    imagePromptEn: "turkey burger wholegrain bun salad",
    prepMinutes: 25,
  },
  {
    id: "obiad-0052-paella-warzywna-z-kurczakiem",
    slot: "obiad",
    title: "Paella warzywna z kurczakiem",
    tagline: "Hiszpański ryż",
    ingredients: ["60 g ryżu","100 g kurczaka","papryka, groszek","szafran lub kurkuma","bulion"],
    steps: ["Zrumień kurczaka.","Dodaj ryż, warzywa i bulion.","Duś bez mieszania do wchłonięcia."],
    approximateMacros: { calories: 400, proteinG: 32, fatG: 8, carbsG: 50 },
    imagePromptEn: "chicken vegetable paella",
    prepMinutes: 40,
  },
  {
    id: "obiad-0053-zupa-tom-yum-z-kurczakiem-i-makaronem-ryzowym",
    slot: "obiad",
    title: "Zupa tom yum z kurczakiem i makaronem ryżowym",
    tagline: "Pikantna zupa-danie",
    ingredients: ["120 g kurczaka","pasta tom yum","80 g makaronu ryżowego","pieczarki","limonka"],
    steps: ["Ugotuj bulion z pastą.","Dodaj kurczaka i pieczarki.","Na końcu makaron i limonkę."],
    approximateMacros: { calories: 352, proteinG: 30, fatG: 8, carbsG: 40 },
    imagePromptEn: "tom yum chicken rice noodles",
    prepMinutes: 25,
  },
  {
    id: "obiad-0054-pieczona-piers-z-kaczki-z-kasza-i-zurawina",
    slot: "obiad",
    title: "Pieczona pierś z kaczki z kaszą i żurawiną",
    tagline: "Wykwintny obiad",
    ingredients: ["140 g piersi kaczki bez skóry","60 g kaszy gryczanej","żurawina","rozmaryn"],
    steps: ["Usmaż/upiecz pierś.","Ugotuj kaszę.","Podawaj z żurawiną."],
    approximateMacros: { calories: 422, proteinG: 34, fatG: 14, carbsG: 40 },
    imagePromptEn: "duck breast buckwheat cranberry",
    prepMinutes: 35,
  },
  {
    id: "obiad-0055-spaghetti-bolonskie-z-soczewica",
    slot: "obiad",
    title: "Spaghetti bolońskie z soczewicą",
    tagline: "Roślinna bolończyzna",
    ingredients: ["70 g spaghetti pełnoziarnistego","80 g czerwonej soczewicy","sos pomidorowy","marchew, seler","oregano"],
    steps: ["Ugotuj soczewicę z warzywami w sosie.","Ugotuj makaron.","Połącz."],
    approximateMacros: { calories: 382, proteinG: 24, fatG: 6, carbsG: 58 },
    imagePromptEn: "lentil bolognese wholewheat spaghetti",
    prepMinutes: 30,
  },
  {
    id: "podwieczorek-0056-jogurt-naturalny-z-kakao-i-bananem",
    slot: "podwieczorek",
    title: "Jogurt naturalny z kakao i bananem",
    tagline: "Słodka mini porcja",
    ingredients: ["150 g jogurtu naturalnego","1 łyżeczka kakao","1/2 banana"],
    steps: ["Wymieszaj jogurt z kakao.","Dodaj banana."],
    approximateMacros: { calories: 180, proteinG: 12, fatG: 4, carbsG: 24 },
    imagePromptEn: "yogurt cocoa banana snack",
    prepMinutes: 3,
  },
  {
    id: "podwieczorek-0057-garsc-migdalow-i-jablko",
    slot: "podwieczorek",
    title: "Garść migdałów i jabłko",
    tagline: "Proste combo",
    ingredients: ["20 g migdałów","1 jabłko"],
    steps: ["Umyj jabłko.","Jedz z migdałami."],
    approximateMacros: { calories: 216, proteinG: 5, fatG: 12, carbsG: 22 },
    imagePromptEn: "almonds apple snack",
    prepMinutes: 1,
  },
  {
    id: "podwieczorek-0058-koktajl-truskawkowy-na-kefirze",
    slot: "podwieczorek",
    title: "Koktajl truskawkowy na kefirze",
    tagline: "Orzeźwienie",
    ingredients: ["200 ml kefiru","100 g truskawek","5 g miodu"],
    steps: ["Zblenduj składniki."],
    approximateMacros: { calories: 138, proteinG: 10, fatG: 2, carbsG: 20 },
    imagePromptEn: "strawberry kefir smoothie",
    prepMinutes: 4,
  },
  {
    id: "podwieczorek-0059-ryzowki-z-twarogiem-i-miodem",
    slot: "podwieczorek",
    title: "Ryżówki z twarogiem i miodem",
    tagline: "Chrupiąco",
    ingredients: ["3 wafle ryżowe","80 g twarogu","1 łyżeczka miodu"],
    steps: ["Posmaruj wafle twarogiem.","Polej miodem."],
    approximateMacros: { calories: 186, proteinG: 14, fatG: 2, carbsG: 28 },
    imagePromptEn: "rice cakes cottage cheese honey",
    prepMinutes: 3,
  },
  {
    id: "podwieczorek-0060-marchewki-baby-z-hummusem",
    slot: "podwieczorek",
    title: "Marchewki baby z hummusem",
    tagline: "Warzywny dip",
    ingredients: ["150 g marchewek baby","40 g humusu"],
    steps: ["Podawaj marchewki z hummusem."],
    approximateMacros: { calories: 158, proteinG: 6, fatG: 6, carbsG: 20 },
    imagePromptEn: "baby carrots hummus snack",
    prepMinutes: 2,
  },
  {
    id: "podwieczorek-0061-serek-wiejski-z-ananasem",
    slot: "podwieczorek",
    title: "Serek wiejski z ananasem",
    tagline: "Szybkie białko",
    ingredients: ["150 g serka wiejskiego","80 g ananasa"],
    steps: ["Wymieszaj serek z ananasem."],
    approximateMacros: { calories: 164, proteinG: 18, fatG: 4, carbsG: 14 },
    imagePromptEn: "cottage cheese pineapple snack",
    prepMinutes: 2,
  },
  {
    id: "podwieczorek-0062-herbata-matcha-latte-z-mlekiem-i-bialkiem",
    slot: "podwieczorek",
    title: "Herbata matcha latte z mlekiem i białkiem",
    tagline: "Napój zamiast przekąski",
    ingredients: ["1 łyżeczka matchy","200 ml mleka","15 g białka waniliowego"],
    steps: ["Rozprowadź matchę.","Dodaj ciepłe mleko i białko, spień."],
    approximateMacros: { calories: 148, proteinG: 16, fatG: 4, carbsG: 12 },
    imagePromptEn: "matcha protein latte",
    prepMinutes: 5,
  },
  {
    id: "podwieczorek-0063-pieczone-chipsy-z-ciecierzycy",
    slot: "podwieczorek",
    title: "Pieczone chipsy z ciecierzycy",
    tagline: "Chrupiące",
    ingredients: ["100 g ciecierzycy z puszki","przyprawy","1 łyżeczka oliwy"],
    steps: ["Osusz ciecierzycę, wymieszaj z oliwą i przyprawami.","Piecz 25 min w 200°C."],
    approximateMacros: { calories: 182, proteinG: 10, fatG: 6, carbsG: 22 },
    imagePromptEn: "roasted chickpea chips",
    prepMinutes: 30,
  },
  {
    id: "podwieczorek-0064-kanapka-mini-z-pasta-z-avocado-i-jajkiem",
    slot: "podwieczorek",
    title: "Kanapka mini z pastą z avocado i jajkiem",
    tagline: "Pół porcji",
    ingredients: ["1 kromka chleba","1/4 awokado","1 jajko na twardo"],
    steps: ["Rozgnieć awokado na chlebie.","Dodaj pokrojone jajko."],
    approximateMacros: { calories: 220, proteinG: 12, fatG: 12, carbsG: 16 },
    imagePromptEn: "mini avocado egg open sandwich",
    prepMinutes: 8,
  },
  {
    id: "podwieczorek-0065-galaretka-proteinowa-z-owocami",
    slot: "podwieczorek",
    title: "Galaretka proteinowa z owocami",
    tagline: "Na zimno",
    ingredients: ["galaretka bez cukru","15 g żelatyny lub białka","owoce"],
    steps: ["Przygotuj galaretkę według przepisu.","Dodaj owoce, schłodź."],
    approximateMacros: { calories: 96, proteinG: 12, fatG: 0, carbsG: 12 },
    imagePromptEn: "protein jelly fruit cup",
    prepMinutes: 10,
  },
  {
    id: "podwieczorek-0066-tortilla-chips-pieczone-z-salsa",
    slot: "podwieczorek",
    title: "Tortilla chips pieczone z salsą",
    tagline: "Domowe chipsy",
    ingredients: ["1 tortilla pokrojona w trójkąty","salsa pomidorowa","przyprawy"],
    steps: ["Upiecz trójkąty tortilli.","Podawaj z salsą."],
    approximateMacros: { calories: 172, proteinG: 6, fatG: 4, carbsG: 28 },
    imagePromptEn: "baked tortilla chips salsa",
    prepMinutes: 15,
  },
  {
    id: "podwieczorek-0067-shake-kawowy-proteinowy",
    slot: "podwieczorek",
    title: "Shake kawowy proteinowy",
    tagline: "Popołudniowy boost",
    ingredients: ["espresso lub kawa","25 g białka","200 ml mleka","lód"],
    steps: ["Zblenduj kawę, białko i mleko z lodem."],
    approximateMacros: { calories: 188, proteinG: 26, fatG: 4, carbsG: 12 },
    imagePromptEn: "iced coffee protein shake",
    prepMinutes: 4,
  },
  {
    id: "kolacja-0068-salatka-cobb-light-z-kurczakiem",
    slot: "kolacja",
    title: "Sałatka Cobb light z kurczakiem",
    tagline: "Lekka kolacja",
    ingredients: ["120 g kurczaka","sałata rzymska","1 jajko","pomidor","ogórek","dressing jogurtowy"],
    steps: ["Usmaż kurczaka.","Ułóż sałatkę z jajkiem i warzywami.","Polej dressingiem."],
    approximateMacros: { calories: 300, proteinG: 36, fatG: 12, carbsG: 12 },
    imagePromptEn: "light chicken cobb salad",
    prepMinutes: 20,
  },
  {
    id: "kolacja-0069-pieczony-dorsz-z-cukinia-i-pomidorami",
    slot: "kolacja",
    title: "Pieczony dorsz z cukinią i pomidorami",
    tagline: "Jedna blacha",
    ingredients: ["160 g dorsza","cukinia","pomidorki koktajlowe","czosnek","zioła"],
    steps: ["Ułóż rybę i warzywa na blaszce.","Piecz 18 min w 190°C."],
    approximateMacros: { calories: 230, proteinG: 34, fatG: 6, carbsG: 10 },
    imagePromptEn: "baked cod zucchini tomatoes tray",
    prepMinutes: 25,
  },
  {
    id: "kolacja-0070-omlet-na-kolacje-z-pieczarkami-i-szpinakiem",
    slot: "kolacja",
    title: "Omlet na kolację z pieczarkami i szpinakiem",
    tagline: "Szybko i lekko",
    ingredients: ["3 jajka","pieczarki","szpinak","szczypta sera"],
    steps: ["Usmaż pieczarki i szpinak.","Wlej jajka, zetnij omlet."],
    approximateMacros: { calories: 256, proteinG: 22, fatG: 16, carbsG: 6 },
    imagePromptEn: "mushroom spinach dinner omelette",
    prepMinutes: 12,
  },
  {
    id: "kolacja-0071-zupa-krem-z-pieczonej-papryki-z-grzanka",
    slot: "kolacja",
    title: "Zupa krem z pieczonej papryki z grzanką",
    tagline: "Rozgrzewająca kolacja",
    ingredients: ["2 czerwone papryki","cebula","bulion","1 kromka pieczywa","odrobina śmietany 12%"],
    steps: ["Upiecz papryki, zblenduj z bulionem.","Dopraw śmietaną.","Podawaj z grzanką."],
    approximateMacros: { calories: 198, proteinG: 8, fatG: 6, carbsG: 28 },
    imagePromptEn: "roasted pepper soup crouton",
    prepMinutes: 35,
  },
  {
    id: "kolacja-0072-tacos-rybne-z-salsa-mango",
    slot: "kolacja",
    title: "Tacos rybne z salsą mango",
    tagline: "Lekka kolacja meksykańska",
    ingredients: ["120 g białej ryby","2 małe tortille","mango","cebula czerwona","limonka"],
    steps: ["Usmaż rybę.","Zrób salsę z mango.","Złóż tacos."],
    approximateMacros: { calories: 328, proteinG: 28, fatG: 8, carbsG: 36 },
    imagePromptEn: "fish tacos mango salsa",
    prepMinutes: 20,
  },
  {
    id: "kolacja-0073-salatka-z-komosy-pieczonego-buraka-i-koziego-sera",
    slot: "kolacja",
    title: "Sałatka z komosy, pieczonego buraka i koziego sera",
    tagline: "Kolorowa miska",
    ingredients: ["50 g quinoa","burak pieczony","40 g sera koziego","rukola","pestki dyni"],
    steps: ["Ugotuj quinoa.","Ułóż z burakiem i serem.","Posyp pestkami."],
    approximateMacros: { calories: 342, proteinG: 18, fatG: 14, carbsG: 36 },
    imagePromptEn: "quinoa beet goat cheese salad",
    prepMinutes: 25,
  },
  {
    id: "kolacja-0074-kurczak-w-sosie-musztardowym-z-puree-z-kalafiora",
    slot: "kolacja",
    title: "Kurczak w sosie musztardowym z puree z kalafiora",
    tagline: "Low-carb kolacja",
    ingredients: ["150 g kurczaka","musztarda + jogurt","kalafior na puree","szczypiorek"],
    steps: ["Usmaż kurczaka, polej sosem.","Zrób puree z kalafiora."],
    approximateMacros: { calories: 314, proteinG: 40, fatG: 10, carbsG: 16 },
    imagePromptEn: "mustard chicken cauliflower mash",
    prepMinutes: 25,
  },
  {
    id: "kolacja-0075-risotto-grzybowe-light",
    slot: "kolacja",
    title: "Risotto grzybowe light",
    tagline: "Wegańskie opcje: bulion warzywny",
    ingredients: ["60 g ryżu arborio","mieszanka grzybów","cebula","bulion","natka"],
    steps: ["Smaż ryż i grzyby.","Dolewaj bulion.","Dopraw natką."],
    approximateMacros: { calories: 284, proteinG: 10, fatG: 4, carbsG: 52 },
    imagePromptEn: "light mushroom risotto",
    prepMinutes: 35,
  },
  {
    id: "kolacja-0076-stek-z-tofu-z-warzywami-stir-fry",
    slot: "kolacja",
    title: "Stek z tofu z warzywami stir-fry",
    tagline: "Azjatycka kolacja roślinna",
    ingredients: ["140 g tofu","brokuł, papryka","sos sojowy light","imbir","ryż 40 g (opcjonalnie)"],
    steps: ["Usmaż tofu.","Dodaj warzywa i sos.","Podawaj z ryżem lub bez."],
    approximateMacros: { calories: 316, proteinG: 22, fatG: 12, carbsG: 30 },
    imagePromptEn: "tofu stir fry vegetables",
    prepMinutes: 20,
  },
  {
    id: "kolacja-0077-zapiekanka-z-cukinii-i-mielonego-indyka",
    slot: "kolacja",
    title: "Zapiekanka z cukinii i mielonego indyka",
    tagline: "Bez makaronu",
    ingredients: ["1 cukinia","120 g indyka mielonego","sos pomidorowy","ser light 30 g"],
    steps: ["Usmaż indyka z sosem.","Ułóż z cukinią, posyp serem, zapiecz."],
    approximateMacros: { calories: 300, proteinG: 32, fatG: 12, carbsG: 16 },
    imagePromptEn: "zucchini turkey bake",
    prepMinutes: 35,
  },
  {
    id: "kolacja-0078-salatka-nicoise-light",
    slot: "kolacja",
    title: "Sałatka niçoise light",
    tagline: "Francuska klasyka",
    ingredients: ["tuńczyk 80 g","jajko","fasolka szparagowa","ziemniak 1 mały","oliwki","sałata"],
    steps: ["Ugotuj jajko, ziemniak i fasolkę.","Ułóż z tuńczykiem i oliwkami."],
    approximateMacros: { calories: 306, proteinG: 30, fatG: 10, carbsG: 24 },
    imagePromptEn: "light salade nicoise",
    prepMinutes: 25,
  },
  {
    id: "kolacja-0079-krewetki-z-czosnkiem-na-salacie-lodowej",
    slot: "kolacja",
    title: "Krewetki z czosnkiem na sałacie lodowej",
    tagline: "Bardzo lekko",
    ingredients: ["140 g krewetek","czosnek","sałata lodowa","limonka","1 łyżeczka oliwy"],
    steps: ["Smaż krewetki z czosnkiem.","Podawaj na sałacie z limonką."],
    approximateMacros: { calories: 208, proteinG: 28, fatG: 8, carbsG: 6 },
    imagePromptEn: "garlic shrimp iceberg salad",
    prepMinutes: 12,
  },
  {
    id: "kolacja-0080-tortilla-pizza-z-kurczakiem-i-warzywami",
    slot: "kolacja",
    title: "Tortilla pizza z kurczakiem i warzywami",
    tagline: "Szybka „pizza”",
    ingredients: ["1 tortilla","sos pomidorowy","80 g kurczaka","papryka","ser light"],
    steps: ["Posmaruj tortillę sosem.","Dodaj dodatki, piecz 8 min."],
    approximateMacros: { calories: 330, proteinG: 28, fatG: 10, carbsG: 32 },
    imagePromptEn: "tortilla pizza chicken vegetables",
    prepMinutes: 15,
  },
  {
    id: "kolacja-0081-krem-z-cukinii-z-grzanka-pelnoziarnista",
    slot: "kolacja",
    title: "Krem z cukinii z grzanką pełnoziarnistą",
    tagline: "Kolacja-zupa",
    ingredients: ["2 cukinie","cebula","bulion","1 kromka chleba","odrobina jogurtu"],
    steps: ["Ugotuj warzywa w bulionie, zblenduj.","Dopraw jogurtem.","Podawaj z grzanką."],
    approximateMacros: { calories: 164, proteinG: 8, fatG: 4, carbsG: 24 },
    imagePromptEn: "zucchini cream soup wholegrain toast",
    prepMinutes: 25,
  },
  {
    id: "kolacja-0082-bowl-z-lososiem-ryzem-i-edamame",
    slot: "kolacja",
    title: "Bowl z łososiem, ryżem i edamame",
    tagline: "Kolacja z bilansem makro",
    ingredients: ["100 g łososia","50 g ryżu","80 g edamame","ogórek","sos sojowy"],
    steps: ["Upiecz łososia.","Ugotuj ryż i edamame.","Ułóż bowl."],
    approximateMacros: { calories: 414, proteinG: 32, fatG: 14, carbsG: 40 },
    imagePromptEn: "salmon rice edamame bowl",
    prepMinutes: 25,
  },
  {
    id: "kolacja-0083-placki-z-tunczyka-z-sosem-jogurtowym",
    slot: "kolacja",
    title: "Placki z tuńczyka z sosem jogurtowym",
    tagline: "Bez panierki",
    ingredients: ["1 puszka tuńczyka","1 jajko","2 łyżki płatków owsianych","jogurt + koper"],
    steps: ["Wymieszaj tuńczyka z jajkiem i płatkami.","Usmaż placki.","Podawaj z sosem."],
    approximateMacros: { calories: 256, proteinG: 30, fatG: 8, carbsG: 16 },
    imagePromptEn: "tuna fritters yogurt dill sauce",
    prepMinutes: 15,
  },
  {
    id: "kolacja-0084-wrap-z-falafellem-i-tahini-light",
    slot: "kolacja",
    title: "Wrap z falafellem i tahini light",
    tagline: "Wegetariańska kolacja",
    ingredients: ["3 falafle pieczone","tortilla pełnoziarnista","sałata","ogórek","sos tahini rozcieńczony jogurtem"],
    steps: ["Podgrzej falafle.","Zawiń w tortillę z warzywami i sosem."],
    approximateMacros: { calories: 406, proteinG: 22, fatG: 14, carbsG: 48 },
    imagePromptEn: "falafel wrap tahini yogurt",
    prepMinutes: 15,
  },
  {
    id: "kolacja-0085-omlet-z-pieczarkami-i-szczypiorkiem",
    slot: "kolacja",
    title: "Omlet z pieczarkami i szczypiorkiem",
    tagline: "Klasyczna kolacja białkowa",
    ingredients: ["3 jajka","100 g pieczarek","szczypiorek","1 łyżeczka oliwy"],
    steps: ["Podsmaż pieczarki.","Zalej jajkami, posyp szczypiorkiem."],
    approximateMacros: { calories: 248, proteinG: 22, fatG: 16, carbsG: 4 },
    imagePromptEn: "mushroom chive omelette",
    prepMinutes: 12,
  },
  {
    id: "drugie_sniadanie-0086-tost-z-pasta-z-tunczyka-i-ogorkiem",
    slot: "drugie_sniadanie",
    title: "Tost z pastą z tuńczyka i ogórkiem",
    tagline: "Szybkie drugie śniadanie",
    ingredients: ["2 kromki chleba","1/2 puszki tuńczyka","jogurt naturalny","ogórek"],
    steps: ["Wymieszaj tuńczyka z jogurtem.","Posmaruj tosty, dodaj ogórek."],
    approximateMacros: { calories: 262, proteinG: 24, fatG: 6, carbsG: 28 },
    imagePromptEn: "tuna yogurt toast cucumber",
    prepMinutes: 8,
  },
  {
    id: "drugie_sniadanie-0087-jogurt-islandzki-z-mango-i-limonka",
    slot: "drugie_sniadanie",
    title: "Jogurt islandzki z mango i limonką",
    tagline: "Świeży, wysokobiałkowy",
    ingredients: ["200 g skyr","80 g mango","sok z limonki","mięta"],
    steps: ["Pokrój mango.","Wymieszaj ze skyrem, dopraw limonką i miętą."],
    approximateMacros: { calories: 202, proteinG: 24, fatG: 2, carbsG: 22 },
    imagePromptEn: "skyr mango lime mint bowl",
    prepMinutes: 5,
  },
  {
    id: "drugie_sniadanie-0088-mini-wrap-z-szynka-drobiowa-i-rukola",
    slot: "drugie_sniadanie",
    title: "Mini wrap z szynką drobiową i rukolą",
    tagline: "Na wynos",
    ingredients: ["1 mała tortilla","60 g szynki drobiowej","rukola","ser light","pomidor"],
    steps: ["Ułóż składniki na tortilli.","Zawiń i przekrój na pół."],
    approximateMacros: { calories: 264, proteinG: 22, fatG: 8, carbsG: 26 },
    imagePromptEn: "turkey ham arugula mini wrap",
    prepMinutes: 7,
  },
  {
    id: "drugie_sniadanie-0089-koktajl-truskawkowy-z-kefirem",
    slot: "drugie_sniadanie",
    title: "Koktajl truskawkowy z kefirem",
    tagline: "Probiotyczny napój-posiłek",
    ingredients: ["250 ml kefiru","150 g truskawek","10 g płatków owsianych","odrobina miodu"],
    steps: ["Zblenduj wszystko na gładko."],
    approximateMacros: { calories: 220, proteinG: 14, fatG: 4, carbsG: 32 },
    imagePromptEn: "strawberry kefir smoothie oats",
    prepMinutes: 5,
  },
  {
    id: "drugie_sniadanie-0090-salatka-z-soczewica-i-feta-light",
    slot: "drugie_sniadanie",
    title: "Sałatka z soczewicą i fetą light",
    tagline: "Syty lunchbox",
    ingredients: ["100 g soczewicy ugotowanej","30 g fety light","ogórek","pomidor","oliwa 1 łyżeczka"],
    steps: ["Wymieszaj soczewicę z warzywami.","Dodaj fetę i oliwę."],
    approximateMacros: { calories: 256, proteinG: 18, fatG: 8, carbsG: 28 },
    imagePromptEn: "lentil feta cucumber tomato salad",
    prepMinutes: 10,
  },
  {
    id: "podwieczorek-0091-ryzowki-z-twarogiem-i-owocami-lesnymi",
    slot: "podwieczorek",
    title: "Ryżówki z twarogiem i owocami leśnymi",
    tagline: "Chrupiący podwieczorek",
    ingredients: ["2 wafle ryżowe","80 g twarogu","garść owoców leśnych","cynamon"],
    steps: ["Posmaruj wafle twarogiem.","Ułóż owoce, posyp cynamonem."],
    approximateMacros: { calories: 212, proteinG: 16, fatG: 4, carbsG: 28 },
    imagePromptEn: "rice cakes cottage cheese berries",
    prepMinutes: 5,
  },
  {
    id: "podwieczorek-0092-shake-czekoladowy-z-bananem",
    slot: "podwieczorek",
    title: "Shake czekoladowy z bananem",
    tagline: "Po treningu",
    ingredients: ["30 g białka czekoladowego","1 mały banan","250 ml mleka 1,5%"],
    steps: ["Zblenduj składniki na 20 sekund."],
    approximateMacros: { calories: 285, proteinG: 30, fatG: 5, carbsG: 30 },
    imagePromptEn: "chocolate protein banana shake",
    prepMinutes: 3,
  },
  {
    id: "podwieczorek-0093-hummus-z-marchewka-i-papryka",
    slot: "podwieczorek",
    title: "Hummus z marchewką i papryką",
    tagline: "Warzywny snack",
    ingredients: ["80 g humusu","marchew","papryka"],
    steps: ["Pokrój warzywa w słupki.","Podawaj z hummusem."],
    approximateMacros: { calories: 210, proteinG: 8, fatG: 10, carbsG: 22 },
    imagePromptEn: "hummus carrot pepper sticks",
    prepMinutes: 5,
  },
  {
    id: "podwieczorek-0094-twarozek-z-rzodkiewka-i-szczypiorkiem",
    slot: "podwieczorek",
    title: "Twarożek z rzodkiewką i szczypiorkiem",
    tagline: "Słony podwieczorek",
    ingredients: ["150 g twarogu chudego","rzodkiewka","szczypiorek","1 kromka chleba"],
    steps: ["Wymieszaj twaróg z warzywami.","Jedz z pieczywem."],
    approximateMacros: { calories: 204, proteinG: 22, fatG: 4, carbsG: 20 },
    imagePromptEn: "cottage cheese radish chives bread",
    prepMinutes: 7,
  },
  {
    id: "podwieczorek-0095-edamame-z-sola-morska-i-sezamem",
    slot: "podwieczorek",
    title: "Edamame z solą morską i sezamem",
    tagline: "Azjatycki snack",
    ingredients: ["150 g edamame w strąkach","sól morska","sezam"],
    steps: ["Obgotuj edamame 4 min.","Posyp solą i sezamem."],
    approximateMacros: { calories: 166, proteinG: 16, fatG: 6, carbsG: 12 },
    imagePromptEn: "edamame sea salt sesame",
    prepMinutes: 6,
  },
  {
    id: "podwieczorek-0096-kisiel-proteinowy-z-wisniami",
    slot: "podwieczorek",
    title: "Kisiel proteinowy z wiśniami",
    tagline: "Słodki, ale lekki",
    ingredients: ["15 g żelatyny lub kisielu","20 g białka waniliowego","100 g wiśni","woda"],
    steps: ["Przygotuj kisiel według opakowania.","Wmieszaj białko i wiśnie na ciepło."],
    approximateMacros: { calories: 169, proteinG: 22, fatG: 1, carbsG: 18 },
    imagePromptEn: "protein cherry jelly dessert",
    prepMinutes: 10,
  },
  {
    id: "sniadanie-0097-bowl-chia-z-mlekiem-kokosowym-light-i-kiwi",
    slot: "sniadanie",
    title: "Bowl chia z mlekiem kokosowym light i kiwi",
    tagline: "Na zimno z błonnikiem",
    ingredients: ["30 g nasion chia","200 ml mleka kokosowego light","1 kiwi","10 g wiórków kokosowych"],
    steps: ["Zamocz chia na noc.","Rano dodaj kiwi i wiórki."],
    approximateMacros: { calories: 278, proteinG: 10, fatG: 14, carbsG: 28 },
    imagePromptEn: "chia pudding kiwi coconut",
    prepMinutes: 5,
  },
  {
    id: "sniadanie-0098-jajka-w-koszulkach-na-szpinaku-z-pomidorkami",
    slot: "sniadanie",
    title: "Jajka w koszulkach na szpinaku z pomidorkami",
    tagline: "Lekkie śniadanie warzywne",
    ingredients: ["2 jajka","100 g szpinaku","pomidorki koktajlowe","czosnek"],
    steps: ["Zeszklij szpinak z czosnkiem.","Ugotuj jajka w koszulkach.","Podawaj z pomidorkami."],
    approximateMacros: { calories: 204, proteinG: 18, fatG: 12, carbsG: 6 },
    imagePromptEn: "poached eggs spinach cherry tomatoes",
    prepMinutes: 15,
  },
  {
    id: "sniadanie-0099-kasza-manna-na-mleku-z-kakao-i-gruszka",
    slot: "sniadanie",
    title: "Kasza manna na mleku z kakao i gruszką",
    tagline: "Dzieciństwo w wersji fitness",
    ingredients: ["40 g kaszy manny","250 ml mleka","1 łyżeczka kakao","1 gruszka"],
    steps: ["Ugotuj mannę na mleku z kakao.","Dodaj pokrojoną gruszkę."],
    approximateMacros: { calories: 320, proteinG: 14, fatG: 8, carbsG: 48 },
    imagePromptEn: "semolina cocoa pear porridge",
    prepMinutes: 12,
  },
  {
    id: "obiad-0100-kurczak-teriyaki-z-brokulem-i-ryzem",
    slot: "obiad",
    title: "Kurczak teriyaki z brokułem i ryżem",
    tagline: "Azjatycki klasyk",
    ingredients: ["140 g kurczaka","sos teriyaki light","150 g brokułu","50 g ryżu"],
    steps: ["Usmaż kurczaka, polej teriyaki.","Ugotuj ryż i brokuł na parze."],
    approximateMacros: { calories: 416, proteinG: 38, fatG: 8, carbsG: 48 },
    imagePromptEn: "chicken teriyaki broccoli rice",
    prepMinutes: 25,
  },
  {
    id: "obiad-0101-gulasz-z-indyka-z-papryka-i-kasza-gryczana",
    slot: "obiad",
    title: "Gulasz z indyka z papryką i kaszą gryczaną",
    tagline: "Rozgrzewający obiad",
    ingredients: ["150 g indyka","papryka, cebula","przyprawy do gulaszu","60 g kaszy gryczanej"],
    steps: ["Duś mięso z warzywami.","Ugotuj grykę osobno."],
    approximateMacros: { calories: 394, proteinG: 36, fatG: 10, carbsG: 40 },
    imagePromptEn: "turkey paprika goulash buckwheat",
    prepMinutes: 45,
  },
  {
    id: "obiad-0102-dorsz-w-panierce-z-platkow-z-puree-z-kalafiora",
    slot: "obiad",
    title: "Dorsz w panierce z płatków z puree z kalafiora",
    tagline: "Low-carb obiad rybny",
    ingredients: ["160 g dorsza","płatki owsiane + jajko do panierki","kalafior na puree","sok z cytryny"],
    steps: ["Obtocz rybę, usmaż.","Zblenduj ugotowany kalafior.","Dopraw cytryną."],
    approximateMacros: { calories: 322, proteinG: 36, fatG: 10, carbsG: 22 },
    imagePromptEn: "oat crusted cod cauliflower mash",
    prepMinutes: 30,
  },
];

export const MEAL_CATALOG_GENERATED_COUNT = 102;
