/** Autogenerowane przez scripts/generate-meal-catalog.mjs — unikalne dania, gramatura i kroki. */
import type { CatalogMeal } from "@/lib/meal-catalog-types";

export const MEAL_CATALOG_GENERATED: CatalogMeal[] = [
  {
    id: "sniadanie-0001-owsianka-proteinowa-z-jablkiem-i-cynamonem",
    slot: "sniadanie",
    title: "Owsianka proteinowa z jabłkiem i cynamonem",
    tagline: "Ciepłe śniadanie z błonnikiem",
    ingredients: ["60 g płatków owsianych","200 ml mleka 1,5%","20 g odżywki białkowej waniliowej","1 jabłko","1 łyżeczka cynamonu"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj płatki na mleku. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Zdejmij z ognia, wmieszaj białko.","Dodaj pokrojone jabłko i cynamon."],
    approximateMacros: { calories: 392, proteinG: 28, fatG: 8, carbsG: 52 },
    imagePromptEn: "protein oatmeal apple cinnamon bowl",
    prepMinutes: 12,
  },
  {
    id: "sniadanie-0002-tosty-francuskie-pelnoziarniste-z-twarogiem",
    slot: "sniadanie",
    title: "Tosty francuskie pełnoziarniste z twarogiem",
    tagline: "Słodko-słone śniadanie",
    ingredients: ["2 kromki chleba pełnoziarnistego","1 jajko","80 g twarogu chudego","50 ml mleka","1 łyżeczka miodu"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Roztrzep jajko z mlekiem.","Obtocz chleb i podsmaż na patelni. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Podawaj z twarogiem i miodem."],
    approximateMacros: { calories: 380, proteinG: 26, fatG: 12, carbsG: 42 },
    imagePromptEn: "whole grain french toast cottage cheese",
    prepMinutes: 15,
  },
  {
    id: "sniadanie-0003-shakshuka-z-ciecierzyca",
    slot: "sniadanie",
    title: "Shakshuka z ciecierzycą",
    tagline: "Bliskowschodnie śniadanie na ciepło",
    ingredients: ["2 jajka","150 g pomidorów krojonych","80 g ciecierzycy z puszki","1/2 cebuli","do smaku (ok. 2–3 g) przyprawy: kumin, papryka, czosnek"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Zeszklij cebulę, dodaj pomidory i przyprawy.","Dodaj ciecierzycę, wbij jajka.","Duś pod przykryciem do ścięcia białka."],
    approximateMacros: { calories: 326, proteinG: 22, fatG: 14, carbsG: 28 },
    imagePromptEn: "shakshuka chickpeas skillet breakfast",
    prepMinutes: 20,
  },
  {
    id: "sniadanie-0004-kanapka-club-z-indykiem-i-jajkiem",
    slot: "sniadanie",
    title: "Kanapka club z indykiem i jajkiem",
    tagline: "Sycące śniadanie do pracy",
    ingredients: ["3 kromki tosta graham","80 g pieczonej piersi indyka","1 jajko na twardo","40 g liście sałaty","1 łyżeczka musztardy"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Opiecz tosty. W piekarniku 180°C przez 12–20 min do zarumienienia.","Ułóż warstwy: indyk, jajko, sałata, musztarda.","Przekrój na pół."],
    approximateMacros: { calories: 362, proteinG: 32, fatG: 10, carbsG: 36 },
    imagePromptEn: "turkey egg club sandwich",
    prepMinutes: 12,
  },
  {
    id: "sniadanie-0005-pancakes-bananowe-z-jogurtem-greckim",
    slot: "sniadanie",
    title: "Pancakes bananowe z jogurtem greckim",
    tagline: "Bez mąki — tylko banan i jajka",
    ingredients: ["1 banan","2 jajka","150 g jogurtu greckiego 0%","szczypta proszku do pieczenia","50 g kilka malin"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Zblenduj banana z jajkami. Miksuj 20–40 s, aż konsystencja będzie gładka; dolej odrobinę płynu, jeśli za gęste.","Smaż małe placki na nieprzywierającej patelni. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Podawaj z jogurtem i malinami."],
    approximateMacros: { calories: 338, proteinG: 24, fatG: 10, carbsG: 38 },
    imagePromptEn: "banana egg pancakes greek yogurt berries",
    prepMinutes: 15,
  },
  {
    id: "sniadanie-0006-kasza-jaglana-na-mleku-z-gruszka",
    slot: "sniadanie",
    title: "Kasza jaglana na mleku z gruszką",
    tagline: "Bezglutenowe śniadanie",
    ingredients: ["50 g kaszy jaglanej","250 ml mleka 1,5%","1 gruszka","10 g orzechów laskowych","szczypta wanilii"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj jagłę na mleku. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Dodaj pokrojoną gruszkę.","Posyp orzechami."],
    approximateMacros: { calories: 384, proteinG: 14, fatG: 12, carbsG: 55 },
    imagePromptEn: "millet porridge pear hazelnuts",
    prepMinutes: 20,
  },
  {
    id: "sniadanie-0007-frittata-ze-szpinakiem-i-feta",
    slot: "sniadanie",
    title: "Frittata ze szpinakiem i fetą",
    tagline: "Pieczony omlet na kilka porcji",
    ingredients: ["3 jajka","80 g szpinaku","40 g fety","1 pomidor","1 łyżeczka oliwy"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Podduś szpinak.","Wymieszaj z jajkami i fetą, przelej do formy.","Piecz 15 min w 180°C."],
    approximateMacros: { calories: 334, proteinG: 26, fatG: 22, carbsG: 8 },
    imagePromptEn: "spinach feta frittata slice",
    prepMinutes: 25,
  },
  {
    id: "sniadanie-0008-bowl-chia-z-mango-i-kokosem",
    slot: "sniadanie",
    title: "Bowl chia z mango i kokosem",
    tagline: "Przygotuj wieczorem",
    ingredients: ["30 g nasion chia","200 ml napoju sojowego","1/2 mango","10 g wiórków kokosowych","1 łyżeczka miodu"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Wymieszaj chia z napojem, odstaw na noc.","Rano dodaj mango i kokos.","Posłodź miodem."],
    approximateMacros: { calories: 318, proteinG: 12, fatG: 14, carbsG: 36 },
    imagePromptEn: "chia pudding mango coconut bowl",
    prepMinutes: 5,
  },
  {
    id: "sniadanie-0009-quesadilla-sniadaniowa-z-jajkiem-i-fasola",
    slot: "sniadanie",
    title: "Quesadilla śniadaniowa z jajkiem i fasolą",
    tagline: "Meksykański start dnia",
    ingredients: ["1 tortilla pełnoziarnista","1 jajko","80 g czarnej fasoli","30 g sera light","40 g salsa lub pomidor"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Usmaż jajko na placku. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Dodaj fasolę i ser, złóż tortillę.","Zrumień z obu stron."],
    approximateMacros: { calories: 382, proteinG: 24, fatG: 14, carbsG: 40 },
    imagePromptEn: "breakfast quesadilla egg black beans",
    prepMinutes: 12,
  },
  {
    id: "sniadanie-0010-smothie-bowl-z-jagodami-i-granola",
    slot: "sniadanie",
    title: "Smothie bowl z jagodami i granolą",
    tagline: "Zimne śniadanie w misce",
    ingredients: ["150 g mrożonych jagód","120 g skyru","1/2 banana","25 g granoli","5 g masła orzechowego"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Zblenduj jagody, skyr i banana. Miksuj 20–40 s, aż konsystencja będzie gładka; dolej odrobinę płynu, jeśli za gęste.","Przelej do miski.","Posyp granolą i masłem orzechowym."],
    approximateMacros: { calories: 346, proteinG: 22, fatG: 10, carbsG: 42 },
    imagePromptEn: "berry smoothie bowl granola",
    prepMinutes: 8,
  },
  {
    id: "sniadanie-0011-jajka-w-koszulkach-na-toscie-z-awokado",
    slot: "sniadanie",
    title: "Jajka w koszulkach na toście z awokado",
    tagline: "Klasyka po nowemu",
    ingredients: ["2 jajka","1 tost graham","1/2 awokado","szczypta chili","10 ml sok z cytryny"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj jajka w koszulkach. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Rozgnieć awokado z cytryną na toście.","Ułóż jajka, posyp chili."],
    approximateMacros: { calories: 340, proteinG: 18, fatG: 20, carbsG: 22 },
    imagePromptEn: "poached eggs avocado toast",
    prepMinutes: 15,
  },
  {
    id: "sniadanie-0012-ryz-jasminowy-na-mleku-kokosowym-z-kardamonem",
    slot: "sniadanie",
    title: "Ryż jaśminowy na mleku kokosowym z kardamonem",
    tagline: "Azjatyckie śniadanie",
    ingredients: ["50 g ryżu jaśminowego","150 ml mleka kokosowego light","100 ml wody","szczypta kardamonu","15 g kilka orzechów nerkowca"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj ryż na mieszance mleka i wody. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Dopraw kardamonem.","Posyp nerkowcami."],
    approximateMacros: { calories: 368, proteinG: 8, fatG: 16, carbsG: 48 },
    imagePromptEn: "jasmine rice coconut milk cardamom breakfast",
    prepMinutes: 25,
  },
  {
    id: "sniadanie-0013-wrap-sniadaniowy-z-lososiem-wedzonym",
    slot: "sniadanie",
    title: "Wrap śniadaniowy z łososiem wędzonym",
    tagline: "Omega-3 na start",
    ingredients: ["1 tortilla","60 g łososia wędzonego","80 g serka wiejskiego light","100 g ogórek","5 g koperek"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Posmaruj tortillę serkiem.","Ułóż łososia, ogórek i koper.","Zwiń ciasno."],
    approximateMacros: { calories: 332, proteinG: 26, fatG: 12, carbsG: 30 },
    imagePromptEn: "smoked salmon breakfast wrap",
    prepMinutes: 8,
  },
  {
    id: "sniadanie-0014-polenta-z-jajkiem-i-pieczarkami",
    slot: "sniadanie",
    title: "Polenta z jajkiem i pieczarkami",
    tagline: "Włoski poranek",
    ingredients: ["50 g polenty","1 jajko","100 g pieczarek","10 g parmezanu","szczypta tymianku"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj polentę. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Usmaż pieczarki z tymiankiem. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Podawaj z jajkiem sadzonym i parmezanem."],
    approximateMacros: { calories: 334, proteinG: 16, fatG: 14, carbsG: 36 },
    imagePromptEn: "polenta fried egg mushrooms",
    prepMinutes: 20,
  },
  {
    id: "sniadanie-0015-budyn-jaglany-z-kakao-i-bananem",
    slot: "sniadanie",
    title: "Budyń jaglany z kakao i bananem",
    tagline: "Na słodko bez cukru",
    ingredients: ["45 g kaszy jaglanej","250 ml mleka","1 łyżeczka kakao","1 banan","5 g gorzkiej czekolady"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj jagłę na mleku z kakao. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Zblenduj z połową banana. Miksuj 20–40 s, aż konsystencja będzie gładka; dolej odrobinę płynu, jeśli za gęste.","Udekoruj bananem i czekoladą."],
    approximateMacros: { calories: 352, proteinG: 12, fatG: 8, carbsG: 58 },
    imagePromptEn: "millet cocoa banana pudding breakfast",
    prepMinutes: 20,
  },
  {
    id: "sniadanie-0016-omlet-japonski-tamagoyaki-z-ryzem",
    slot: "sniadanie",
    title: "Omlet japoński tamagoyaki z ryżem",
    tagline: "Słodkawy omlet rolka",
    ingredients: ["3 jajka","1 łyżeczka sosu sojowego","1 łyżeczka mirinu lub miodu","80 g ugotowanego ryżu","porcja do odważenia: nori (opcjonalnie)"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Roztrzep jajka z soją i mirinem.","Smaż warstwami i zwijaj. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Podawaj z ryżem."],
    approximateMacros: { calories: 342, proteinG: 20, fatG: 14, carbsG: 34 },
    imagePromptEn: "tamagoyaki japanese omelette rice",
    prepMinutes: 18,
  },
  {
    id: "sniadanie-0017-placki-z-cukinii-z-sosem-jogurtowym",
    slot: "sniadanie",
    title: "Placki z cukinii z sosem jogurtowym",
    tagline: "Warzywne śniadanie",
    ingredients: ["1 mała cukinia","1 jajko","30 g mąki owsianej","100 g jogurtu naturalnego","1 ząbek czosnek i koper"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Zetrzyj cukinię, odsącz.","Wymieszaj z jajkiem i mąką, smaż placki. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Podawaj z jogurtem czosnkowym."],
    approximateMacros: { calories: 266, proteinG: 16, fatG: 10, carbsG: 28 },
    imagePromptEn: "zucchini fritters yogurt dip breakfast",
    prepMinutes: 20,
  },
  {
    id: "sniadanie-0018-kasza-manna-z-kakao-i-twarogiem",
    slot: "sniadanie",
    title: "Kasza manna z kakao i twarogiem",
    tagline: "Dzieciństwo w wersji fitness",
    ingredients: ["40 g kaszy manny","250 ml mleka 1,5%","100 g twarogu","1 łyżeczka kakao","1 łyżeczka miodu"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj manną na mleku z kakao. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Przełóż do miski z twarogiem.","Posłodź miodem."],
    approximateMacros: { calories: 344, proteinG: 24, fatG: 8, carbsG: 44 },
    imagePromptEn: "semolina cocoa cottage cheese bowl",
    prepMinutes: 12,
  },
  {
    id: "sniadanie-0019-bagel-z-humusem-jajkiem-i-pieczywem",
    slot: "sniadanie",
    title: "Bagel z humusem, jajkiem i pieczywem",
    tagline: "Śródziemnomorski talerz",
    ingredients: ["2 jajka na twardo","50 g humusu","2 kromki chleba żytniego","100 g ogórek i pomidor","1 łyżeczka (5 ml) oliwa + za'atar"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj jajka. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Ułóż humus, warzywa i jajka.","Skrop oliwą, posyp za'atar, podawaj z chlebem."],
    approximateMacros: { calories: 410, proteinG: 22, fatG: 18, carbsG: 40 },
    imagePromptEn: "hummus eggs mediterranean breakfast plate",
    prepMinutes: 15,
  },
  {
    id: "sniadanie-0020-gofry-owsiane-z-serkiem-wiejskim",
    slot: "sniadanie",
    title: "Gofry owsiane z serkiem wiejskim",
    tagline: "Na gofrownicy lub patelni",
    ingredients: ["50 g płatków owsianych","1 jajko","80 ml mleka","150 g serka wiejskiego light","porcja do odważenia: owoce sezonowe"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Zblenduj płatki z jajkiem i mlekiem. Miksuj 20–40 s, aż konsystencja będzie gładka; dolej odrobinę płynu, jeśli za gęste.","Piecz gofry. W piekarniku 180°C przez 12–20 min do zarumienienia.","Podawaj z serkiem i owocami."],
    approximateMacros: { calories: 362, proteinG: 28, fatG: 10, carbsG: 40 },
    imagePromptEn: "oat waffles cottage cheese fruit",
    prepMinutes: 20,
  },
  {
    id: "drugie_sniadanie-0021-kanapka-zytnia-z-pasta-z-tunczyka-i-ogorkiem",
    slot: "drugie_sniadanie",
    title: "Kanapka żytnia z pastą z tuńczyka i ogórkiem",
    tagline: "Wysokobiałkowa przekąska",
    ingredients: ["2 kromki chleba żytniego","80 g tuńczyka w wodzie","1 łyżeczka jogurtu","100 g ogórek","porcja do odważenia: szczypiorek"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Odcedź tuńczyka, wymieszaj z jogurtem.","Posmaruj pieczywo. W piekarniku 180°C przez 12–20 min do zarumienienia.","Dodaj ogórek i szczypiorek."],
    approximateMacros: { calories: 268, proteinG: 28, fatG: 4, carbsG: 30 },
    imagePromptEn: "rye tuna cucumber sandwich",
    prepMinutes: 8,
  },
  {
    id: "drugie_sniadanie-0022-wrap-z-kurczakiem-teriyaki-i-kapusta",
    slot: "drugie_sniadanie",
    title: "Wrap z kurczakiem teriyaki i kapustą",
    tagline: "Azjatycki lunchbox",
    ingredients: ["1 tortilla","100 g kurczaka","1 łyżeczka sosu teriyaki","porcja do odważenia: kapusta pekińska","80 g marchewka starta"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Usmaż kurczaka, polej teriyaki. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Ułóż z warzywami na tortilli.","Zwiń wrap."],
    approximateMacros: { calories: 328, proteinG: 30, fatG: 8, carbsG: 34 },
    imagePromptEn: "chicken teriyaki wrap cabbage",
    prepMinutes: 15,
  },
  {
    id: "drugie_sniadanie-0023-skyr-z-granola-i-malinami",
    slot: "drugie_sniadanie",
    title: "Skyr z granolą i malinami",
    tagline: "Szybkie białko",
    ingredients: ["200 g skyru naturalnego","30 g granoli","80 g malin"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Przełóż skyr do miski.","Posyp granolą i malinami.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 278, proteinG: 24, fatG: 6, carbsG: 32 },
    imagePromptEn: "skyr granola raspberries bowl",
    prepMinutes: 3,
  },
  {
    id: "drugie_sniadanie-0024-salatka-grecka-mini-z-feta-light",
    slot: "drugie_sniadanie",
    title: "Sałatka grecka mini z fetą light",
    tagline: "Warzywa w drodze",
    ingredients: ["100 g ogórka","100 g pomidora","40 g fety light","porcja do odważenia: oliwki","1 łyżeczka oliwy","porcja do odważenia: oregano"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Pokrój warzywa.","Dodaj fetę i oliwki.","Skrop oliwą, posyp oregano."],
    approximateMacros: { calories: 222, proteinG: 12, fatG: 14, carbsG: 12 },
    imagePromptEn: "mini greek salad feta light",
    prepMinutes: 8,
  },
  {
    id: "drugie_sniadanie-0025-shake-czekoladowy-z-maslem-orzechowym",
    slot: "drugie_sniadanie",
    title: "Shake czekoladowy z masłem orzechowym",
    tagline: "Po treningu rano",
    ingredients: ["30 g białka czekoladowego","250 ml mleka 1,5%","10 g masła orzechowego","1/2 banana"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Zblenduj wszystkie składniki. Miksuj 20–40 s, aż konsystencja będzie gładka; dolej odrobinę płynu, jeśli za gęste.","Wypij schłodzony.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 348, proteinG: 32, fatG: 12, carbsG: 28 },
    imagePromptEn: "chocolate peanut butter protein shake",
    prepMinutes: 4,
  },
  {
    id: "drugie_sniadanie-0026-tost-z-awokado-pomidorem-i-mozarella-light",
    slot: "drugie_sniadanie",
    title: "Tost z awokado, pomidorem i mozarellą light",
    tagline: "Włoska nuta",
    ingredients: ["1 duży tost","1/3 awokado","1 pomidor","40 g mozzarelli light","porcja do odważenia: bazylia"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Opiecz tost. W piekarniku 180°C przez 12–20 min do zarumienienia.","Rozgnieć awokado, dodaj pomidor i ser.","Posyp bazylią."],
    approximateMacros: { calories: 302, proteinG: 16, fatG: 14, carbsG: 28 },
    imagePromptEn: "avocado tomato mozzarella toast",
    prepMinutes: 7,
  },
  {
    id: "drugie_sniadanie-0027-rollsy-z-szynka-drobiowa-i-warzywami",
    slot: "drugie_sniadanie",
    title: "Rollsy z szynką drobiową i warzywami",
    tagline: "Bez pieczywa",
    ingredients: ["4 plastry szynki drobiowej","40 g serka śmietankowego light","120 g papryka","100 g ogórek","40 g rukola"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Posmaruj szynkę serkiem.","Ułóż warzywa i zwiń rolady.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 192, proteinG: 22, fatG: 8, carbsG: 8 },
    imagePromptEn: "turkey ham veggie rolls",
    prepMinutes: 8,
  },
  {
    id: "drugie_sniadanie-0028-hummus-z-marchewka-i-pieczywem-chrupkim",
    slot: "drugie_sniadanie",
    title: "Hummus z marchewką i pieczywem chrupkim",
    tagline: "Roślinna przekąska",
    ingredients: ["80 g humusu","2 marchewki","2 pieczywa chrupkie","120 g papryka"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Pokrój warzywa w słupki.","Podawaj z humusem i pieczywem. W piekarniku 180°C przez 12–20 min do zarumienienia.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 292, proteinG: 10, fatG: 12, carbsG: 36 },
    imagePromptEn: "hummus carrot crispbread snack",
    prepMinutes: 5,
  },
  {
    id: "drugie_sniadanie-0029-omlet-w-kubku-z-mikrofalowki",
    slot: "drugie_sniadanie",
    title: "Omlet w kubku z mikrofalówki",
    tagline: "Biurowe 3 minuty",
    ingredients: ["2 jajka","30 ml mleka","80 g szpinak","20 g sera","szczypta (~1 g) sól, pieprz"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Roztrzep jajka z mlekiem w kubku.","Dodaj szpinak i ser.","Mikrofaluj 60–90 s, mieszając w połowie."],
    approximateMacros: { calories: 214, proteinG: 18, fatG: 14, carbsG: 4 },
    imagePromptEn: "microwave mug omelette spinach",
    prepMinutes: 5,
  },
  {
    id: "drugie_sniadanie-0030-jogurt-grecki-z-miodem-i-orzechami-wloskimi",
    slot: "drugie_sniadanie",
    title: "Jogurt grecki z miodem i orzechami włoskimi",
    tagline: "Prosta klasyka",
    ingredients: ["200 g jogurtu greckiego 0%","1 łyżeczka miodu","15 g orzechów włoskich"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Jogurt przełóż do miski.","Polej miodem, posyp orzechami.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 242, proteinG: 20, fatG: 10, carbsG: 18 },
    imagePromptEn: "greek yogurt honey walnuts",
    prepMinutes: 2,
  },
  {
    id: "drugie_sniadanie-0031-kanapka-z-pasta-jajeczna-i-rukola",
    slot: "drugie_sniadanie",
    title: "Kanapka z pastą jajeczną i rukolą",
    tagline: "Klasyka lunchboxa",
    ingredients: ["2 kromki chleba","2 jajka","1 łyżeczka majonezu light","40 g rukola","porcja do odważenia: szczypiorek"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj jajka, zrób pastę. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Posmaruj pieczywo, dodaj rukolę. W piekarniku 180°C przez 12–20 min do zarumienienia.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 292, proteinG: 18, fatG: 12, carbsG: 28 },
    imagePromptEn: "egg salad sandwich rocket",
    prepMinutes: 12,
  },
  {
    id: "drugie_sniadanie-0032-edamame-z-sola-morska-i-chili",
    slot: "drugie_sniadanie",
    title: "Edamame z solą morską i chili",
    tagline: "Azjatycka przekąska",
    ingredients: ["150 g edamame w strąkach","szczypta (~1 g) sól morska","szczypta chili","porcja do odważenia: sok z limonki"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj lub podgrzej edamame. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Posól, dodaj chili i limonkę.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 200, proteinG: 18, fatG: 8, carbsG: 14 },
    imagePromptEn: "edamame sea salt chili snack",
    prepMinutes: 8,
  },
  {
    id: "drugie_sniadanie-0033-twarozek-z-rzodkiewka-i-szczypiorkiem-na-pieczywie",
    slot: "drugie_sniadanie",
    title: "Twarożek z rzodkiewką i szczypiorkiem na pieczywie",
    tagline: "Polski klasyk",
    ingredients: ["150 g twarogu","porcja do odważenia: rzodkiewka","porcja do odważenia: szczypiorek","2 kromki chleba","szczypta soli"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Rozduś twaróg z warzywami.","Posmaruj pieczywo. W piekarniku 180°C przez 12–20 min do zarumienienia.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 270, proteinG: 24, fatG: 6, carbsG: 30 },
    imagePromptEn: "cottage cheese radish chives bread",
    prepMinutes: 7,
  },
  {
    id: "drugie_sniadanie-0034-sushi-bowl-mini-z-tunczykiem-i-ryzem",
    slot: "drugie_sniadanie",
    title: "Sushi bowl mini z tuńczykiem i ryżem",
    tagline: "Bez rolowania",
    ingredients: ["80 g ryżu sushi ugotowanego","70 g tuńczyka","100 g ogórek","awokado 1/4","porcja do odważenia: sos sojowy light"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Ułóż ryż w misce.","Dodaj tuńczyka i warzywa.","Polej soją."],
    approximateMacros: { calories: 312, proteinG: 24, fatG: 8, carbsG: 36 },
    imagePromptEn: "mini tuna sushi bowl",
    prepMinutes: 10,
  },
  {
    id: "drugie_sniadanie-0035-nalesnik-owsiany-z-twarogiem-i-truskawkami",
    slot: "drugie_sniadanie",
    title: "Naleśnik owsiany z twarogiem i truskawkami",
    tagline: "Jeden duży naleśnik",
    ingredients: ["40 g płatków owsianych","1 jajko","100 g twarogu","80 g truskawek","porcja do odważenia: odrobina mleka"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Zblenduj płatki z jajkiem i mlekiem, usmaż naleśnik. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Nałóż twaróg i truskawki, zwiń.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 338, proteinG: 26, fatG: 10, carbsG: 36 },
    imagePromptEn: "oat pancake cottage cheese strawberries",
    prepMinutes: 12,
  },
  {
    id: "obiad-0036-piers-z-kurczaka-sous-vide-styl-z-kasza-gryczana-i-burak",
    slot: "obiad",
    title: "Pierś z kurczaka sous-vide styl z kaszą gryczaną i burakiem",
    tagline: "Polski talerz siłowy",
    ingredients: ["150 g piersi kurczaka","70 g kaszy gryczanej","150 g buraka pieczonego","szczypta majeranku","1 łyżeczka oliwy"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Usmaż lub upiecz kurczaka. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Ugotuj kaszę. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Podawaj z burakiem i majerankiem."],
    approximateMacros: { calories: 468, proteinG: 42, fatG: 12, carbsG: 48 },
    imagePromptEn: "chicken buckwheat roasted beet plate",
    prepMinutes: 30,
  },
  {
    id: "obiad-0037-losos-pieczony-z-batatem-i-brokulem",
    slot: "obiad",
    title: "Łosoś pieczony z batatem i brokułem",
    tagline: "Omega-3 + warzywa",
    ingredients: ["150 g łososia","200 g batata","150 g brokułu","1/2 szt. (sok) cytryna","5 g koperek"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Piecz łososia 15 min w 190°C.","Ugotuj lub upiecz batata. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Blanszuj brokuł, skrop cytryną."],
    approximateMacros: { calories: 458, proteinG: 34, fatG: 18, carbsG: 40 },
    imagePromptEn: "baked salmon sweet potato broccoli",
    prepMinutes: 30,
  },
  {
    id: "obiad-0038-bowl-buddha-z-tofu-quinoa-i-warzywami",
    slot: "obiad",
    title: "Bowl buddha z tofu, quinoa i warzywami",
    tagline: "Wegański obiad",
    ingredients: ["120 g tofu","60 g quinoa","porcja do odważenia: czerwona kapusta","80 g marchewka","sos tahini 1 łyżeczka"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj quinoa. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Usmaż tofu na złoto. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Ułóż bowl, polej tahini."],
    approximateMacros: { calories: 408, proteinG: 24, fatG: 16, carbsG: 42 },
    imagePromptEn: "tofu quinoa buddha bowl tahini",
    prepMinutes: 25,
  },
  {
    id: "obiad-0039-chili-con-carne-z-indykiem-i-ryzem",
    slot: "obiad",
    title: "Chili con carne z indykiem i ryżem",
    tagline: "Lżejsza wersja klasyki",
    ingredients: ["150 g mięsa z indyka","100 g czerwonej fasoli","120 g pomidory krojone","60 g ryżu","do smaku (ok. 2–3 g) przyprawy chili"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Zrumień indyka z przyprawami.","Dodaj pomidory i fasolę, duś 15 min.","Podawaj z ryżem."],
    approximateMacros: { calories: 450, proteinG: 40, fatG: 10, carbsG: 50 },
    imagePromptEn: "turkey chili con carne rice",
    prepMinutes: 35,
  },
  {
    id: "obiad-0040-dorsz-w-panierce-panko-z-puree-z-kalafiora",
    slot: "obiad",
    title: "Dorsz w panierce panko z puree z kalafiora",
    tagline: "Ryba w lekkiej panierce",
    ingredients: ["160 g dorsza","30 g panko","1 jajko","300 g kalafiora","szczypta gałki"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Obtocz rybę w jajku i panko, upiecz. W piekarniku 180°C przez 12–20 min do zarumienienia.","Ugotuj kalafior, zblenduj na puree. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Dopraw gałką."],
    approximateMacros: { calories: 346, proteinG: 36, fatG: 10, carbsG: 28 },
    imagePromptEn: "panko cod cauliflower mash",
    prepMinutes: 30,
  },
  {
    id: "obiad-0041-pad-thai-z-krewetkami-wersja-light",
    slot: "obiad",
    title: "Pad thai z krewetkami (wersja light)",
    tagline: "Azjatycki wok",
    ingredients: ["120 g krewetek","80 g makaronu ryżowego","porcja do odważenia: kiełki","1 jajko","porcja do odważenia: sos rybny + limonka (odrobina)"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj makaron. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Smaż krewetki i jajko. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Wymieszaj z makaronem i kiełkami."],
    approximateMacros: { calories: 410, proteinG: 32, fatG: 10, carbsG: 48 },
    imagePromptEn: "light prawn pad thai",
    prepMinutes: 25,
  },
  {
    id: "obiad-0042-gulasz-wolowy-z-papryka-i-kasza-jeczmienna",
    slot: "obiad",
    title: "Gulasz wołowy z papryką i kaszą jęczmienną",
    tagline: "Sycący obiad",
    ingredients: ["140 g chudej wołowiny","120 g papryka","80 g cebula","60 g kaszy jęczmiennej","120 g papryka słodka"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Zrumień mięso.","Duś z warzywami i przyprawami.","Podawaj z kaszą."],
    approximateMacros: { calories: 454, proteinG: 38, fatG: 14, carbsG: 44 },
    imagePromptEn: "beef paprika stew barley",
    prepMinutes: 50,
  },
  {
    id: "obiad-0043-kurczak-tikka-z-ryzem-basmati-i-raita",
    slot: "obiad",
    title: "Kurczak tikka z ryżem basmati i raita",
    tagline: "Indyjskie aromaty",
    ingredients: ["150 g kurczaka","porcja do odważenia: jogurt + przyprawy tikka","60 g ryżu basmati","100 g ogórek + jogurt na raita"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Marynuj kurczaka w jogurcie i przyprawach, upiecz. W piekarniku 180°C przez 12–20 min do zarumienienia.","Ugotuj ryż. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Zrób raita z ogórka."],
    approximateMacros: { calories: 442, proteinG: 40, fatG: 10, carbsG: 48 },
    imagePromptEn: "chicken tikka basmati raita",
    prepMinutes: 40,
  },
  {
    id: "obiad-0044-makaron-pelnoziarnisty-z-tunczykiem-i-cukinia",
    slot: "obiad",
    title: "Makaron pełnoziarnisty z tuńczykiem i cukinią",
    tagline: "Szybki obiad z puszki",
    ingredients: ["70 g makaronu pełnoziarnistego","80 g tuńczyka","1 cukinia","1 ząbek czosnek","100 g pomidorki koktajlowe"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj makaron. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Smaż cukinię z czosnkiem. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Wymieszaj z tuńczykiem i makaronem."],
    approximateMacros: { calories: 416, proteinG: 34, fatG: 8, carbsG: 52 },
    imagePromptEn: "wholewheat pasta tuna zucchini",
    prepMinutes: 20,
  },
  {
    id: "obiad-0045-kaczka-confit-styl-light-z-puree-z-selera",
    slot: "obiad",
    title: "Kaczka confit styl light z puree z selera",
    tagline: "Odświętny obiad",
    ingredients: ["150 g udźca kaczki bez skóry","300 g selera","1 szt. (~150 g) jabłko","porcja do odważenia: tymianek"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Upiecz kaczkę z tymiankiem. W piekarniku 180°C przez 12–20 min do zarumienienia.","Ugotuj seler z jabłkiem, zrób puree. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Podawaj razem."],
    approximateMacros: { calories: 384, proteinG: 32, fatG: 16, carbsG: 28 },
    imagePromptEn: "duck breast celery apple puree",
    prepMinutes: 45,
  },
  {
    id: "obiad-0046-falafel-pieczony-z-salatka-tabbouleh",
    slot: "obiad",
    title: "Falafel pieczony z sałatką tabbouleh",
    tagline: "Bliski Wschód bez smażenia",
    ingredients: ["4–5 falafel z ciecierzycy (pieczone)","bulgur 40 g","5 g pietruszka","120 g pomidor","10 ml sok z cytryny"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Upiecz falafel. W piekarniku 180°C przez 12–20 min do zarumienienia.","Ugotuj bulgur, wymieszaj tabbouleh. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Podawaj razem."],
    approximateMacros: { calories: 372, proteinG: 18, fatG: 12, carbsG: 48 },
    imagePromptEn: "baked falafel tabbouleh plate",
    prepMinutes: 35,
  },
  {
    id: "obiad-0047-risotto-z-krewetkami-i-szparagami",
    slot: "obiad",
    title: "Risotto z krewetkami i szparagami",
    tagline: "Kremowe bez śmietany",
    ingredients: ["70 g ryżu arborio","100 g krewetek","porcja do odważenia: szparagi","porcja do odważenia: bulion warzywny","parmezan 10 g"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Smaż ryż, dolewaj bulion. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Dodaj szparagi i krewetki pod koniec.","Dopraw parmezanem."],
    approximateMacros: { calories: 400, proteinG: 28, fatG: 8, carbsG: 54 },
    imagePromptEn: "prawn asparagus risotto",
    prepMinutes: 35,
  },
  {
    id: "obiad-0048-schab-pieczony-z-ziemniakami-i-surowka-z-kapusty",
    slot: "obiad",
    title: "Schab pieczony z ziemniakami i surówką z kapusty",
    tagline: "Domowy obiad",
    ingredients: ["140 g schabu","200 g ziemniaków","porcja do odważenia: kapusta + marchewka","musztarda"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Natrij schab musztardą, upiecz. W piekarniku 180°C przez 12–20 min do zarumienienia.","Upiecz ziemniaki. W piekarniku 180°C przez 12–20 min do zarumienienia.","Zrób surówkę."],
    approximateMacros: { calories: 420, proteinG: 36, fatG: 12, carbsG: 42 },
    imagePromptEn: "roast pork potatoes cabbage salad",
    prepMinutes: 45,
  },
  {
    id: "obiad-0049-moussaka-light-z-baklazanem-i-indykiem",
    slot: "obiad",
    title: "Moussaka light z bakłażanem i indykiem",
    tagline: "Grecka zapiekanka",
    ingredients: ["1 bakłażan","120 g indyka mielonego","porcja do odważenia: sos pomidorowy","porcja do odważenia: beszamel light z mleka i mąki"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Podpiecz bakłażana. W piekarniku 180°C przez 12–20 min do zarumienienia.","Usmaż indyka z sosem. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Ułóż warstwy, zalej beszamelem, piecz. W piekarniku 180°C przez 12–20 min do zarumienienia."],
    approximateMacros: { calories: 374, proteinG: 32, fatG: 14, carbsG: 30 },
    imagePromptEn: "light turkey moussaka eggplant",
    prepMinutes: 50,
  },
  {
    id: "obiad-0050-krewetki-w-sosie-czosnkowym-z-kasza-jaglana",
    slot: "obiad",
    title: "Krewetki w sosie czosnkowym z kaszą jaglaną",
    tagline: "Szybki wok",
    ingredients: ["140 g krewetek","60 g kaszy jaglanej","1 ząbek czosnek","5 g natka pietruszki","oliwa 1 łyżeczka"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj jagłę. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Smaż krewetki z czosnkiem. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Podawaj z pietruszką."],
    approximateMacros: { calories: 352, proteinG: 30, fatG: 8, carbsG: 40 },
    imagePromptEn: "garlic prawns millet",
    prepMinutes: 20,
  },
  {
    id: "obiad-0051-burger-z-indyka-z-pieczywem-pelnoziarnistym-i-salatka",
    slot: "obiad",
    title: "Burger z indyka z pieczywem pełnoziarnistym i sałatką",
    tagline: "Comfort food fitness",
    ingredients: ["140 g mielonego indyka","porcja do odważenia: bułka pełnoziarnista","60 g sałata, pomidor","porcja do odważenia: sos jogurtowy"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Uformuj i usmaż kotleta. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Złóż burgera.","Dodaj sałatkę z boku."],
    approximateMacros: { calories: 420, proteinG: 38, fatG: 12, carbsG: 40 },
    imagePromptEn: "turkey burger wholegrain bun salad",
    prepMinutes: 25,
  },
  {
    id: "obiad-0052-paella-warzywna-z-kurczakiem",
    slot: "obiad",
    title: "Paella warzywna z kurczakiem",
    tagline: "Hiszpański ryż",
    ingredients: ["60 g ryżu","100 g kurczaka","120 g papryka, groszek","porcja do odważenia: szafran lub kurkuma","porcja do odważenia: bulion"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Zrumień kurczaka.","Dodaj ryż, warzywa i bulion.","Duś bez mieszania do wchłonięcia."],
    approximateMacros: { calories: 400, proteinG: 32, fatG: 8, carbsG: 50 },
    imagePromptEn: "chicken vegetable paella",
    prepMinutes: 40,
  },
  {
    id: "obiad-0053-zupa-tom-yum-z-kurczakiem-i-makaronem-ryzowym",
    slot: "obiad",
    title: "Zupa tom yum z kurczakiem i makaronem ryżowym",
    tagline: "Pikantna zupa-danie",
    ingredients: ["120 g kurczaka","porcja do odważenia: pasta tom yum","80 g makaronu ryżowego","porcja do odważenia: pieczarki","porcja do odważenia: limonka"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj bulion z pastą. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Dodaj kurczaka i pieczarki. W piekarniku 180°C przez 12–20 min do zarumienienia.","Na końcu makaron i limonkę."],
    approximateMacros: { calories: 352, proteinG: 30, fatG: 8, carbsG: 40 },
    imagePromptEn: "tom yum chicken rice noodles",
    prepMinutes: 25,
  },
  {
    id: "obiad-0054-pieczona-piers-z-kaczki-z-kasza-i-zurawina",
    slot: "obiad",
    title: "Pieczona pierś z kaczki z kaszą i żurawiną",
    tagline: "Wykwintny obiad",
    ingredients: ["140 g piersi kaczki bez skóry","60 g kaszy gryczanej","porcja do odważenia: żurawina","porcja do odważenia: rozmaryn"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Usmaż/upiecz pierś. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Ugotuj kaszę. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Podawaj z żurawiną."],
    approximateMacros: { calories: 422, proteinG: 34, fatG: 14, carbsG: 40 },
    imagePromptEn: "duck breast buckwheat cranberry",
    prepMinutes: 35,
  },
  {
    id: "obiad-0055-spaghetti-bolonskie-z-soczewica",
    slot: "obiad",
    title: "Spaghetti bolońskie z soczewicą",
    tagline: "Roślinna bolończyzna",
    ingredients: ["70 g spaghetti pełnoziarnistego","80 g czerwonej soczewicy","porcja do odważenia: sos pomidorowy","80 g marchew, seler","porcja do odważenia: oregano"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj soczewicę z warzywami w sosie. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Ugotuj makaron. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Połącz."],
    approximateMacros: { calories: 382, proteinG: 24, fatG: 6, carbsG: 58 },
    imagePromptEn: "lentil bolognese wholewheat spaghetti",
    prepMinutes: 30,
  },
  {
    id: "podwieczorek-0056-jogurt-naturalny-z-kakao-i-bananem",
    slot: "podwieczorek",
    title: "Jogurt naturalny z kakao i bananem",
    tagline: "Słodka mini porcja",
    ingredients: ["150 g jogurtu naturalnego","1 łyżeczka kakao","1/2 banana"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Wymieszaj jogurt z kakao.","Dodaj banana.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 180, proteinG: 12, fatG: 4, carbsG: 24 },
    imagePromptEn: "yogurt cocoa banana snack",
    prepMinutes: 3,
  },
  {
    id: "podwieczorek-0057-garsc-migdalow-i-jablko",
    slot: "podwieczorek",
    title: "Garść migdałów i jabłko",
    tagline: "Proste combo",
    ingredients: ["20 g migdałów","1 jabłko"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Umyj jabłko.","Jedz z migdałami.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 216, proteinG: 5, fatG: 12, carbsG: 22 },
    imagePromptEn: "almonds apple snack",
    prepMinutes: 1,
  },
  {
    id: "podwieczorek-0058-koktajl-truskawkowy-na-kefirze",
    slot: "podwieczorek",
    title: "Koktajl truskawkowy na kefirze",
    tagline: "Orzeźwienie",
    ingredients: ["200 ml kefiru","100 g truskawek","5 g miodu"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Zblenduj składniki. Miksuj 20–40 s, aż konsystencja będzie gładka; dolej odrobinę płynu, jeśli za gęste.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 138, proteinG: 10, fatG: 2, carbsG: 20 },
    imagePromptEn: "strawberry kefir smoothie",
    prepMinutes: 4,
  },
  {
    id: "podwieczorek-0059-ryzowki-z-twarogiem-i-miodem",
    slot: "podwieczorek",
    title: "Ryżówki z twarogiem i miodem",
    tagline: "Chrupiąco",
    ingredients: ["3 wafle ryżowe","80 g twarogu","1 łyżeczka miodu"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Posmaruj wafle twarogiem.","Polej miodem.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 186, proteinG: 14, fatG: 2, carbsG: 28 },
    imagePromptEn: "rice cakes cottage cheese honey",
    prepMinutes: 3,
  },
  {
    id: "podwieczorek-0060-marchewki-baby-z-hummusem",
    slot: "podwieczorek",
    title: "Marchewki baby z hummusem",
    tagline: "Warzywny dip",
    ingredients: ["150 g marchewek baby","40 g humusu"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Podawaj marchewki z hummusem.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 158, proteinG: 6, fatG: 6, carbsG: 20 },
    imagePromptEn: "baby carrots hummus snack",
    prepMinutes: 2,
  },
  {
    id: "podwieczorek-0061-serek-wiejski-z-ananasem",
    slot: "podwieczorek",
    title: "Serek wiejski z ananasem",
    tagline: "Szybkie białko",
    ingredients: ["150 g serka wiejskiego","80 g ananasa"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Wymieszaj serek z ananasem.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 164, proteinG: 18, fatG: 4, carbsG: 14 },
    imagePromptEn: "cottage cheese pineapple snack",
    prepMinutes: 2,
  },
  {
    id: "podwieczorek-0062-herbata-matcha-latte-z-mlekiem-i-bialkiem",
    slot: "podwieczorek",
    title: "Herbata matcha latte z mlekiem i białkiem",
    tagline: "Napój zamiast przekąski",
    ingredients: ["1 łyżeczka matchy","200 ml mleka","15 g białka waniliowego"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Rozprowadź matchę.","Dodaj ciepłe mleko i białko, spień.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 148, proteinG: 16, fatG: 4, carbsG: 12 },
    imagePromptEn: "matcha protein latte",
    prepMinutes: 5,
  },
  {
    id: "podwieczorek-0063-pieczone-chipsy-z-ciecierzycy",
    slot: "podwieczorek",
    title: "Pieczone chipsy z ciecierzycy",
    tagline: "Chrupiące",
    ingredients: ["100 g ciecierzycy z puszki","do smaku (ok. 2–3 g) przyprawy","1 łyżeczka oliwy"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Osusz ciecierzycę, wymieszaj z oliwą i przyprawami.","Piecz 25 min w 200°C.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 182, proteinG: 10, fatG: 6, carbsG: 22 },
    imagePromptEn: "roasted chickpea chips",
    prepMinutes: 30,
  },
  {
    id: "podwieczorek-0064-kanapka-mini-z-pasta-z-avocado-i-jajkiem",
    slot: "podwieczorek",
    title: "Kanapka mini z pastą z avocado i jajkiem",
    tagline: "Pół porcji",
    ingredients: ["1 kromka chleba","1/4 awokado","1 jajko na twardo"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Rozgnieć awokado na chlebie.","Dodaj pokrojone jajko.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 220, proteinG: 12, fatG: 12, carbsG: 16 },
    imagePromptEn: "mini avocado egg open sandwich",
    prepMinutes: 8,
  },
  {
    id: "podwieczorek-0065-galaretka-proteinowa-z-owocami",
    slot: "podwieczorek",
    title: "Galaretka proteinowa z owocami",
    tagline: "Na zimno",
    ingredients: ["porcja do odważenia: galaretka bez cukru","15 g żelatyny lub białka","porcja do odważenia: owoce"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Przygotuj galaretkę według przepisu. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Dodaj owoce, schłodź.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 96, proteinG: 12, fatG: 0, carbsG: 12 },
    imagePromptEn: "protein jelly fruit cup",
    prepMinutes: 10,
  },
  {
    id: "podwieczorek-0066-tortilla-chips-pieczone-z-salsa",
    slot: "podwieczorek",
    title: "Tortilla chips pieczone z salsą",
    tagline: "Domowe chipsy",
    ingredients: ["1 tortilla pokrojona w trójkąty","40 g salsa pomidorowa","do smaku (ok. 2–3 g) przyprawy"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Upiecz trójkąty tortilli. W piekarniku 180°C przez 12–20 min do zarumienienia.","Podawaj z salsą.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 172, proteinG: 6, fatG: 4, carbsG: 28 },
    imagePromptEn: "baked tortilla chips salsa",
    prepMinutes: 15,
  },
  {
    id: "podwieczorek-0067-shake-kawowy-proteinowy",
    slot: "podwieczorek",
    title: "Shake kawowy proteinowy",
    tagline: "Popołudniowy boost",
    ingredients: ["30–60 ml espresso lub kawa","25 g białka","200 ml mleka","porcja do odważenia: lód"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Zblenduj kawę, białko i mleko z lodem. Miksuj 20–40 s, aż konsystencja będzie gładka; dolej odrobinę płynu, jeśli za gęste.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 188, proteinG: 26, fatG: 4, carbsG: 12 },
    imagePromptEn: "iced coffee protein shake",
    prepMinutes: 4,
  },
  {
    id: "kolacja-0068-salatka-cobb-light-z-kurczakiem",
    slot: "kolacja",
    title: "Sałatka Cobb light z kurczakiem",
    tagline: "Lekka kolacja",
    ingredients: ["120 g kurczaka","60 g sałata rzymska","1 jajko","120 g pomidor","100 g ogórek","30 g dressing jogurtowy"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Usmaż kurczaka. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Ułóż sałatkę z jajkiem i warzywami.","Polej dressingiem."],
    approximateMacros: { calories: 300, proteinG: 36, fatG: 12, carbsG: 12 },
    imagePromptEn: "light chicken cobb salad",
    prepMinutes: 20,
  },
  {
    id: "kolacja-0069-pieczony-dorsz-z-cukinia-i-pomidorami",
    slot: "kolacja",
    title: "Pieczony dorsz z cukinią i pomidorami",
    tagline: "Jedna blacha",
    ingredients: ["160 g dorsza","150 g cukinia","100 g pomidorki koktajlowe","1 ząbek czosnek","2 g zioła"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Ułóż rybę i warzywa na blaszce.","Piecz 18 min w 190°C.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 230, proteinG: 34, fatG: 6, carbsG: 10 },
    imagePromptEn: "baked cod zucchini tomatoes tray",
    prepMinutes: 25,
  },
  {
    id: "kolacja-0070-omlet-na-kolacje-z-pieczarkami-i-szpinakiem",
    slot: "kolacja",
    title: "Omlet na kolację z pieczarkami i szpinakiem",
    tagline: "Szybko i lekko",
    ingredients: ["3 jajka","porcja do odważenia: pieczarki","80 g szpinak","szczypta sera"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Usmaż pieczarki i szpinak. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Wlej jajka, zetnij omlet.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 256, proteinG: 22, fatG: 16, carbsG: 6 },
    imagePromptEn: "mushroom spinach dinner omelette",
    prepMinutes: 12,
  },
  {
    id: "kolacja-0071-zupa-krem-z-pieczonej-papryki-z-grzanka",
    slot: "kolacja",
    title: "Zupa krem z pieczonej papryki z grzanką",
    tagline: "Rozgrzewająca kolacja",
    ingredients: ["2 czerwone papryki","80 g cebula","porcja do odważenia: bulion","1 kromka pieczywa","odrobina śmietany 12%"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Upiecz papryki, zblenduj z bulionem. W piekarniku 180°C przez 12–20 min do zarumienienia.","Dopraw śmietaną.","Podawaj z grzanką."],
    approximateMacros: { calories: 198, proteinG: 8, fatG: 6, carbsG: 28 },
    imagePromptEn: "roasted pepper soup crouton",
    prepMinutes: 35,
  },
  {
    id: "kolacja-0072-tacos-rybne-z-salsa-mango",
    slot: "kolacja",
    title: "Tacos rybne z salsą mango",
    tagline: "Lekka kolacja meksykańska",
    ingredients: ["120 g białej ryby","2 małe tortille","porcja do odważenia: mango","80 g cebula czerwona","porcja do odważenia: limonka"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Usmaż rybę. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Zrób salsę z mango.","Złóż tacos."],
    approximateMacros: { calories: 328, proteinG: 28, fatG: 8, carbsG: 36 },
    imagePromptEn: "fish tacos mango salsa",
    prepMinutes: 20,
  },
  {
    id: "kolacja-0073-salatka-z-komosy-pieczonego-buraka-i-koziego-sera",
    slot: "kolacja",
    title: "Sałatka z komosy, pieczonego buraka i koziego sera",
    tagline: "Kolorowa miska",
    ingredients: ["50 g quinoa","porcja do odważenia: burak pieczony","40 g sera koziego","40 g rukola","porcja do odważenia: pestki dyni"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj quinoa. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Ułóż z burakiem i serem.","Posyp pestkami."],
    approximateMacros: { calories: 342, proteinG: 18, fatG: 14, carbsG: 36 },
    imagePromptEn: "quinoa beet goat cheese salad",
    prepMinutes: 25,
  },
  {
    id: "kolacja-0074-kurczak-w-sosie-musztardowym-z-puree-z-kalafiora",
    slot: "kolacja",
    title: "Kurczak w sosie musztardowym z puree z kalafiora",
    tagline: "Low-carb kolacja",
    ingredients: ["150 g kurczaka","musztarda + jogurt","200 g kalafior na puree","porcja do odważenia: szczypiorek"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Usmaż kurczaka, polej sosem. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Zrób puree z kalafiora.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 314, proteinG: 40, fatG: 10, carbsG: 16 },
    imagePromptEn: "mustard chicken cauliflower mash",
    prepMinutes: 25,
  },
  {
    id: "kolacja-0075-risotto-grzybowe-light",
    slot: "kolacja",
    title: "Risotto grzybowe light",
    tagline: "Wegańskie opcje: bulion warzywny",
    ingredients: ["60 g ryżu arborio","porcja do odważenia: mieszanka grzybów","80 g cebula","porcja do odważenia: bulion","5 g natka"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Smaż ryż i grzyby. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Dolewaj bulion.","Dopraw natką."],
    approximateMacros: { calories: 284, proteinG: 10, fatG: 4, carbsG: 52 },
    imagePromptEn: "light mushroom risotto",
    prepMinutes: 35,
  },
  {
    id: "kolacja-0076-stek-z-tofu-z-warzywami-stir-fry",
    slot: "kolacja",
    title: "Stek z tofu z warzywami stir-fry",
    tagline: "Azjatycka kolacja roślinna",
    ingredients: ["140 g tofu","150 g brokuł, papryka","porcja do odważenia: sos sojowy light","porcja do odważenia: imbir","ryż 40 g (opcjonalnie)"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Usmaż tofu. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Dodaj warzywa i sos.","Podawaj z ryżem lub bez."],
    approximateMacros: { calories: 316, proteinG: 22, fatG: 12, carbsG: 30 },
    imagePromptEn: "tofu stir fry vegetables",
    prepMinutes: 20,
  },
  {
    id: "kolacja-0077-zapiekanka-z-cukinii-i-mielonego-indyka",
    slot: "kolacja",
    title: "Zapiekanka z cukinii i mielonego indyka",
    tagline: "Bez makaronu",
    ingredients: ["1 cukinia","120 g indyka mielonego","porcja do odważenia: sos pomidorowy","ser light 30 g"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Usmaż indyka z sosem. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Ułóż z cukinią, posyp serem, zapiecz. W piekarniku 180°C przez 12–20 min do zarumienienia.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 300, proteinG: 32, fatG: 12, carbsG: 16 },
    imagePromptEn: "zucchini turkey bake",
    prepMinutes: 35,
  },
  {
    id: "kolacja-0078-salatka-nicoise-light",
    slot: "kolacja",
    title: "Sałatka niçoise light",
    tagline: "Francuska klasyka",
    ingredients: ["tuńczyk 80 g","porcja do odważenia: jajko","80 g fasolka szparagowa","ziemniak 1 mały","porcja do odważenia: oliwki","60 g sałata"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj jajko, ziemniak i fasolkę. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Ułóż z tuńczykiem i oliwkami.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 306, proteinG: 30, fatG: 10, carbsG: 24 },
    imagePromptEn: "light salade nicoise",
    prepMinutes: 25,
  },
  {
    id: "kolacja-0079-krewetki-z-czosnkiem-na-salacie-lodowej",
    slot: "kolacja",
    title: "Krewetki z czosnkiem na sałacie lodowej",
    tagline: "Bardzo lekko",
    ingredients: ["140 g krewetek","1 ząbek czosnek","60 g sałata lodowa","porcja do odważenia: limonka","1 łyżeczka oliwy"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Smaż krewetki z czosnkiem. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Podawaj na sałacie z limonką.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 208, proteinG: 28, fatG: 8, carbsG: 6 },
    imagePromptEn: "garlic shrimp iceberg salad",
    prepMinutes: 12,
  },
  {
    id: "kolacja-0080-tortilla-pizza-z-kurczakiem-i-warzywami",
    slot: "kolacja",
    title: "Tortilla pizza z kurczakiem i warzywami",
    tagline: "Szybka „pizza”",
    ingredients: ["1 tortilla","porcja do odważenia: sos pomidorowy","80 g kurczaka","120 g papryka","30 g ser light"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Posmaruj tortillę sosem.","Dodaj dodatki, piecz 8 min.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 330, proteinG: 28, fatG: 10, carbsG: 32 },
    imagePromptEn: "tortilla pizza chicken vegetables",
    prepMinutes: 15,
  },
  {
    id: "kolacja-0081-krem-z-cukinii-z-grzanka-pelnoziarnista",
    slot: "kolacja",
    title: "Krem z cukinii z grzanką pełnoziarnistą",
    tagline: "Kolacja-zupa",
    ingredients: ["2 cukinie","80 g cebula","porcja do odważenia: bulion","1 kromka chleba","porcja do odważenia: odrobina jogurtu"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj warzywa w bulionie, zblenduj. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Dopraw jogurtem.","Podawaj z grzanką."],
    approximateMacros: { calories: 164, proteinG: 8, fatG: 4, carbsG: 24 },
    imagePromptEn: "zucchini cream soup wholegrain toast",
    prepMinutes: 25,
  },
  {
    id: "kolacja-0082-bowl-z-lososiem-ryzem-i-edamame",
    slot: "kolacja",
    title: "Bowl z łososiem, ryżem i edamame",
    tagline: "Kolacja z bilansem makro",
    ingredients: ["100 g łososia","50 g ryżu","80 g edamame","100 g ogórek","porcja do odważenia: sos sojowy"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Upiecz łososia. W piekarniku 180°C przez 12–20 min do zarumienienia.","Ugotuj ryż i edamame. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Ułóż bowl."],
    approximateMacros: { calories: 414, proteinG: 32, fatG: 14, carbsG: 40 },
    imagePromptEn: "salmon rice edamame bowl",
    prepMinutes: 25,
  },
  {
    id: "kolacja-0083-placki-z-tunczyka-z-sosem-jogurtowym",
    slot: "kolacja",
    title: "Placki z tuńczyka z sosem jogurtowym",
    tagline: "Bez panierki",
    ingredients: ["1 puszka tuńczyka","1 jajko","2 łyżki płatków owsianych","porcja do odważenia: jogurt + koper"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Wymieszaj tuńczyka z jajkiem i płatkami.","Usmaż placki. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Podawaj z sosem."],
    approximateMacros: { calories: 256, proteinG: 30, fatG: 8, carbsG: 16 },
    imagePromptEn: "tuna fritters yogurt dill sauce",
    prepMinutes: 15,
  },
  {
    id: "kolacja-0084-wrap-z-falafellem-i-tahini-light",
    slot: "kolacja",
    title: "Wrap z falafellem i tahini light",
    tagline: "Wegetariańska kolacja",
    ingredients: ["3 falafle pieczone","porcja do odważenia: tortilla pełnoziarnista","60 g sałata","100 g ogórek","porcja do odważenia: sos tahini rozcieńczony jogurtem"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Podgrzej falafle.","Zawiń w tortillę z warzywami i sosem.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 406, proteinG: 22, fatG: 14, carbsG: 48 },
    imagePromptEn: "falafel wrap tahini yogurt",
    prepMinutes: 15,
  },
  {
    id: "kolacja-0085-omlet-z-pieczarkami-i-szczypiorkiem",
    slot: "kolacja",
    title: "Omlet z pieczarkami i szczypiorkiem",
    tagline: "Klasyczna kolacja białkowa",
    ingredients: ["3 jajka","100 g pieczarek","porcja do odważenia: szczypiorek","1 łyżeczka oliwy"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Podsmaż pieczarki. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Zalej jajkami, posyp szczypiorkiem.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 248, proteinG: 22, fatG: 16, carbsG: 4 },
    imagePromptEn: "mushroom chive omelette",
    prepMinutes: 12,
  },
  {
    id: "drugie_sniadanie-0086-tost-z-pasta-z-tunczyka-i-ogorkiem",
    slot: "drugie_sniadanie",
    title: "Tost z pastą z tuńczyka i ogórkiem",
    tagline: "Szybkie drugie śniadanie",
    ingredients: ["2 kromki chleba","1/2 puszki tuńczyka","porcja do odważenia: jogurt naturalny","100 g ogórek"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Wymieszaj tuńczyka z jogurtem.","Posmaruj tosty, dodaj ogórek.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 262, proteinG: 24, fatG: 6, carbsG: 28 },
    imagePromptEn: "tuna yogurt toast cucumber",
    prepMinutes: 8,
  },
  {
    id: "drugie_sniadanie-0087-jogurt-islandzki-z-mango-i-limonka",
    slot: "drugie_sniadanie",
    title: "Jogurt islandzki z mango i limonką",
    tagline: "Świeży, wysokobiałkowy",
    ingredients: ["200 g skyr","80 g mango","porcja do odważenia: sok z limonki","porcja do odważenia: mięta"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Pokrój mango.","Wymieszaj ze skyrem, dopraw limonką i miętą.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 202, proteinG: 24, fatG: 2, carbsG: 22 },
    imagePromptEn: "skyr mango lime mint bowl",
    prepMinutes: 5,
  },
  {
    id: "drugie_sniadanie-0088-mini-wrap-z-szynka-drobiowa-i-rukola",
    slot: "drugie_sniadanie",
    title: "Mini wrap z szynką drobiową i rukolą",
    tagline: "Na wynos",
    ingredients: ["1 mała tortilla","60 g szynki drobiowej","40 g rukola","30 g ser light","120 g pomidor"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Ułóż składniki na tortilli.","Zawiń i przekrój na pół.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 264, proteinG: 22, fatG: 8, carbsG: 26 },
    imagePromptEn: "turkey ham arugula mini wrap",
    prepMinutes: 7,
  },
  {
    id: "drugie_sniadanie-0089-koktajl-truskawkowy-z-kefirem",
    slot: "drugie_sniadanie",
    title: "Koktajl truskawkowy z kefirem",
    tagline: "Probiotyczny napój-posiłek",
    ingredients: ["250 ml kefiru","150 g truskawek","10 g płatków owsianych","porcja do odważenia: odrobina miodu"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Zblenduj wszystko na gładko. Miksuj 20–40 s, aż konsystencja będzie gładka; dolej odrobinę płynu, jeśli za gęste.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 220, proteinG: 14, fatG: 4, carbsG: 32 },
    imagePromptEn: "strawberry kefir smoothie oats",
    prepMinutes: 5,
  },
  {
    id: "drugie_sniadanie-0090-salatka-z-soczewica-i-feta-light",
    slot: "drugie_sniadanie",
    title: "Sałatka z soczewicą i fetą light",
    tagline: "Syty lunchbox",
    ingredients: ["100 g soczewicy ugotowanej","30 g fety light","100 g ogórek","120 g pomidor","oliwa 1 łyżeczka"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Wymieszaj soczewicę z warzywami.","Dodaj fetę i oliwę.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 256, proteinG: 18, fatG: 8, carbsG: 28 },
    imagePromptEn: "lentil feta cucumber tomato salad",
    prepMinutes: 10,
  },
  {
    id: "podwieczorek-0091-ryzowki-z-twarogiem-i-owocami-lesnymi",
    slot: "podwieczorek",
    title: "Ryżówki z twarogiem i owocami leśnymi",
    tagline: "Chrupiący podwieczorek",
    ingredients: ["2 wafle ryżowe","80 g twarogu","porcja do odważenia: garść owoców leśnych","1 łyżeczka (2 g) cynamon"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Posmaruj wafle twarogiem.","Ułóż owoce, posyp cynamonem.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 212, proteinG: 16, fatG: 4, carbsG: 28 },
    imagePromptEn: "rice cakes cottage cheese berries",
    prepMinutes: 5,
  },
  {
    id: "podwieczorek-0092-shake-czekoladowy-z-bananem",
    slot: "podwieczorek",
    title: "Shake czekoladowy z bananem",
    tagline: "Po treningu",
    ingredients: ["30 g białka czekoladowego","1 mały banan","250 ml mleka 1,5%"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Zblenduj składniki na 20 sekund. Miksuj 20–40 s, aż konsystencja będzie gładka; dolej odrobinę płynu, jeśli za gęste.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 285, proteinG: 30, fatG: 5, carbsG: 30 },
    imagePromptEn: "chocolate protein banana shake",
    prepMinutes: 3,
  },
  {
    id: "podwieczorek-0093-hummus-z-marchewka-i-papryka",
    slot: "podwieczorek",
    title: "Hummus z marchewką i papryką",
    tagline: "Warzywny snack",
    ingredients: ["80 g humusu","80 g marchew","120 g papryka"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Pokrój warzywa w słupki.","Podawaj z hummusem.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 210, proteinG: 8, fatG: 10, carbsG: 22 },
    imagePromptEn: "hummus carrot pepper sticks",
    prepMinutes: 5,
  },
  {
    id: "podwieczorek-0094-twarozek-z-rzodkiewka-i-szczypiorkiem",
    slot: "podwieczorek",
    title: "Twarożek z rzodkiewką i szczypiorkiem",
    tagline: "Słony podwieczorek",
    ingredients: ["150 g twarogu chudego","porcja do odważenia: rzodkiewka","porcja do odważenia: szczypiorek","1 kromka chleba"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Wymieszaj twaróg z warzywami.","Jedz z pieczywem. W piekarniku 180°C przez 12–20 min do zarumienienia.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 204, proteinG: 22, fatG: 4, carbsG: 20 },
    imagePromptEn: "cottage cheese radish chives bread",
    prepMinutes: 7,
  },
  {
    id: "podwieczorek-0095-edamame-z-sola-morska-i-sezamem",
    slot: "podwieczorek",
    title: "Edamame z solą morską i sezamem",
    tagline: "Azjatycki snack",
    ingredients: ["150 g edamame w strąkach","szczypta (~1 g) sól morska","porcja do odważenia: sezam"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Obgotuj edamame 4 min.","Posyp solą i sezamem.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 166, proteinG: 16, fatG: 6, carbsG: 12 },
    imagePromptEn: "edamame sea salt sesame",
    prepMinutes: 6,
  },
  {
    id: "podwieczorek-0096-kisiel-proteinowy-z-wisniami",
    slot: "podwieczorek",
    title: "Kisiel proteinowy z wiśniami",
    tagline: "Słodki, ale lekki",
    ingredients: ["15 g żelatyny lub kisielu","20 g białka waniliowego","100 g wiśni","200 ml woda"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Przygotuj kisiel według opakowania. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Wmieszaj białko i wiśnie na ciepło.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 169, proteinG: 22, fatG: 1, carbsG: 18 },
    imagePromptEn: "protein cherry jelly dessert",
    prepMinutes: 10,
  },
  {
    id: "sniadanie-0097-bowl-chia-z-mlekiem-kokosowym-light-i-kiwi",
    slot: "sniadanie",
    title: "Bowl chia z mlekiem kokosowym light i kiwi",
    tagline: "Na zimno z błonnikiem",
    ingredients: ["30 g nasion chia","200 ml mleka kokosowego light","1 kiwi","10 g wiórków kokosowych"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Zamocz chia na noc.","Rano dodaj kiwi i wiórki.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 278, proteinG: 10, fatG: 14, carbsG: 28 },
    imagePromptEn: "chia pudding kiwi coconut",
    prepMinutes: 5,
  },
  {
    id: "sniadanie-0098-jajka-w-koszulkach-na-szpinaku-z-pomidorkami",
    slot: "sniadanie",
    title: "Jajka w koszulkach na szpinaku z pomidorkami",
    tagline: "Lekkie śniadanie warzywne",
    ingredients: ["2 jajka","100 g szpinaku","100 g pomidorki koktajlowe","1 ząbek czosnek"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Zeszklij szpinak z czosnkiem.","Ugotuj jajka w koszulkach. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Podawaj z pomidorkami."],
    approximateMacros: { calories: 204, proteinG: 18, fatG: 12, carbsG: 6 },
    imagePromptEn: "poached eggs spinach cherry tomatoes",
    prepMinutes: 15,
  },
  {
    id: "sniadanie-0099-kasza-manna-na-mleku-z-kakao-i-gruszka",
    slot: "sniadanie",
    title: "Kasza manna na mleku z kakao i gruszką",
    tagline: "Dzieciństwo w wersji fitness",
    ingredients: ["40 g kaszy manny","250 ml mleka","1 łyżeczka kakao","1 gruszka"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Ugotuj mannę na mleku z kakao. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Dodaj pokrojoną gruszkę.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 320, proteinG: 14, fatG: 8, carbsG: 48 },
    imagePromptEn: "semolina cocoa pear porridge",
    prepMinutes: 12,
  },
  {
    id: "obiad-0100-kurczak-teriyaki-z-brokulem-i-ryzem",
    slot: "obiad",
    title: "Kurczak teriyaki z brokułem i ryżem",
    tagline: "Azjatycki klasyk",
    ingredients: ["140 g kurczaka","20 ml sos teriyaki light","150 g brokułu","50 g ryżu"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Usmaż kurczaka, polej teriyaki. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Ugotuj ryż i brokuł na parze. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 416, proteinG: 38, fatG: 8, carbsG: 48 },
    imagePromptEn: "chicken teriyaki broccoli rice",
    prepMinutes: 25,
  },
  {
    id: "obiad-0101-gulasz-z-indyka-z-papryka-i-kasza-gryczana",
    slot: "obiad",
    title: "Gulasz z indyka z papryką i kaszą gryczaną",
    tagline: "Rozgrzewający obiad",
    ingredients: ["150 g indyka","120 g papryka, cebula","do smaku (ok. 2–3 g) przyprawy do gulaszu","60 g kaszy gryczanej"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Najpierw odważ składniki z listy. Duś mięso z warzywami.","Ugotuj grykę osobno. Gotuj we właściwej ilości płynu (zwykle 8–15 min), aż będzie miękki; odcedź, jeśli trzeba.","Na koniec sprawdź konsystencję i smak; dopraw szczyptą soli lub przyprawami z listy."],
    approximateMacros: { calories: 394, proteinG: 36, fatG: 10, carbsG: 40 },
    imagePromptEn: "turkey paprika goulash buckwheat",
    prepMinutes: 45,
  },
  {
    id: "obiad-0102-dorsz-w-panierce-z-platkow-z-puree-z-kalafiora",
    slot: "obiad",
    title: "Dorsz w panierce z płatków z puree z kalafiora",
    tagline: "Low-carb obiad rybny",
    ingredients: ["160 g dorsza","30 g płatki owsiane + jajko do panierki","200 g kalafior na puree","10 ml sok z cytryny"],
    steps: ["Odważ dokładnie składniki wagą kuchenną i przygotuj naczynia (patelnia / garnek / piekarnik).","Obtocz rybę, usmaż. Na średnim ogniu z 1 łyżeczką tłuszczu, 4–8 min, aż nabierze koloru.","Zblenduj ugotowany kalafior. Miksuj 20–40 s, aż konsystencja będzie gładka; dolej odrobinę płynu, jeśli za gęste.","Dopraw cytryną."],
    approximateMacros: { calories: 322, proteinG: 36, fatG: 10, carbsG: 22 },
    imagePromptEn: "oat crusted cod cauliflower mash",
    prepMinutes: 30,
  },
];

export const MEAL_CATALOG_GENERATED_COUNT = 102;
