import { GYMBRAT_GITHUB_SLUG } from "@/lib/gymbrat-source";
import type { ChangelogSourceEntry } from "@/lib/deploy-changelog";

export type ChangelogEntry = ChangelogSourceEntry;

export const CHANGELOG_ENTRIES: ChangelogEntry[] = [
  {
    title: "2026-10 — Android 0.1.11: ikona z Brandingu w APK",
    date: "2026-10-03",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    bullets: [
      "W Profilu jest GymBrat Android 0.1.11 (versionCode 12) — świeży Release z gym-brat.vercel.app/gymbrat.apk.",
      "Karta „Aplikacja Android” (pobieranie APK) w Profilu widać tylko na telefonie Android w widoku RWD — nie na PC ani iPhonie.",
      "Z Profilu usunięto Nawyki / Przypomnienia PWA (godziny, dni tygodnia, skrót e-mail cron) oraz runner powiadomień w aplikacji.",
      "Z Profilu usunięto sekcję Dane osobowe (RODO) — eksport JSON/CSV i usunięcie konta.",
      "Z panelu admina usunięto Narzędzia administracyjne / Czyszczenie historii (purge treningów i posiłków z całej bazy).",
      "Usunięto Dziennik zmian administratora (Bezpieczeństwo) oraz API ustawień AI admina; dla zawodników nie ma czatu AI / uprawnień AI — tylko lokalne podpowiedzi treningowe.",
      "Na produkcji mniej śladu w DevTools: bez source map w przeglądarce, wyciszone console.*, ograniczone React DevTools, krótsze błędy API i bez logowania pełnych Error w UI.",
      "Ikona launchera z panelu Branding (także WebP) jest wbudowywana w APK przy buildzie w GitHub Actions.",
    ],
  },
  {
    title: "Zapowiedź — pakiet treningu V1",
    planned: true,
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    bullets: [
      "Zdjęcia użytkownika (raporty sylwetki, zdjęcie startowe, ekran cardio) są szyfrowane w bazie (AES-256-GCM, APP_ENCRYPTION_KEY) i serwowane przez autoryzowane GET /api/media/* — bez data URL w payloadzie stron (mniej w DevTools / RSC).",
      "Usunięto ekran Nowości (/changelog) oraz wejścia do niego z menu bocznego i Profilu — lista zmian zostaje tylko w kontrakcie GET /api/version (deploy).",
      "Tło aplikacji mieni się (gradient + ambient), duże liczby mają font serif i animację count-up; dolna nawigacja to PULPIT · TRENING · DIETA · ANALIZA · PROFIL (u admina: ADMIN) oraz złoty przycisk Raport na środku belki (bez TEAM i bez Skrzynki).",
      "Ekran Pulpit od góry do dołu jak na makiecie: powitanie z pogrubionym „X dni do raportu” + skrót imienia/nazwiska jako przycisk menu (bez osobnego „Menu”), „Trening na dziś” z paskiem postępu cardio w karcie (minuty z ostatnich 7 dni vs cel, link do Cardio), suplementy, 01 Sylwetka, 02 Założenia (pierścienie + forma), 03 Od Damiana, 04 Przemiana (suwak), 05 Obwody, 06 Ostatnie treningi.",
      "Na Pulpicie kafle Treningi tyg. / Cardio tyg. / Tyg. z rzędu są zawsze pod kartą „Trening na dziś” (nie w „Inny dzień”).",
      "Sekcja Założenia na Pulpicie ma mniejsze odstępy, spokojniejsze napisy i układ spójny z Sylwetką / Obwodami.",
      "W „Trening na dziś” na Pulpicie jest mały złoty chip „Dodaj cardio” (fasolka pod głównym CTA) — otwiera arkusz wpisu cardio spójny wizualnie z Pulpitem (app-dialog, złoty gradient, chipy aktywności, złote CTA).",
      "Po starcie treningu z Pulpitu lub Treningów dolny pasek aktywnej sesji nie miga już przez ułamek sekundy — pokazuje się dopiero po wyjściu z ekranu treningu (np. powrót do aplikacji).",
      "Po zapisie zakończonego treningu zamiast krótkiego ekranu „Trening jest wyłączony” widać stan ładowania do momentu przejścia na Treningi lub Postępy.",
      "Przełączanie Pulpit · Trening · Dieta · Analiza · Profil reaguje od razu (podświetlenie zakładki, szkielet ekranu), a ciężkie dane ładują się w tle; zakładki są prefetchowane po wejściu w aplikację.",
      "Pulpit streamuje nagłówek (Cześć + menu) osobno od reszty ekranu, a sekcja Przemiana ładuje się bez odszyfrowywania wszystkich zdjęć raportów — krótszy LCP na produkcji.",
      "Raporty → Historia pomiarów nie obcina już dolnej krawędzi karty ani tabeli — przewijanie poziome ma ciemny pasek i odstęp od zaokrąglenia.",
      "Sekcja Przemiana i Postępy → Zdjęcia do porównania Start/Teraz biorą wyłącznie zdjęcie przodu z każdego raportu (nie bok ani tył).",
      "Złoty przycisk Raport na środku dolnej belki widać tylko na Pulpicie, Treningu i Analizie — na Diecie i Profilu znika.",
      "Szybkie dodanie posiłku w Diecie pokazuje jeden komunikat sukcesu — bez lawiny powtórzonych toastów po odświeżeniu dnia.",
      "Na Pulpicie kafle Makro dziś i Makro tydzień pokazują u góry pozostałe kcal, a pod spodem wyrównane kolumny zjedzone / % / zostało (B·W·T).",
      "W Diecie → Dziennik duża liczba kcal i paski makro (kcal/B/T/W) są w jednej karcie u góry — bez osobnej belki nad nawigacją.",
      "Tło aplikacji ma głębszą atmosferę (dryfujące światła, winieta, ziarno); ciemne kafle mają żywe światło krawędzi i powolny sheen — bez zmiany koloru na jasny.",
      "Usunięto pakiet ~100 startowych przepisów i stockowe grafiki Unsplash; katalog w diecie jest tylko z zewnętrznego JSON, a przy imporcie grafiki generuje AI (Pollinations z imagePromptEn).",
      "Prompt AI do generowania JSON przepisów jest pod stałe Posiłek 1–5 (mapowanie slotów sniadanie…kolacja) i wymaga zróżnicowanych makro (profile A–F), bo użytkownik zmienia tylko B/W/T.",
      "Grafiki przepisów idą przez /api/recipe-image → gen.pollinations.ai z POLLINATIONS_API_KEY (POST /v1/images/generations + fallback GET; legacy image.pollinations.ai zwracało 402).",
      "W Profilu masz zawsze 5 stałych posiłków (Posiłek 1–5) — zmieniasz tylko zalecane makro B/W/T, bez zmiany nazw ani liczby; Dieta dopasowuje przepisy i skaluje gramaturę.",
      "W sesji treningu system na bieżąco analizuje ostatni trening i zaliczone serie: pokazuje aktywną radę o ciężarze/powtórzeniach (np. „Dziś spróbuj…”, zdejmij ciężar po twardej serii, dobij powtórzenia) — na ekranie serii i w przerwie; stuknięcie wpisuje wartości.",
      "Zamknięcie treningu bez zapisu (X) pokazuje dedykowany popup GymBrat (ciemna karta, wyśrodkowany nagłówek, złote „Wróć do treningu” i czerwony secondary) zamiast systemowego okna przeglądarki.",
      "Kafelki i karty na wszystkich ekranach mają delikatny złoty cień (app-card / app-panel).",
      "Na ekranie Trening z powrotem jest karta Kontynuuj / Rozpocznij trening (rekomendowany dzień planu).",
      "Wgranie ikony Android w panelu Branding odpala przebudowę APK (GitHub Actions) i odświeżenie pliku na Vercel (Deploy Hook).",
      "Nazwy ćwiczeń z importu / AI / własnego wpisu zostają dokładnie jak w planie — bez automatycznego tłumaczenia na polskie z katalogu.",
      "Zmiana nazwy ćwiczenia w planie (np. po imporcie z PDF/Excela) nie czyści już progresu i nie wrzuca historii do „Inne” — zapis planu przepisuje nazwę w historii treningów.",
      "Ekran przerwy ma zegar z płynnie odliczającym złotym kołem (presety i +30 s resetują / wydłużają cykl animacji).",
      "Przy przekroczeniu białka, tłuszczu lub węgli Pulpit pokazuje na pasku cardio niebieski segment z dodatkowymi minutami (algorytm liczy nadwyżkę kcal, dni do końca tygodnia, szansę wyrównania dietą oraz tempo/spalanie z Twojego cardio) oraz zamknięty tooltip z wyjaśnieniem.",
      "Niebieski segment cardio jest dynamiczny w skali tygodnia: wczorajsza nadwyżka makro widać dziś; po odrobieniu dietą lub cardio pasek sam znika.",
      "Kafelek „Makro tydzień” na Pulpicie otwiera kalendarz ze statusem dni, słupkami porównania % celu między dniami, kartą „ten tydzień vs inne” (Δ% vs poprzedni i średnia tygodni) oraz szczegółami dnia względem średniej tygodnia.",
      "W Diecie → Dziennik przy Posiłek 1…5 wiersz B/W/T to suma wpisanych produktów, a nie cele z szablonu „ile możesz zjeść”.",
      "Skaner EAN nie miga już komunikatem „Nie udało się uruchomić aparatu” przy starcie kamery — błąd widać dopiero po realnej porażce.",
      "Skaner produktu ma UI z makiety: okrągłe X i latarka, złote narożniki ramki oraz dolny pasek „Nakieruj na kod kreskowy” (EAN-13/8).",
      "Po znalezieniu produktu ekran porcji jest jak na makiecie: 01 ILE (gramy, chipy, porcja), makro B/W/T/kcal, 02 wybór Posiłek 1–5, bilans „zostało / po dodaniu” oraz złote „Dodaj do dziennika”.",
      "Baza produktów w Diecie jest szersza (owoce, warzywa, nabiał, mięso, kasze, tłuszcze); wyszukiwanie rozumie liczbę mnogą (np. truskawki → Truskawka) i preferuje lokalne makro jak w Fitatu zamiast przypadkowych wpisów Open Food Facts.",
      "Przy ponownym dodaniu z „Ostatnio” makro skalują się od zapisanej porcji (albo z katalogu), a nie od błędnej „1 szt.”.",
      "Wyszukiwanie produktów odpytuje równolegle Open Food Facts (PL + świat, miliony EAN) oraz USDA FoodData Central; zapytania PL są też tłumaczone na EN (np. truskawki → strawberry), a przy skanie EAN jest fallback USDA gdy OFF nie zna kodu.",
      "Cardio ma osobny ekran: zalecenie, Nagraj trasę / Dodaj wpis / Z zegarka oraz historię wpisów; po zapisie otwiera się podsumowanie (np. Marsz) z metrykami, Udostępnij i zdjęciem ekranu urządzenia.",
      "Ekran Nagraj trasę jest pełnoekranowy: ciemna mapa GPS, badge „Nagrywam trasę”, dystans/czas, tempo/kroki/punkty GPS, czerwony Stop oraz informacja o wake-locku (ekran nie gaśnie podczas nagrywania).",
      "Obrót telefonu nie restartuje już aplikacji Android (WebView) ani PWA — Activity zachowuje stan, a manifest pozwala na dowolną orientację.",
      "Przycisk „Suplementy na dziś” na Pulpicie otwiera ekran zarządzania listą (nazwa + dawka/ilość); te same pozycje widać w Diecie → Plan.",
      "W Diecie → Dziennik pasek makro (kcal/B/T/W) siedzi nad przyciskiem Raport i nie jest już przez niego zasłaniany.",
      "Nawigacja między zakładkami jest szybsza: schemat bazy nie odpala się przy każdym kliknięciu, a przypomnienia ładują się w tle zamiast blokować ekran.",
      "„Zmień zdjęcie startowe” (Pulpit i Postępy → Zdjęcia) otwiera galerię telefonu i zapisuje wybrane zdjęcie jako Start w porównaniu przemiany.",
      "Brak integracji z Fitatu — żywienie liczy się wyłącznie z dziennika GymBrat (skan / wyszukiwanie) i celów z profilu; usunięto most proxy i łączenie konta.",
      "Postępy (Siła) mają nagłówek z datą startu, chipy zakładek, kartę Moje maxy, podsumowanie objętości (rośnie/stoi/spada) oraz listy ćwiczeń per dzień planu z deltą, sparkline i stanem „pierwszy trening” / „jeszcze nie robione”.",
      "Postępy (Siła) analizują intensywność: średni RIR/RPE, odsetek twardych serii, zgodność RIR z celem planu, tempo z planu oraz trend — na liście Siła i na szczegółach ćwiczenia (wykres RIR/RPE).",
      "W sesji zaliczenie serii wymaga ciężaru > 0 i powtórzeń — przy 0 kg / pustym ciężarze jest „Pomiń serię” (nie zielone zaliczenie). Postępy nadal rozumieją serie masy ciała w historii (suma/max powtórzeń zamiast e1RM).",
      "Po „Pomiń serię” sesja od razu idzie do kolejnej serii/ćwiczenia (bez przerwy), a „Wróć do pominiętej” otwiera właściwą serię; Wstecz też wraca po świeżym stanie planu.",
      "Historia raportów ciała w Postępach i osiągnięciach obejmuje do 500 wpisów (wcześniej ucięcie do 50 zostawiało starsze pomiary tylko w bazie).",
      "Cardio hub pokazuje sumy tygodnia i trendy 8 tyg. (dystans, kalorie, kroki, tempo); w formularzach i po treningu siłowym da się zapisać te metryki — nie tylko minuty.",
      "Statystyki siłowe scalają warianty nazw ćwiczeń (PL/EN, aliasy katalogu, spacje/diakrytyki) do jednej serii — np. „Bench Press” i „Wyciskanie sztangi na ławce poziomej”.",
      "Tonaż i powtórzenia w historii, hubach i KPI liczą wyłącznie serie naprawdę wykonane — pominięte (skipped) nie zawyżają już objętości ani liczby zaliczonych serii.",
      "Postępy (Sylwetka) mają kartę wagi z wykresem (kropki = raporty, linia = średnia), sekcje Tempo, Cel (waga docelowa + ETA) oraz Obwody ze sparkline od startu.",
      "W Postępach → Sylwetka → Obwody jest też trend brzucha z raportów (obok pasa, uda, klatki i ramienia); spadek liczy się jako poprawa.",
      "Postępy (Zdjęcia) mają slider Start/Teraz ze złotym uchwytem, zmianę zdjęcia startowego, karty z wagą/pasem oraz tabelę delt (waga, pas).",
      "Postępy (Tydzień) mają kartę bieżącego tygodnia jak na makiecie: zakres dat, licznik treningów, siatka 7 dni (złote kółko + ptaszek, obwódka na dziś, niebieska kropka pod dniem cardio), legenda oraz sekcja W tym tygodniu z tonażem i cardio wyrównanymi w prawo; dalej wykres 8 tygodni, cele i osiągnięcia.",
      "Postępy → Tydzień spina dietę z treningiem: kcal/białko z dziennika vs cele oraz tonaż, RPE i RIR w tych samych 8 tygodniach; status „W diecie” przy 85–110% kcal.",
      "Hub Trening ma nagłówek z licznikiem tygodnia, kartę niedokończonej sesji (Kontynuuj / Porzuć), Dni planu z PDF i dziennikiem obciążeń, Korektę techniki, Postępy/Historię oraz Cardio; Historia treningów ma KPI, filtry, grupy tygodni i „Popraw” w oknie 7 dni.",
      "Dieta → Plan ma układ z makiet: nagłówek „Twój plan” z Plan/Dziennik, chipy dzień treningowy/nietreningowy, kartę MAKRO NA DZIEŃ, osobne kafle posiłków (accordion z wyszukiwarką, filtrami smaku/kategorii/trudności i siatką dań) oraz listę zakupów.",
      "Dieta → Dziennik ma układ z makiet: nagłówek „Co zjadłeś / Dziennik”, nawigację daty, chipy Treningowy/Nietreningowy/domyślnie, kartę ZJEDZONE, złoty skan kodu oraz kafle Posiłek 1…N z trzema akcjami (skan, przepisy, plus).",
      "Ekran „Trening zrobiony” ma układ z makiet: puchar + nazwa planu, duży tonaż (font metryczny), czas / serie / ćwiczenia w trzech kolumnach, sekcje 01 Nowe rekordy i 02 Najlepsze serie (wiersze w siatce, do dwóch linii nazwy), stopka + cardio przed „Gotowe” — wszystko na szerokości Pulpitu (max-w-lg), portal pełnoekranowy.",
      "Po zakończeniu ćwiczenia (ekran przerwy / Dalej) sesja pomija już zaliczone pozycje i przechodzi do kolejnego niedokończonego ćwiczenia — także gdy kolejność wykonania była inna niż w planie.",
      "Po dodaniu serii w trakcie treningu ekran przerwy znowu pojawia się po kolejnych zaliczonych seriach.",
      "Wpisany ciężar i powtórzenia zapisują się od razu; Wstecz oraz skoki między seriami/ćwiczeniami nie czyszczą wcześniej wpisanych wartości. Seria bez ciężaru nie świeci na zielono — zaliczenie wymaga danych, pominięcie jest pomarańczowe.",
      "Aktywny trening zapisuje się na bieżąco (telefon + chmura), nie dopiero przy zakończeniu sesji.",
      "W panelu admina (Branding) wgrywasz logo i ikony web/PWA/Android/iOS bez edycji kodu — web i logo w aplikacji od razu; ikona Android na launcherze przy pushu na master (APK buduje się w Actions równolegle ze stroną).",
      "Przyciski w wizardzie raportu i na ekranie przerwy mają jednolity złoty styl CTA; podczas treningu ciężar i serie są edytowalne.",
      "Po imporcie planu z PDF/Word/Excel można edytować ćwiczenia, a w planie ustawisz RIR, tempo, notatki i superserie.",
      "Na Treningach działa eksport planu do PDF/druku oraz generowanie planu z AI (dni siłowe zapisują się do edycji).",
      "Sugestia ciężaru z ostatniej sesji (chip per seria) oraz ekran postępu z badge NOWY MAX po pobiciu rekordu.",
      "Po rekordzie na podsumowaniu treningu widać grafikę „NOWY MAX” generowaną przez agenta Pollinations (złoty motyw siłowni) z nakładką GymBrat.",
      "Po zaliczeniu wszystkich serii (bez pominięć) od razu jest ekran „Trening zrobiony”; przy pominiętych seriach popup pozwala wrócić albo zakończyć. Minuty cardio z ekranu zakończenia zapisują się w treningu i wliczają do KPI cardio (Historia, Pulpit); w sesji jest „Zakończ bez zapisu”; „+ Seria” dodaje serię na końcu bez przeskoku z aktualnie wykonywanej.",
      "Niedokończoną sesję treningu da się wznowić na innym telefonie lub PC dzięki synchronizacji aktywnej sesji w chmurze.",
      "Na Pulpicie w Makro dziś widać ile już zjedzono i ile zostało do spożycia (B/W/T).",
      "Przepisy w Dietcie pochodzą wyłącznie z panelu admina (JSON) — wyczyszczenie bazy usuwa je z aplikacji.",
      "W panelu admina jest pakiet startowy przepisów, walidacja i eksport JSON, empty state w pustej Dietcie oraz kopiowalny prompt dla zewnętrznego AI (dokładny kontrakt JSON do generowania przepisów).",
      "Na Planie w Dietcie widać propozycje pod braki makro z katalogu.",
      "Wyszukiwanie w Jadłospisie obejmuje też popularne produkty sieci (KFC, Lidl, Biedronka…) oraz szersze dopasowanie nazwa+marka.",
      "Wpis w Jadłospisie da się edytować (nazwa, sekcja, makro) — nie trzeba już usuwać i dodawać od nowa przy złej gramaturze.",
      "Zakładka Ostatnie powtarza produkty z historii dziennika zamiast „popularnych” z początku bazy.",
      "Przy produktach sieci (KFC/Lidl/Biedronka…) widać jasno: szacunek / sprawdź etykietę.",
      "Ulubione działają (serce na ekranie porcji, lista lokalna); martwa zakładka Własne jest schowana.",
      "Przycisk + z sekcji Jadłospisu przenosi slot do katalogu potraw (mapa por Plan ↔ dziennik).",
      "Na Pulpicie przy pierwszym wejściu w danym dniu pojawia się popup „Ten tydzień” (kcal, treningi X/Y, raport + jeden CTA).",
      "Na Jadłospisie: cele dnia, rozkład posiłków, po stuknięciu siatka dopasowanych dań (filtry trudność / słone–słodkie) oraz karta zdjęcie↔przepis.",
      "W profilu jasno: propozycje posiłków = katalog i makro, nie model AI; słownik PL/EN obejmuje Dietę, panel katalogu i sesję.",
      "W panelu admina można wgrywać przepisy JSON do bazy (bez zmiany kodu); tylko główny admin nadaje innym uprawnienia admina.",
      "Import katalogu akceptuje też uproszczony JSON (mealType, calories/protein/carbs/fat, prepTime, instructions) — w tym pojedynczy przepis.",
      "Telefon wibruje przy końcu przerwy, zakończeniu ćwiczenia, pobiciu rekordu (NOWY MAX) i domknięciu treningu.",
      "Ekran serii w sesji: technika ↗ (YouTube z planu treningowego), Zgłoś, kropki serii, ciężar ±2,5/±0,5, W zapasie i Zalicz serię.",
      "Statystyki i porównania (historia, Pulpit) liczą się osobno per dzień planu — Nogi tylko do Nóg, Push tylko do Push.",
      "Pulpit, Dieta, Treningi, Analiza, Profil, Historia, Raporty i sesja treningu mają spójne nagłówki, karty (app-card) oraz złote CTA.",
      "Po zapisie treningu „Zobacz postęp” otwiera popup z analizą vs poprzednia sesja tego samego planu (tonaż, ↑/↓/pominięte, ćwiczenia).",
      "Wykresy na Analizie mają złote gradienty, czystsze osie i karty app-card — spójnie z Pulpitem i Historią.",
      "Po „Wszystkie serie wykonane”, jeśli coś pominięto (także kilka serii), jest komunikat i przycisk powrotu do pominiętego ćwiczenia.",
      "Link YouTube „technika ↗” dodajesz przy ćwiczeniu w edycji planu (pole pod nazwą) — zapisuje się przy ćwiczeniu.",
      "Dni planu (Pulpit, Trening) są w kolejce od najdawniej / nigdy nie robionego (góra i propozycja „na dziś”) do ostatnio robionego (dół listy).",
      "Przy każdym dniu planu na Pulpicie (Inny dzień) i na ekranie Trening widać datę ostatniego wykonania (dd.mm) obok nazwy — nie tylko „X dni temu”.",
      "W Profilu użytkownicy przeglądarki mają bezpośredni link do najnowszego APK Android (z numerem wersji).",
      "W Profilu przełącznik postępów: porównania tonażu w % albo w kg (Historia i popup po treningu).",
      "Android 0.1.7: przy aktualizacji APK z innym podpisem aplikacja ostrzega, zamiast zawieszać instalator — wtedy odinstaluj starą GymBrat i zainstaluj ponownie.",
    ],
  },
  {
    title: "2026-09 — Android 0.1.10: pobieranie APK bez zawieszania",
    date: "2026-09-30",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    bullets: [
      "W Profilu pobieranie APK idzie z paskiem postępu i systemowym Share („Zapisz w plikach”), zamiast menedżera Chrome, który często wisi na 100%.",
      "Aplikacja Android nie otwiera już pliku .apk wewnątrz WebView — używa systemowego DownloadManagera.",
    ],
  },
  {
    title: "2026-09 — Android 0.1.9",
    date: "2026-09-30",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    bullets: [
      "W Profilu do pobrania jest nowy build Android 0.1.9 (versionCode 10) z gym-brat.vercel.app/gymbrat.apk — świeży Release, nie sam bump numeru przy starym pliku.",
      "Jeśli pobieranie „wisi” albo instalator nie startuje: odinstaluj starą GymBrat (inny podpis), potem zainstaluj APK z Profilu.",
      "Pobieranie APK używa wersjonowanej nazwy pliku (gymbrat-0.1.9.apk), żeby Chrome na Androidzie nie wisiał na utkniętym starym downloadzie.",
    ],
  },
  {
    title: "2026-09 — Pobieranie APK same-origin",
    date: "2026-09-29",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    bullets: [
      "Pobieranie APK z Profilu idzie z gym-brat.vercel.app/gymbrat.apk (same-origin), żeby Chrome na Androidzie nie wisiał na 100%.",
    ],
  },
  {
    title: "2026-09 — Pulpit: Inny dzień + ekrany treningu jak na grafikach",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Na Pulpicie „Inny dzień” rozwija listę dni planu (Push A, Pull…) z przyciskiem Start →; „Zacznij trening” od razu uruchamia sesję prowadzoną.",
      "Lista ćwiczeń w sesji ma kolory statusu (złoty = bieżące, zielony = zrobione) oraz kropki serii jak na screenach.",
      "Po zaliczeniu serii pojawia się pełnoekranowa Przerwa z dużym timerem, presetami 1:00–3:00, kartą zaliczone/następne oraz przyciskiem Dalej.",
    ],
  },
  {
    title: "2026-09 — belka Raport na środku, jadłospis Fitatu, zapis cardio",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Przycisk „+ Raport” na dolnej belce jest wyśrodkowany względem całego paska, a nie przesunięty między Dietą a Treningami.",
      "Dodawanie posiłku otwiera pełny ekran Szukaj z trzema przyciskami na dole: Nowy produkt, Nowa potrawa i Szybkie dodawanie (formularz nazwa + kcal/tłuszcze/węgle/białko).",
      "Przycisk + przy sekcji posiłku znów otwiera ten ekran zamiast niedziałającego skrótu.",
      "W arkuszu cardio przycisk „Zapisz N min” zostaje zawsze widoczny nad belką systemową.",
    ],
  },
  {
    title: "2026-09 — pulpit, jadłospis, raport, cardio i Analiza w belce",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Na Pulpicie „wykonane cardio” liczy tylko wpisy cardio — trening siłowy nie podbija już minut.",
      "W Jadłospisie przy dodawaniu do sekcji są trzy opcje: nowy produkt, nowa potrawa i szybkie dodawanie makro; pasek kcal jest od razu pod kolacją.",
      "W belce dolnej jest Analiza; raport wymaga pasa, uda, klatki i ramienia, a w podsumowaniu widać trzy miniatury zdjęć.",
      "Zapis cardio: edytowalne minuty i przycisk Zapisz nad dolną belką (nie pod nią).",
    ],
  },
  {
    title: "2026-09 — PDF w imporcie planu nie jest już wyszarzony",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Wybór pliku planu na Androidzie nie wyszarza już PDF — picker przyjmuje wszystkie pliki, a typ (.pdf / Word / Excel) sprawdza aplikacja po wyborze.",
      "W Profilu → Plan treningowy możesz wgrać „Plan treningowy Damian masa.pdf” z folderu Pobrane.",
    ],
  },
  {
    title: "2026-09 — import planu treningowego z PDF",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "W Profilu → Plan treningowy możesz wgrać plan z PDF — aplikacja czyta dni (Push, Pull, Nogi, Klatka, Barki) oraz serie i powtórzenia w zapisie „2s 8-10p”.",
      "Obsługiwane są też Word i Excel; na Androidzie wybierz plik z folderu Pobrane.",
    ],
  },
  {
    title: "2026-09 — import Excela: pusty plik z Androida (400 w 16 ms)",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Import planu z Excela na Androidzie nie wysyła już pustego pliku: bajty są kopiowane od razu po wyborze, zanim WebView wyczyści input.",
      "API jasno zgłasza pusty upload; aplikacja Android kopiuje wybrany dokument do pamięci podręcznej, żeby serwer dostał treść .xlsx / .doc.",
    ],
  },
  {
    title: "2026-09 — naprawa importu Excela (Android 400)",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Import planu treningowego z Excela na Androidzie jest odporny na pustą nazwę pliku (rozpoznanie po MIME i magicznych bajtach) oraz na arkusze z tytułem w pierwszym wierszu.",
      "Gdy w Excelu nie ma typowych nagłówków kolumn, aplikacja czyta też układ tekstowy typu „Przysiady 4x8”.",
    ],
  },
  {
    title: "2026-09 — import planu także ze starego Worda (.doc)",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Import planu treningowego obsługuje też stary format Word (.doc), nie tylko .docx i Excel.",
      "Na ekranie Treningi przycisk „Import Word” prowadzi do ustawienia planu w Profilu (zamiast pustego eksportu).",
    ],
  },
  {
    title: "2026-09 — import planu z Excela/Worda na Androidzie + dokładny wykres wagi",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Import planu treningowego działa z Worda (.docx) i Excela (.xlsx); picker na Androidzie nie blokuje już plików z Pobranych przez zbyt wąski filtr MIME.",
      "Na Pulpicie wykres Waga i pas pokazuje dokładne wartości (kafelki ostatniej wagi/pasa, etykiety przy punktach, pełna data w podpowiedzi).",
    ],
  },
  {
    title: "2026-09 — import planu treningowego z Worda (.docx)",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "W Profilu → Plan treningowy możesz wgrać plan z pliku Word (.docx) — aplikacja tworzy dni/plany z ćwiczeniami, seriami i powtórzeniami.",
      "Nagłówki typu „Dzień A” / „Push” stają się osobnymi planami; linie w stylu „Przysiady 4x8” trafiają jako ćwiczenia (z dopasowaniem do katalogu GymBrat).",
    ],
  },
  {
    title: "2026-09 — raport: wymagane zdjęcia, bez brzucha, cykl w profilu",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Przy dodawaniu raportu wymagane są zawsze trzy zdjęcia (przód, bok, tył); usunięto pole Brzuch (cm), bo dublowało pas.",
      "W Profilu ustawiasz co ile dni dodawać raport — timer na Pulpicie i w Raportach restartuje się po każdym zapisie.",
    ],
  },
  {
    title: "2026-09 — Pulpit, Profil, Analiza i pasek dolny",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Na Pulpicie etykieta streaku to „Tren. tyg. z rzędu”, a kafelek Raporty zastępuje Makro tydzień (analogicznie do Makro dziś).",
      "W dolnym pasku zamiast Wiadomości jest Profil; Nowości zostają w menu i w Profilu.",
      "Profil ma tylko ustawienia używane w aplikacji (plan, cardio, dieta, przypomnienia, szablony posiłków, pomiary, hasło, eksport) — bez zbędnych celów fitness niewidocznych nigdzie indziej.",
      "Ekran Analiza ma układ i styl jak Pulpit: kafle statystyk, ważenie, wykresy wagi/tonażu/siły oraz postęp ćwiczeń — bez zdublowanych skrótów i bloku metodyki.",
    ],
  },
  {
    title: "2026-09 — raport: podsumowanie jak na screenie + popup sukcesu",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Krok Podsumowanie w raporcie pokazuje pomiary, złote paski samopoczucia i Tak/Nie jak na pierwotnym ekranie — zamiast samej listy tekstowej.",
      "Po zapisie raportu pojawia się animowany popup (preloader, potem potwierdzenie sukcesu).",
      "Na Pulpicie Forma dziś i Trzymanie się założeń mają złote nagłówki i czytelniejsze kafle jak w referencji.",
    ],
  },
  {
    title: "2026-09 — baza produktów: poprawne nazwy (bez skyr→screw)",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Przy wyszukiwaniu produktów do planu nazwy nie biorą już zepsutych tłumaczeń z Open Food Facts (np. „Screw” zamiast „Skyr”) — zostaje oryginalna / polska nazwa produktu.",
      "Nazwy produktów w wynikach wyszukiwania i na ekranie porcji są chronione przed automatycznym tłumaczeniem przeglądarki.",
    ],
  },
  {
    title: "2026-09 — przepisy: gramatura, kroki i panel szczegółów",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "W katalogu posiłków składniki mają jasną gramaturę (co i ile odważyć), a kroki opisują jak przygotować porcję — nie tylko krótkie hasła.",
      "Panel szczegółów przepisu ma poprawny układ (pełna szerokość, ciemne tło GymBrat, czytelna lista gramatur i numerowane kroki), bez rozjechanych tekstów.",
    ],
  },
  {
    title: "2026-09 — Trzymanie się założeń i podpowiedzi w raporcie",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Na Pulpicie sekcja Trzymanie się założeń ma pierścienie % (Dieta / Treningi / Cardio), paski historii (zielone = zrealizowane, czerwone = opuszczone), legendę oraz podpis „Ostatnie 24 z N”.",
      "Przy dodawaniu raportu pola pomiarów, skali samopoczucia i Tak/Nie pokazują w tle wartości z ostatniego raportu jako podpowiedź.",
    ],
  },
  {
    title: "2026-09 — Treningi: hub, sesja prowadzona, plan w profilu",
    date: "2026-09-26",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Zakładka Treningi to hub: wybór dnia planu, Rozpocznij trening, Dodaj cardio, statystyki tygodnia oraz ostatnie treningi i cardio — bez edycji planu.",
      "Ustawianie planu treningowego (dni i ćwiczenia) jest w Profilu → Plan treningowy.",
      "Sesja prowadzona ma steppery ciężaru i powtórzeń, RIR (w zapasie), Zalicz serię, listę ćwiczeń oraz ekran Trening zrobiony.",
      "Dodaj cardio otwiera arkusz: maszyna, czas, dystans, tętno i notatka w stylu GymBrat.",
    ],
  },
  {
    title: "2026-09 — trening jak na zrzutach: plany, start, sesja",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Ekran Plany pokazuje listę z liczbą ćwiczeń i serii, „+ Nowy plan” oraz „Moje ćwiczenia”; w edytorze ustawiasz serie i kolejność, a zapis/anulowanie jest jak w aplikacji treningowej.",
      "Start treningu ma kafle ostatniej sesji (postęp/suma kg i powtórzeń), pasek dni tygodnia, wykres Ciężar/Powt. oraz duży przycisk Rozpocznij trening z wyborem planu (data ostatniego użycia).",
      "W sesji widać porównanie do poprzedniego treningu (−/+ powt. i ciężar), ptaszki przy seriach, menu ćwiczenia (notatka, dodaj/zamień, historia) oraz Anuluj / Zakończ — w czarno-złotym stylu GymBrat.",
    ],
  },
  {
    title: "2026-09 — Start, raporty, dieta: układ i płynność",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Na Raportach usunięto sekcję Archiwum (Twoje raporty / eksport / import historii z Excela) — zostaje formularz i historia pomiarów.",
      "Na Pulpicie kafelek „W programie” zastępuje wykres postępu makro dnia (białko, węglowodany, tłuszcze — ile zostało do spożycia względem celu).",
      "Usunięto diagram „Od startu”; wykres wagi i pasa ma czytelniejszy wygląd, legendę oraz płynną animację linii przy zmianie zakresu dni.",
      "Sekcje Forma dziś i Trzymanie się założeń mają wyraźniejsze kafle odseparowane od tła, żeby nie zlewały się z pulpitem.",
      "Systemowy wstecz w telefonie przy dodawaniu posiłku wraca do jadłospisu zamiast na Pulpit; poprawiono skalowanie viewportu na iPhone.",
    ],
  },
  {
    title: "2026-09 — scoring produktów i pełne nazwy ze skanu",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Ocena GymBrat uwzględnia kalorie, tłuszcz, cukier, sól, białko, błonnik oraz sygnały ultra-przetworzenia — chipsy dostają niską ocenę zamiast prawie 5/5.",
      "Pod oceną widać uzasadnienia (np. wysoka kaloryczność, dużo soli) oraz etykietę Świetny–Unikaj.",
      "Po skanie i wyszukiwaniu nazwa to marka + produkt (np. „Piątnica Twaróg chudy”), bez uciętych skrótów.",
      "Na ekranie porcji domyślna ilość to gramatura opakowania z etykiety (np. kubek 330 g), z podpowiedzią „opakowanie” — nie zawsze 100 g.",
    ],
  },
  {
    title: "2026-09 — Android 0.1.5: aktualizacja APK i dialog kamery",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "W profilu aplikacji Android „Sprawdź ponownie” porównuje Twoją wersję z najnowszym APK (0.1.5) i uruchamia pobieranie, gdy jest nowsza kompilacja.",
      "Serwer nie bierze już starszego GitHub Release nad nowszą wersją z aplikacji — aktualizacja do 0.1.5 znów jest widoczna przy 0.1.3.",
      "APK 0.1.5 naprawia brak systemowego pytania o aparat przy skanie EAN (most requestCameraPermission).",
    ],
  },
  {
    title: "2026-09 — Android: dialog kamery przy skanie EAN",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "W aplikacji Android skaner EAN najpierw pokazuje systemowy dialog zgody na aparat (most GymBratAndroid), a dopiero potem uruchamia kamerę — naprawia brak pytania o uprawnienie w WebView.",
      "Gdy kamera była wcześniej zablokowana, na ekranie skanu jest link „Otwórz ustawienia aplikacji”. Zainstaluj GymBrat Android 0.1.5.",
    ],
  },
  {
    title: "2026-09 — karta produktu: szczegóły odżywcze jak Fitatu",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Na ekranie porcji rozwijasz „W 100 g” i widzisz tabelę makro/mikro (tłuszcze nasycone, cukry, błonnik, witaminy, minerały) z wartością „b.d.” gdy brak danych.",
      "Pod tabelą są wymienniki WW i WBT, składniki z tagami Zdrowy / Bezpieczny / Szkodliwy oraz ocena GymBrat na podstawie soli, cukru i tłuszczu nasyconego.",
      "Porcje g / ml / sztuka i sticky pasek makro dnia (kcal, białko, tłuszcz, węgle) zostają widoczne podczas przewijania szczegółów.",
    ],
  },
  {
    title: "2026-09 — dziennik diety jak Fitatu: jadłospis, szukaj, porcja",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Jadłospis ma pasek dni tygodnia, sekcje Śniadanie–Kolacja z przyciskiem + oraz sticky makro dnia (kcal, białko, tłuszcz, węgle).",
      "Dodawanie posiłku to pełny ekran Szukaj ze skanerem w pasku wyszukiwania; po wyborze ustawiasz gramy lub sztuki jak w Fitatu.",
      "Skaner EAN jest pełnoekranowy z kwadratową ramką i przyciskiem Wyłącz aparat — nad paskiem nawigacji aplikacji.",
    ],
  },
  {
    title: "2026-09 — skan diety: ilość g/ml/szt. i naprawione wyszukiwanie",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Aparat przy skanie etykiety zajmuje cały ekran (nad paskiem nawigacji), ma stabilny podgląd, przycisk „Wyłącz aparat” i szybszy odczyt EAN.",
      "Po skanie i po wyborze z wyszukiwania ustawiasz ilość w gramach, mililitrach albo sztukach, a makro przelicza się jak w Fitatu (baza na 100 g).",
      "Wpisanie nazwy (np. kiwi) wyszukuje na żywo w lokalnej bazie i Open Food Facts — uzupełniono typowe owoce i warzywa.",
    ],
  },
  {
    title: "2026-09 — Start: makro Od startu i poprawione kafle",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "W Następnym treningu kafle Treningi tyg., Cardio tyg. i Tyg. z rzędu mają wyraźne kolory, a seria liczy kolejne tygodnie z treningiem zamiast dni.",
      "Kafelek Od startu to wykres liniowy makro dziennego (białko, węglowodany, tłuszcze) oraz pozostałych kalorii do spożycia względem celu z profilu.",
      "W programie liczy dni od pierwszego raportu, a wykres wagi i pasa aktualizuje się po nowym raporcie sylwetki (waga z raportu trafia na wykres).",
    ],
  },
  {
    title: "2026-09 — usuwanie produktu bez systemowego okna",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Usuwanie produktu z dziennika diety otwiera ciemny dialog GymBrat (Anuluj / Usuń) zamiast komunikatu przeglądarki z adresem Vercel.",
    ],
  },
  {
    title: "2026-09 — dziennik diety jak Getao + naprawiony zoom skanera",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Ekran Dieta ma widok Dziennik jak w Getao: przełącznik Plan/Dziennik, data, dzień treningowy/nietreningowy, karta kcal/BWT oraz złoty przycisk „Skanuj kod kreskowy”.",
      "Skaner otwiera aparat w ramce bez sztucznego przybliżenia (object-contain + minimalny zoom) — kod z etykiety da się wygodnie zeskanować, a makro trafia do sekcji posiłku.",
    ],
  },
  {
    title: "2026-09 — skan etykiety aparatem na Diecie",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Przycisk „Skanuj etykietę produktu” na Diecie otwiera aparat — zeskanuj kod EAN z opakowania, a makro (białko, węgle, tłuszcz, kcal) trafi od razu do wybranej sekcji dziennika.",
      "Aplikacja Android 0.1.4 prosi o dostęp do kamery w WebView, żeby skan działał też w APK.",
    ],
  },
  {
    title: "2026-09 — dieta jak Fitatu: skan i sekcje posiłków",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Na ekranie Dieta możesz wyszukać produkt w bazie albo zeskanować kod kreskowy — od razu widać białko, węglowodany, tłuszcz i kalorie przed dodaniem.",
      "Na dole ekranu są sekcje śniadanie, drugie śniadanie, lunch, obiad i przekąska: dodajesz produkty do wybranej pory i widzisz sumę makro w każdej sekcji.",
    ],
  },
  {
    title: "2026-09 — dieta bez AI i bogatszy katalog przepisów",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Aplikacja nie oferuje już funkcji AI: ukryto czat trenera, ustawienia AI w profilu i panelu admina oraz kartę „plan z AI”; briefing dnia i propozycje posiłków działają wyłącznie na danych z aplikacji i lokalnym katalogu.",
      "Katalog diety ma ponad sto unikalnych przepisów (śniadanie–kolacja) zamiast klonów typu jajecznica z różnymi dodatkami — każde danie z makro, składnikami i krótkim przepisem.",
    ],
  },
  {
    title: "2026-09 — start raportu z paska + naprawa zapisu zdjęć",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Przycisk Raport na dolnym pasku od razu otwiera wizard dodawania; podczas wypełniania środkowy przycisk jest ukryty.",
      "Wpisane pomiary i odpowiedzi zostają po Wstecz między krokami, a zapis raportu nie pada już na zbyt dużych zdjęciach — widać też konkretny komunikat błędu.",
    ],
  },
  {
    title: "2026-09 — przywrócenie produkcji + wizard raportów",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Produkcja znów zawiera cały dotychczasowy stack (złoty UI, kafle, Android, dieta) — Promote ze starego mastera został cofnięty przez ten deploy.",
      "Dodawanie raportu to pięciostopniowy wizard: pomiary (waga wymagana), samopoczucie na złotych paskach, zgodność TAK/NIE, zdjęcia przód/bok/tył oraz podsumowanie.",
      "Po kliknięciu „Dodaj raport” przycisk znika — zostaje karta kroków; historia pomiarów ma tabelę z deltami i widokami Pomiary / Samopoczucie / Plan.",
    ],
  },
  {
    title: "2026-09 — backend Java oddzielony od frontu",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Backend API GymBrat działa w Java (Spring Boot) w katalogu java-backend — health, version, Android APK, raporty sylwetki i domknięcie treningu.",
      "Front zostaje w Next.js/TypeScript; gdy ustawisz JAVA_API_BASE_URL, trasy /api proxy’ują do Javy (sesja NextAuth + nagłówek użytkownika), a bez tej zmiennej działa dotychczasowa logika TypeScript.",
    ],
  },
  {
    title: "2026-09 — kafelki wagi i wyższy przycisk Raport",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Kafelki Waga, Od startu, Tempo i W programie mają złote ikony, duże liczby i podpisy w stylu ekranu startu — w tym zmianę wagi względem poprzedniego raportu.",
      "Złoty przycisk Raport na dolnej belce siedzi wyżej, w linii z ikonami nawigacji, a nie poniżej ich krawędzi.",
    ],
  },
  {
    title: "2026-09 — kafelki wymiarów jak na ekranie startu",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Kafelki Pas, Udo, Klatka i Ramię na Pulpicie mają wykres obszarowy, dużą liczbę, strzałkę zmiany oraz podpis startu i liczby pomiarów — w układzie zbliżonym do referencyjnego ekranu.",
      "Kolory wykresów (zieleń, błękit, złoto, róż) i typografia wyróżniają każdy wymiar na ciemnym tle karty.",
    ],
  },
  {
    title: "2026-09 — zdjęcia w raporcie wracają do APK",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Po wyborze zdjęcia w galerii telefonu wraca ono do formularza raportu w aplikacji Android — wcześniej galeria się otwierała, ale plik nie trafiał do pola zdjęć.",
      "Zainstaluj GymBrat Android 0.1.3, a na stronie używany jest bezpośredni wybór pliku (bez sztucznego klikania inputa), żeby WebView poprawnie przyjął zdjęcie.",
    ],
  },
  {
    title: "2026-09 — wybór zdjęć w aplikacji Android",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Aplikacja GymBrat na telefonie (WebView) otwiera galerię przy „Wybierz zdjęcia” w raporcie — wcześniej klik w APK nic nie robił, bo brakowało obsługi wyboru pliku.",
      "Zainstaluj aktualizację Android 0.1.2 (versionCode 3), żeby wybór zdjęć sylwetki działał tak jak w przeglądarce na komputerze.",
    ],
  },
  {
    title: "2026-09 — wybór pliku w raporcie znów działa",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Na ekranie Dodaj raport przycisk wyboru zdjęć sylwetki znów otwiera selektor plików — nie jest już przycinany ani zasłonięty przez układ karty.",
      "Ten sam niezawodny wybór pliku działa przy imporcie Excel z historią raportów.",
    ],
  },
  {
    title: "2026-09 — wyraźniejsze złote przyciski",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Przyciski na wszystkich ekranach mają jaśniejsze złoto, metaliczny gradient i wyraźniejszy cień — wyglądają nowocześniej i bardziej wyróżniają się na czarnym tle.",
      "Wspólne style gym-btn-primary, gym-btn-outline i gym-btn-secondary obejmują CTA w nawigacji, na startcie treningu, w diecie, profilu i raportach.",
    ],
  },
  {
    title: "2026-09 — dieta tylko z lokalnej bazy przepisów",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Zakładka Dieta pokazuje przepisy wyłącznie z lokalnej bazy GymBrat — bez generowania przez AI i bez linków z internetu.",
      "Przycisk „Propozycje z bazy” dobiera dania do pory dnia oraz braków białka, węglowodanów i tłuszczu z Twojego planu.",
    ],
  },
  {
    title: "2026-09 — baza posiłków w diecie",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "W zakładce Dieta jest lokalna baza około 590 przepisów z makro (białko, węglowodany, tłuszcz) oraz grafiką i instrukcją przygotowania.",
      "Posiłki są podzielone na śniadanie, drugie śniadanie, obiad, podwieczorek i kolację — możesz filtrować, wyszukiwać i dodawać je do dziennika.",
      "Propozycje dnia i przeglądanie katalogu biorą się z tej samej bazy aplikacji.",
    ],
  },
  {
    title: "2026-09 — aktualizacja APK tylko dla GymBrat",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Popup „Wymagana aktualizacja” porównuje wersję zainstalowanego GymBrat z release’em GymBrat 0.1.1, a nie z wersją 1.11.5 Akademii Wielkich Piłkarzy.",
      "Przycisk aktualizacji pobiera gymbrat.apk z GitHub Release tego repozytorium — instalator Akademii nie jest już podsuwany w aplikacji GymBrat.",
    ],
  },
  {
    title: "2026-09 — start aplikacji bez 307 na logowanie",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Wejście na adres główny bez sesji oddaje ekran logowania z kodem 200 — Vercel i WebView nie widzą już przekierowania 307 na /login.",
      "Tożsamość aplikacji Android jest cache’owana, żeby React nie wpadał w pętlę aktualizacji i nie pokazywał fałszywego błędu przy starcie APK.",
    ],
  },
  {
    title: "2026-09 — bez fałszywego popupu o zmianach",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Aplikacja nie pokazuje już okna „Zmieniamy się na lepsze” przy zwykłym logu w konsoli albo nieudanym zliczeniu wejścia.",
      "Komunikat o awarii pojawia się tylko przy prawdziwym błędzie ekranu i mówi „Coś poszło nie tak”.",
    ],
  },
  {
    title: "2026-09 — analytics page-view z aplikacji Android",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "POST /api/analytics/page-view znów przyjmuje żądania z tego samego hosta (np. gym-brat.vercel.app), także gdy lista Origin w zmiennych środowiskowych nie zawiera aliasu produkcyjnego Vercel.",
      "Beacony z WebView GymBratAndroidApp nie dostają już błędnego 403 przy Sec-Fetch-Site: none — zliczanie wejść w aplikacji Android działa.",
    ],
  },
  {
    title: "2026-09 — pulpit i ekrany jak w aplikacji mobilnej",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Ekrany po zalogowaniu mają czarne tło, płaskie ciemne karty i złote liczby — ten sam rytm co na zdjęciach referencyjnych.",
      "Na dole jest pasek Pulpit, Dieta, Treningi i Wiadomości oraz złoty przycisk Raport na środku.",
      "Start pokazuje powitanie, następny trening z przyciskiem Zacznij trening, wagę, tempo, formę, przemianę i wymiary ze wykresami.",
      "Dieta ma układ planu żywieniowego z kafelkami makro, a logowanie nadal zostaje przy zdjęciu siłowni.",
    ],
  },
  {
    title: "2026-09 — czarno-złoty styl logowania w całej aplikacji",
    date: "2026-09-25",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Wszystkie ekrany korzystają z tego samego czarno-złotego języka co logowanie: złoty akcent, tło ze zdjęciem siłowni i panelami glass/gold.",
      "Nawigacja, przyciski CTA, wykresy i paski postępu używają tokenów --neon zamiast twardej czerwieni ulicznej.",
      "Marka GymBrat w nagłówku ma ten sam krój display (Bebas) co na ekranie logowania.",
      "Ekran Start ma złoty panel powitalny spójny z resztą aplikacji.",
    ],
  },
  {
    title: "2026-09 — nowy ekran Start i wymiary w raporcie",
    date: "2026-09-19",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Ekran Start pokazuje powitanie z imieniem, następny trening z przyciskiem Rozpocznij oraz mini-statystyki tygodnia i serii.",
      "Na Starcie są kafle Waga, Tempo i Waga od startu oraz liniowy wykres masy z zakresami od tygodnia do roku.",
      "Sekcja Twoja przemiana porównuje pierwsze i ostatnie zdjęcie z raportów suwakiem, a kafle wymiarów pokazują wagę, pas, ramię i brzuch.",
      "Ze Startu usunięto stare kafle posiłków, makro, check-inu i deficytu — te dane zostają w innych ekranach aplikacji.",
      "W raporcie można zapisać obwód ramienia i brzucha (pola armCm oraz abdomenCm) obok dotychczasowych pomiarów.",
    ],
  },
  {
    title: "2026-09 — poprawki produkcji (Analiza, Android, PWA, UI)",
    date: "2026-09-19",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Naprawiony crash po wejściu w Analizę (kolejność hooków w CoachChatFab).",
      "Stary service worker next-pwa jest wyrejestrowywany, żeby produkcja nie trzymała poprzedniego UI.",
      "GET /api/android/version i /android-version.json są publiczne — aplikacja Android pobiera wersję bez logowania.",
      "Ekrany w aplikacji korzystają z tego samego czarno-złotego języka co logowanie.",
      "Akademia znowu może osadzić GymBrat w iframe (CSP frame-ancestors), bez linków siostrzanych w samym GymBrat.",
    ],
  },
  {
    title: "2026-09 — nadzór wdrożeń z repozytorium GymBrat",
    date: "2026-09-19",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: undefined,
    bullets: [
      "Agent Deploy Guardian pilnuje, żeby wdrożenie szło wyłącznie z github.com/damianchmielewski33-cmyk/GymBrat.",
      "Każda zmiana widoczna dla użytkownika musi mieć jasny, pełnozdaniowy opis w changelogu tej aplikacji.",
      "Publiczny GET /api/version pokazuje commit, gałąź i zaufanie źródła z tego repozytorium — nie z AWP.",
      "CI blokuje PR-y, które ruszają UI bez aktualizacji changelogu albo pochodzą spoza repozytorium GymBrat.",
    ],
  },
  {
    title: "2026-09 — start i osadzanie w Akademii",
    date: "2026-09-18",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    sha: "06820a0",
    bullets: [
      "Strona startowa i logowanie dostały czarno-złoty motyw ze zdjęciami siłowni (commit 15fe94f z tego repo).",
      "Akademia może osadzić GymBrat w iframe — nagłówki i CSP pochodzą z repozytorium GymBrat, nie z AWP.",
    ],
  },
  {
    title: "2026-05 — stabilność, dostępność, offline",
    date: "2026-05",
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    bullets: [
      "Limitowanie zapytań API (trening, raporty, panel admina).",
      "Dziennik zmian w panelu administratora (AI globalnie, role, dostęp do AI).",
      "Briefing i analiza: spójne fallbacki bez modelu AI; bez brandingu „Trener AI”, gdy konto nie ma uprawnień.",
      "Czat trenera ukryty, gdy AI jest wyłączone globalnie i nie skonfigurowano wyszukiwarki (Custom Search).",
      "Kolejka zapisu treningu przy braku sieci (IndexedDB) — automatyczna synchronizacja po powrocie online.",
      "Eksport JSON/CSV w profilu; checklista pierwszych kroków na Start.",
      "Powiadomienia PWA (gdy karta otwarta) — ustawienia w profilu.",
      "Szkielet i18n (np. nawigacja) — rozszerzalny na kolejne języki.",
    ],
  },
  {
    title: "Planowane",
    planned: true,
    sourceRepo: GYMBRAT_GITHUB_SLUG,
    bullets: [
      "Dalsza synchronizacja sesji między urządzeniami (konflikty, natychmiastowy push).",
      "Pełniejsze pokrycie UI w słownikach tłumaczeń.",
    ],
  },
];
